### ISSUE TITLE
Warning: React does not recognize the `X` prop on a DOM element

### ISSUE THREAD

**Issue by niawjunior** [styled-system/styled-system#1044]
I use ant design and styled-component

and then I use styled-system for custom some style but I got this error

```
const Footers = () => {
  return (
    <StyledFooter textAlign="center">BisMarck</StyledFooter>
  )
}
```
Warning: React does not recognize the `textAlign` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `textalign` instead. If you accidentally passed it from a parent component, remove it from the DOM element

**Comment by localnet** [comment]
I think it is a `styled-components` trouble, related with this:

https://styled-system.com/guides/removing-props-from-html/#styled-components

**Comment by jxnblk** [comment]
Yes, it is. See https://styled-system.com/guides/removing-props-from-html

**Comment by klawingco** [comment]
A way to managed this on styled-components is by using  withConfig. You can tweak the shouldForwardProps to return true or false. 

e.g

```javascript
const StyledTitle = styled(Title).withConfig({
  shouldForwardProp: (prop) => !['justifyContent', 'alignItems'].includes(prop),
})<FlexboxProps>`
  ${flexbox}
 `

```
