### ISSUE TITLE
Ability to omit `size` prop when using the `layout` function

### ISSUE THREAD

**Issue by ConnorTCM** [styled-system/styled-system#1066]
Hi @jxnblk. Really enjoying using Styled System, but I was wondering if there is any way to omit just the `size` prop when including the `layout` function? I've found the `size` prop name is a bit odd as being able to alter the size of a component (in more ways than just the height and width) is something that I do quite frequently. Being able to omit it would help reduce a fair amount of refactoring of existing components.

**Comment by jxnblk** [comment]
You can compose only the props you want to use, e.g.

```js
import { layout, compose } from 'styled-system'

const styleProps = compose(
  layout.width,
  layout.size
)
```
