### ISSUE TITLE
How do I add an alias to a theme (eg. fontSizes)

### ISSUE THREAD

**Issue by spaut** [styled-system/styled-system#1100]
Sorry if this is a really dumb question.

Running Gatsby, styled components, and styled system.  

Trying to following the documentation below, but if I just add 'fontSizes.body = fontSizes[2]' to my theme.js file, I get an error.
export default {
    colors: {
      darth: '#000e1a',
      spartan: '#357EDD',
    }
    space: [0, 4, 8, 16, 32, 64, 128, 256, 512],
    fontSizes: [15, 16, 18, 20, 24, 32],
    fontSizes.body = fontSizes[2],
  }

Error:  error  Parsing error: Unexpected token, expected ","   (it doesn't like the  '.'  between fontSizes and body.  

FWIW, total noob to Gatsby, React, etc..

Thank you.

---- Documentation I'm trying to follow  ------

Scale Aliases
For typically ordinal values like font sizes that are stored in arrays, it can be helpful to create aliases by adding named properties to the object.

// example fontSizes aliases
fontSizes: [12, 14, 16, 20, 24, 32]
// aliases
fontSizes.body = fontSizes[2]
fontSizes.display = fontSizes[5]

**Comment by spaut** [comment]
Just realized there is probably a more appropriate place for this: 

https://spectrum.chat/styled-system/general/how-to-add-an-fontsizes-alias~f91b4031-3930-4b2e-8e1a-030e4d718cc1

**Comment by jxnblk** [comment]
You can modify an object after defining it with dot notation like this:

```js
const theme = {
  fontSizes: [ 12, 14, 16, 24, 32 ],
}

theme.fontSizes.body = theme.fontSizes[2]
```

**Comment by spaut** [comment]
Thank you, @jxnblk.
