### ISSUE TITLE
Props forwarded which should not be forwarded

### ISSUE THREAD

**Issue by KennyLindahl** [styled-system/styled-system#1148]
**Describe the bug**
We have seen inconsistencies with certain props being forwarded.
The expected behaviour is that no props that styled-system can identify as css properties should be forwarded at all, but still props such as fontSize is forwarded as font-size when using `css` from `@styled-system/css`.

**To Reproduce**
Check demo of issue here:
https://codesandbox.io/s/boring-bassi-54bg9

Note: Using styled-components or emotion gives the same result.

```js
import css from '@styled-system/css'

const StyledInput = styled.input`
  ${props =>
    css({
      fontSize: props.fontSize, //Is forwarded as font-size="x"
      textAlign: props.textAlign, //Is not forwarded
    })}
`
```

```js
<StyledInput
  fontSize={this.props.fontSize}
  textAlign={this.props.textAlign}
/>
```

**Expected behavior**
Should not forward any of the props that styled-system accepts.

**Screenshots**

![Screen Shot 2020-02-20 at 8 47 01](https://user-images.githubusercontent.com/1323068/74911943-fa362c00-53bd-11ea-840a-6507b18ee75f.png)

Thanks in advance

**Comment by jxnblk** [comment]
Styled Components does not offer an API to filter props from being rendered as HTML attributes, but Emotion does. See https://styled-system.com/guides/removing-props-from-html

**Comment by KennyLindahl** [comment]
@jxnblk Yes, but why is some props forwarded and some not? It has to do with `styled-system` because this is reproduced both on `emotion` and `styled-components`. 

I know `emotion` provides this, but it's preferable to avoid wring this every time your use `css({...})` since it could be handled internally by `styled-system`. It looks like it is handled, but not on all properties.

**Comment by jxnblk** [comment]
The libraries forward props that are valid HTML or SVG attributes by default
