### ISSUE TITLE
Default export seems to be incorrect

### ISSUE THREAD

**Issue by betalb** [styled-system/styled-system#1160]
**Describe the bug**
According to documentation, there is a default export in styled-system package, but looking at the code there is no such export. This one looks the closest one (https://github.com/styled-system/styled-system/blob/master/packages/styled-system/src/index.js#L191), but it is named export (`style`), not the default one

**Comment by Flavien-Pensato** [comment]
Update the doc seems more appropriate WYT ?

**Comment by betalb** [comment]
This might be a good option

**Comment by Flavien-Pensato** [comment]
I didn't know where exactly the docs said so but we can close this one

**Comment by jxnblk** [comment]
There is no default export from the `styled-system` package. If any of the docs or examples show that, they should be updated

**Comment by betalb** [comment]
Sorry, looks like I messed things up a little bit and confused styled-system and styled-components documentation :)
