### ISSUE TITLE
Automatic multiplication of space numbers 

### ISSUE THREAD

**Issue by paramsinghvc** [styled-system/styled-system#1299]
space parameters like pr, pl are being converted non-deterministically to weird values like `pr={4}` gets converted to `paddingRight: 32` while 40 remains 40.

CodeSandbox

https://codesandbox.io/s/styled-components-gv2yo?fontsize=14&hidenavigation=1&theme=dark

**Comment by The-Code-Monkey** [comment]
This isn't random your using  the default values and trying to access a key that doesn't exist.

These are the default values: [0, 4, 8, 16, 32, 64, 128, 256, 512];

when you do `pr={4}` you are getting 32 which is key 4 when you do `pr={40}` well there is no key 40 so the fallback is to use the value you entered.

**Comment by paramsinghvc** [comment]
Can there be a flag to control this multiplication? It's a general requirement to expect the numbers being passed into these props to be handled naturally without any modification.

**Comment by The-Code-Monkey** [comment]
there isn't any multiplication going on they are fixed values, if you want different values create your own theme and if you want it to work by multiplication you'll need a custom function.

**Comment by jxnblk** [comment]
This is the intended behavior of Styled System for the current version -- see https://styled-system.com/api#defaults
