### ISSUE TITLE
How make works aliases on Typescript

### ISSUE THREAD

**Issue by stvmachine** [styled-system/styled-system#1302]
Hi I'm trying to make it works `styled-system` on typescript. I already installed `@types/styled-system` but i got this error when I'm trying to declare aliases. I followed other questions, so i think the syntax should be OK:

```js
import { Theme } from 'styled-system';
const fontSizes = [12, 14, 16, 24, 32];

export const theme: Theme = {
  fontSizes,
}

theme.fontSizes.xxsmall = theme.fontSizes[0];
theme.fontSizes.xsmall = theme.fontSizes[1];
theme.fontSizes.small = theme.fontSizes[2];
```

And the error that i have is: ```Property 'body' does not exist on type 'ObjectOrArray<TLengthStyledSystem, string | number | symbol>'.
  Property 'body' does not exist on type 'TLengthStyledSystem[]'.```

I hope someone can help with this one 🙏 . Thinking on the issue, the way that we need to apply an alias actually looks really weird. Not sure, how something like this work on JS.

**Comment by The-Code-Monkey** [comment]
@stvmachine The types within the @types package only work for the inbuilt functions, if you have anything in your theme you need to type it up yourself.

**Comment by The-Code-Monkey** [comment]
Another point is I don't have any arrays i have objects that are keyed like arrays e.g.
```
const object = {
  "0": "0",
  "1": "1px"
}
```

**Comment by stvmachine** [comment]
Good tips!, i think probably the object keys as array is probably less hacky for typescript.

**Comment by The-Code-Monkey** [comment]
I'm not sure why your getting an issue there, to be fair I've not tested the inbuilt functions yet that may be something you have to type on a component basis using `typeof` and `keyof typeof` again.

**Comment by The-Code-Monkey** [comment]
Let me know what your solution was, whether there is a global way or if it's component based.

**Comment by stvmachine** [comment]
Considering the code that i already posted, if i discard the **responsiveness** for color, it would work. It's a shame, of course. The solution should be something: 

```js
// theme.ts
import * as CSS from 'csstype';

export interface ThemeColors {
  black: CSS.ColorProperty;
  white: CSS.ColorProperty;
}

export const colors: ThemeColors = {
  black: '#000000',
  white: '#fffffff'
};

const theme = {
  colors: {
    ...colors,
  }
}

export type ThemeType = typeof theme;
export type ThemeColor = keyof typeof colors;

// Button.tsx
import { StyledButton, StyledButtonProps} from './Button.styles.tsx';
const Button = ({color, backgroundColor}: ButtonProps) => <StyledButton color={color}/>);

//Button.styles.tsx
import styled from 'styled-components';
import {
  color,
  //not import from colorProps
  fontSize,
  FontSizeProps,
  layout,
  LayoutProps,
} from 'styled-system';
import { ThemeType, ThemeColor } from '../theme';

interface ThemeProps {
  theme?: ThemeType;

export type ButtonProps = FontSizeProps<ThemeType> &
  LayoutProps<ThemeType> & {
    color?: ThemeColor;
    backgroundColor?: ThemeColor;
  };
 
export const ButtonWithVariations = styled.button<ButtonProps & ThemeProps>`
  ${color}
  ${fontSize}
  ${layout}
```

**Comment by The-Code-Monkey** [comment]
Yeah i thought that would be the solution, let me know if you get anything more than this

**Comment by tonyghiani** [comment]
Hey @stvmachine, I don't know if it's the best solution, but I managed to solve the aliases typing with the styled-system aliases in the following way:
```js
/**
 * Theme settings
 */
const theme = {} as DefaultTheme;

export default theme;

export interface DefaultTheme {
  breakpoints: ThemeScale<string, BreakpointAlias>;
  ...
}

export type ThemeScale<Type, Aliases extends string> = Array<Type> & Record<Aliases, Type>;
export type BreakpointAlias = 'mobile' | 'tablet' | 'desktop' | 'widescreen';

theme.breakpoints = ['32em', '48em', '80em', '120em'] as ThemeScale<string, BreakpointAlias>;
[
  theme.breakpoints.mobile,
  theme.breakpoints.tablet,
  theme.breakpoints.desktop,
  theme.breakpoints.widescreen
] = theme.breakpoints;
```

Any better solution is more than appreciated!
