### ISSUE TITLE
[@styled-system/css] Performance issue due to Object.assign in _extends

### ISSUE THREAD

**Issue by MichaelDeBoey** [styled-system/styled-system#1306]
**Describe the bug**
Just like @CompuIves described in codesandbox/codesandbox-client#4018, there's en enormous performance hit due to the fact that `@styled-system/css` is using `Object.assign`.

> Replaces `@styled-system/css` with a version that doesn't use Object.assign, since that's very expensive for us. It improves render time 3 times for rendering components that use `css`.

Node 8 [supports](https://node.green/#ES2018-features-object-rest-spread-properties) Object spreading, so I think this is something that can be fixed upstream and more people could benefit from this win.

**Comment by jxnblk** [comment]
Thanks! `@styled-system/css` is deprecated in favor of `@theme-ui/css` (not officially yet), but if you want to look into a fix, please see the [Theme UI repo](https://github.com/system-ui/theme-ui)
