### ISSUE TITLE
Fix GitHub "used by" counter and install instruction

### ISSUE THREAD

**Issue by aaronadamsCA** [styled-system/styled-system#1316]
I'm not sure why, but GitHub thinks this is the `clean-element` project:

![image](https://user-images.githubusercontent.com/1505561/81033163-78a05700-8e60-11ea-844b-2496e5cacdde.png)

"Used by" is a great metric to gauge a project's popularity, IMO more than watchers/stars/forks. You're probably underselling yourselves right now, then!

I think it's a repo configuration thing.

**Comment by jxnblk** [comment]
Thanks! Last time I checked, GitHub didn't support a way to change this -- please let me know if that's not the case anymore

**Comment by aaronadamsCA** [comment]
There should be a setting somewhere in your repository settings that looks something like this:

![image](https://user-images.githubusercontent.com/1505561/81760636-c9820200-9495-11ea-8f83-70c35ce3f5a9.png)

**Comment by jxnblk** [comment]
I definitely do *not* have that in the settings for this repo. Might be due to feature flagging, but I don't think there's a resolution here...
