### ISSUE TITLE
Breakpoints object in theme and variant are incompatible

### ISSUE THREAD

**Issue by ludovicmnji** [styled-system/styled-system#1318]
**Describe the bug**
When I define the breakpoints as an object in theme, the use of `variant` provoke an error `breakpoints.map is not a function`. 

**To Reproduce**

https://codesandbox.io/s/laughing-herschel-jee44?file=/src/App.js

**Expected behavior**
I don't know if it's a bug or a limitation of styled-system due to internal computation but I would expect to do not have to define my breakpoints as an array and override it as an object because  

**Additional context**
I try to do that because I try to use styled-system in a Typescript project. TS doesn't allow to define an array and next define array like that.

**Comment by jxnblk** [comment]
Variants *only* support responsive array values and breakpoints defined as arrays. The only place you can use plain objects as breakpoints is as prop values

**Comment by ludovicmnji** [comment]
Ok I understand! 

So maybe someone has a solution for Typescript because doing this in TS file is forbidden:

```ts
const breakpoints = ["30em", "40em", "50em", "80em"]
breakpoints.sm = breakpoints[0];
breakpoints.md = breakpoints[1];
breakpoints.lg = breakpoints[2];
breakpoints.xl = breakpoints[3];
```

I got an error on each alias line:

`Property 'sm' does not exist on type 'string[]'.`

**Comment by jxnblk** [comment]
This library isn't written in TypeScript so I may be wrong here, but I believe you can use numbers as keys in TypeScript to get around this limitation:

```js
// e.g.
breakpoints: {
  0: '30em',
  1: '40em',
  sm: '30em'
}
```

**Comment by ludovicmnji** [comment]
Yes I tried this way and it works well in Typescript but I always have the `breakpoints.map` error at runtime 😢 

I suppose to support it you will have to change each function that use only array breakpoints to check if it's an object or an array and get `Object.keys(breakpoints)` ?

**Comment by gustavo-cordeiro** [comment]
@ludovicmnji you can use [`Type`](https://www.typescriptlang.org/docs/handbook/advanced-types.html#type-aliases) to work with this kind o data asign

```js
type BreakpointsProp = Array<string> & {
  sm?: string,
  md?: string,
  lg?: string,
  xl?: string,
}

const breakpoints:BreakpointsProp = ["30em", "40em", "50em", "80em"]
breakpoints.sm = breakpoints[0];
breakpoints.md = breakpoints[1];
breakpoints.lg = breakpoints[2];
breakpoints.xl = breakpoints[3];
```

**Comment by ludovicmnji** [comment]
@gustavo-cordeiro Thanks, it seems to be the best compromise to be able to use `variant` without problem for that case.

**Comment by leandrojo** [comment]
Works for me

```tsx
interface Breakpoints extends Array<string> {
  sm?: string;
  md?: string;
  lg?: string;
  xl?: string;
}

let breakpoints: Breakpoints = ['600px', '960px', '1280px', '1920px'];

breakpoints = {
  ...breakpoints,
  ...{
    sm: breakpoints[0],
    md: breakpoints[1],
    lg: breakpoints[2],
    xl: breakpoints[3],
  }
};
```
