### ISSUE TITLE
[TypeScript?] Pass props to used components

### ISSUE THREAD

**Issue by damianon** [styled-system/styled-system#1330]
Hi,

i searched through the issues but most were just about (not) passing props to html elements. What I'm wondering is if there's a more elegant way to pass some props of a component to a used component inside:
I'm using typescript but I imagine this could also be an issue without it.

```typescript
const Link: React.FC<{someFlag: boolean; } & MarginProps> = props =>{
    return (
      <Box {...margin}>
        {props.someFlag && <span>Text</span>}
      </Box>
    );
}
```

My issue is in how to properly get margin out of the props and not passing on someFlag.
Currently I'm using a custom function, but that doesn't seem to be a very nice solution, especially if I want to use other props too.

```typescript
function extractMarginProps(props: any & MarginProps): MarginProps {
    return {
        m: props.m,
        margin: props.margin,
        mt: props.mt,
        marginTop: props.marginTop,
        mr: props.mr,
        marginRight: props.marginRight,
        mb: props.mb,
        marginBottom: props.marginBottom,
        ml: props.ml,
        marginLeft: props.marginLeft,
        mx: props.mx,
        my: props.my,
    };
}
```

**Comment by damianon** [comment]
My solution seemed to work initially, but aparently doesn't even work now (maybe it never did?).
If I only set mr it is aparently overwritten by marginRight undefined and no margin is set.

**Comment by lwolle** [comment]
You could expose some api to allow customization of the internally used component? Would that be an option for you. 
https://eng.uber.com/introducing-base-web/

**Comment by vaishal** [comment]
Rebass does something like this where margin props are picked and omitted, you can create a similar utility based on it here https://github.com/rebassjs/rebass/blob/master/packages/forms/src/index.js#L23

**Comment by damianon** [comment]
That seems to be the best solution so far. Thanks
