### ISSUE TITLE
Props `size` override the `width` props

### ISSUE THREAD

**Issue by gustavo-cordeiro** [styled-system/styled-system#1436]
**Describe the bug**
Props `size` override the `width` props

**To Reproduce**
```js
layout({width: [0.5, 1], size: ''}) // results in {width: "", @media screen and (min-width: 599px): {…}, height: ""}
layout({width: [0.5, 1]}) // results in  {width: "50%", @media screen and (min-width: 599px): {…}}
```

**Expected behavior**
I don't know if it's a bug or a spec of styled-system. But this rules are not in the docs, and if you pass props `width` and `size` you get the wrong value for `witdh` css value;

**Additional context**
I was try to use styled system with Web Components, and for implementation I pass all maped props to my Emotion instance; 
Because of that, I noticed this behavior

**Comment by timothymathison** [comment]
@gustavo-cordeiro, I was able prevent this issue, by passing `width` **after** `size` in the `props` object.
