### ISSUE TITLE
Using custom props with CSS and Variant

### ISSUE THREAD

**Issue by fcisio** [styled-system/styled-system#1497]
Hi, I've been having a hard time creating variants or using the css prop. Neither seem to work with custom props.

> For example, let's say I have a custom prop:
```js
const _aspectRatio = {
  aspectRatio: {
    property: '--aspect-ratio',
    scale: 'ratio',
    transform: (value, scale) => `${scale[value]}`,
  },
}
```
> Then I want to use that prop in a variant:
```js
variant: {
    prop: 'variant',
    variants: {
      tall: {
        aspectRatio: [3,4,5]
      }
    }
  }
```

> Or I want to use it with the css prop:

```jsx
<Image css={css({ aspectRatio: [3,4,5] })} />
```

> It doesn't work either way

#### If it is a normal behavior, is it something that could be implemented in the future?

Thanks.

**Comment by fcisio** [comment]
Hi, haven't heard anything in a while, would anyone be able to better understand this.

Thanks

**Comment by vaishal** [comment]
Hi, `@styled-system/css` only works with [these theme keys](https://github.com/styled-system/styled-system/tree/master/packages/css#theme-keys) not any custom ones unfortunately. [Variants](https://styled-system.com/variants) use `css` so that’s why it doesn’t work either.
