### ISSUE TITLE
TypeScript Error: No overload matches this call

### ISSUE THREAD

**Issue by genesis-algorithms** [styled-system/styled-system#1500]
**Describe the bug**
I'm getting this strange error while trying to pass bg prop.

**To Reproduce**
You can see it on every fresh react/typescript install with styled-components/styled-system

Use codesandbox to create a reproduction:
For quick check :https://codesandbox.io/s/intelligent-hopper-67362?file=/tsconfig.json:0-224

**Comment by chrisMYchen** [comment]
@genesis-algorithms 

I just spent a long time figuring this out as well! You still have to define your styled component types explicitly even when using the styled-system functions.

```
interface IProps {
  bg?: string | null;
}
const Button = styled.button<IProps>`
  ${color}
`;

```
Will fix this!

**Comment by martonlanga** [comment]
Does the latest react break the types?

**Comment by genesis-algorithms** [comment]
I'm closing this since @chrisMYchen answer was what I was looking for... Thanks, everyone!
