### ISSUE TITLE
Is the project abandoned?

### ISSUE THREAD

**Issue by svile** [styled-system/styled-system#1547]
I was just looking at the release frequency, current issues, pending pull request, and overall activity as of late; and considering that I myself am experiencing some of the issues already reported, it is hard to not think the case. So, is the project abandoned?

**Comment by lukaskoeller** [comment]
Can you give some insights to this @jxnblk ?

**Comment by leanmiguel** [comment]
In the case that it has been abandoned, do people just fork the repo and try to add their own changes?

**Comment by radar** [comment]
I've been using https://github.com/system-ui/theme-ui as a straight-up replacement for this and it seems (mostly) compatible.

**Comment by lukaskoeller** [comment]
Maybe https://xstyled.dev is an alternative. It is inspired by styled-system but maintained but somebody else

**Comment by fcisio** [comment]
I have migrated from Styled System to Theme UI. Which after some research seem's to be created by some of the same maintainers as Styled System and is also described as "The next evolution of Styled System".

As far as a migration between tools like these goes, Theme UI is fairly easy and quick to migrate to.

The structure is pretty much the same, but there are some bigger differences when it comes to the principles and approaches. All in all, with theme UI you will lose some flexibility to do stuff like custom props, but you'll gain in ease of use and features (color modes, color scheme media query, variants, ...).

> I'm still wondering why there is no mention of Theme UI being the "official" new version of Styled System. Especially since both tools seem to be made by the same people and that Styled System looks pretty much abandoned.

#### Feel free to switch to Theme UI, as to me, this is the only sensible option at this point 🚀

**Comment by bodazhao** [comment]
See https://jxnblk.com/blog/two-steps-forward/ where author suggest people to give **Theme UI** a try (great read to understand history of CSS-in-JS as well)

**Comment by svile** [comment]
I'm confused, according to Github insights, https://github.com/system-ui/theme-ui has also been started by (and primary maintainer) @jxnblk This may indeed be the "Two steps forward". However, considering this unannounced but implicitly deducted faith of Styled Systems, I'm now questioning the future prospects of Theme UI even though there is at least one other maintainer there.

https://xstyled.dev looks promising but does not seem to support react-native yet.

**Comment by xeladejo** [comment]
> https://xstyled.dev looks promising but does not seem to support react-native yet.

I have not tried, but I think ‘@xstyled/system‘ can support react-native and ‘@xstyled/styled-components‘ will support it [soon](https://github.com/smooth-code/xstyled/pull/140).

**Comment by eybbus** [comment]
I just find it bit odd that there is nothing in the README or announcement about the current status of the project. It would be nice to know if this project is done and what people should move on to.

Is there a fork that is being maintained?

**Comment by roginfarrer** [comment]
Hi all, I'm maintaining a fork that also adds a handful of frequently requested features from the issues here. The libraries aren't entirely identical (doesn't have all of the different styled-system packages) but the foundation is there.

https://github.com/system-props/system-props

Here's a shortlist of what's been added:

* Rewritten in TypeScript, including types for props
* Support for configurable pseudo props, similar to Chakra-UI's PsuedoBox
* Support for theme values in shorthand properties (e.g., margin, padding, border, box-shadow, etc)
* Designate theme values with a `$` prefix

**Comment by dmt0** [comment]
This is not the first project by @jxnblk that was abandoned abruptly. 
I'm now maintaining a project that's based on https://github.com/jxnblk/system-components/ and not even sure what to migrate to.
I'm also worrying about the future direction here.

**Comment by fcisio** [comment]
Hey @dmt0 
I was in the same situation and made the switch to [Theme UI](https://theme-ui.com/getting-started), It's very similar to Styled System and the migration is pretty easy. There are some functionalities that aren't there, but others that make it worthwhile.

A lot of works have been done recently, and the project is pretty active.

I'd suggest you try it out!

**Comment by svile** [comment]
I'm closing this issue. It's been 7 months now and I think my original question has been answered, albeit  implicitly. There are already some great alternatives listed here which we can all pick from. Happy coding!

**Comment by httpete** [comment]
> Hey @dmt0
> I was in the same situation and made the switch to [Theme UI](https://theme-ui.com/getting-started), It's very similar to Styled System and the migration is pretty easy. There are some functionalities that aren't there, but others that make it worthwhile.
> 
> A lot of works have been done recently, and the project is pretty active.
> 
> I'd suggest you try it out!

Isn't Theme-ui Emotion under the hood? That wasn't a hard transition?

**Comment by dmt0** [comment]
I'd stay away from projects done by these guys altogether. It's all fun and games if you're using it for a toy project, but if you need to maintain something long term, it's a no-go. There are 3 abandoned projects now:

- https://github.com/jxnblk/system-components/
- https://github.com/rebassjs/components
- this one
- System UI - will it reach 1.0 and be abandoned right after in pursuit of a new "philosophy" or before 1.0?

No communication in the repos. No clear migration paths. Nothing.
Ripping out frameworks from production projects is not fun. I'd rather use something stable and focus on functionality.
`</rant>`

Credit where credit is due - all of those projects are actually really nice to use. But without long-term support all of this is for nothing.

**Comment by fcisio** [comment]
@httpete 
The migration between Styled Components to Emotion was very simple. The syntax is 99% the same.

The only difference being how global styles are handled, and the class composition. But overall not much at all.

As for staying off these projects, I do get the point, it is a very valid one. And I'm using Theme UI in production, so I'd like to believe it's gonna stay active for a while. But I haven't seen any activity from @jxnblk ever on that project. It's the community that keeps it going.

So far they're doing an incredible job.

**Comment by South-Paw** [comment]
I also made a [fork of styled-system](https://github.com/spicy-ui/styled-system) and added some improvements and fixes to it (plus wrote it in Typescript).

Even though the types aren't 100% there, the library functions mostly the same as this one (and the exceptions are noted in the readme) and I intend to support it going forward as I made a [design system](https://github.com/spicy-ui/core) a top it and use that in some medium to large client projects.

**Comment by sijad** [comment]
I like https://github.com/ppiyush13/react-styled-flex simple approach

**Comment by ebellumat** [comment]
> Maybe https://xstyled.dev is an alternative. It is inspired by styled-system but maintained by someone else.

There's any support to variants?

**Comment by luuk777w** [comment]
xstyled.dev is a great alternative! It is a near drop-in replacement for styled-system

**Comment by mglavall** [comment]
I

> xstyled.dev is a great alternative! It is a near drop-in replacement for styled-system

If it wasnt because it replaces styled-components entirely

**Comment by The-Code-Monkey** [comment]
https://github.com/The-Code-Monkey/styled-system/ continuation of the project here for anyone who wants it
