### ISSUE TITLE
Styled-systems doesn't appear on the web as it does on mobile. Expo 

### ISSUE THREAD

**Issue by berat** [styled-system/styled-system#1695]
Hello there,

Today I started a project with expo and I wanted to use styled-system. I created and used a custom component with the Styled-system. While it looks fine on mobile, styles are not coming on expo web. What is the reason of this?

To show the code I wrote as an example, I wrote the text component and home screen as follows.

This is how it looks on iOS and on the web.
![Screen Shot 2020-11-14 at 17 42 51](https://user-images.githubusercontent.com/10505575/99149797-4c805100-26a1-11eb-8a0b-1c05b2764a38.png)
![Simulator Screen Shot - iPhone 12 Pro Max - 2020-11-14 at 17 46 10](https://user-images.githubusercontent.com/10505575/99149799-5013d800-26a1-11eb-8883-ed044fa0c0e4.png)

```
'Text.js
import {Text as T} from 'react-native';
import styled from 'styled-components';
import {compose, color, size, typography, space} from 'styled-system';

const Text = styled(T)(compose(typography, space, color, size));

export default Text;
```
```
'Home.js
import React from "react";

import { Text, Input, Box, Button } from "../components/style";

export default function HomeScreen({ navigation }) {
  return (
    <Box flex={1} justifyContent="center" alignItems="center">
      <Text fontSize={21}>Search a movie</Text>
      <Input
        width="90%"
        height={70}
        px={20}
        fontSize={20}
        bg={"#ddd"}
        color="black"
        mt={10}
        placeholder="movie name"
        borderRadius="normal"
      />
      <Button
        width="90%"
        mt={30}
        bg="0.dark"
        height={70}
        borderRadius="normal"
        onPress={() => navigation.navigate("Details")}
      >
        <Text color="0.light" fontWeight="bold" fontSize={18}>
          Ara
        </Text>
      </Button>
    </Box>
  );
}

```

Repo: https://github.com/berat/expo-example

**Comment by Flavien-Pensato** [comment]
I'm not a react-native guy but are component the same on mobile and web ?

I see `import styled from 'styled-components/native';`

Does it apply on web to ?

**Comment by berat** [comment]
Yeah, you are right. A few days ago I realized the wrong. It works after add the line `import styled from 'styled-components/native'`
