### ISSUE TITLE
is there a way to do pseudo-classes with variants?

### ISSUE THREAD

**Issue by OleksiiKachan** [styled-system/styled-system#1798]
I use styled-system with styled-components
I have 3 types of buttons: primary, secondary and tertiary
I can set bg and color them with variants. but they should also have different styles on hover, focus, active
Is there a way I can do it with variants? like declaring each button kind with styled-components css``?

**Comment by johnnybenson** [comment]
Has anyone else figured this out? It's kind of a deal breaker.

```tsx
const StyledButton = styled.button<Partial<ButtonProps>>`
  ${compose(
    color,
    background,
    fontSize,
    padding,
    borderRadius,
    lineHeight
  )} /* Define Themeable Properties */
  ${variants.size}
  ${variants.kind}
  ${variants.role}

  /* Define Non-Themeable Properties */
  border: 0;
  outline: 0;

  &:focus,
  &:active {
    /* Issue #1 -> CSS vars*/
    box-shadow: 0 0 0 2px ${Color.Black30}, 0 0 0 2px var(--this-should-match-the-background-color);
  }
  &:disabled {
    /* Issue #2 -> How do I target this selector? */
  }
`;
```

Solutions I am after:
1. If variants can set CSS variables, can target anything below (would be super cool)
2. Targeting pseudo selectors

**Comment by OleksiiKachan** [comment]
@johnnybenson looks like this project is abandoned.
https://github.com/styled-system/styled-system/issues/1808
https://github.com/styled-system/styled-system/issues/1547

consider trying https://xstyled.dev/ or https://github.com/system-ui/theme-ui

**Comment by danchristian** [comment]
@OleksiiKachan Why can't you just do this with [variants](https://styled-system.com/variants)? Set different pseudo-classes for each variant and you will get different hover states etc.

**Comment by johnnybenson** [comment]
I stopped using `styled-system` after @OleksiiKachan pointed out that it's abandoned.

It's easy enough to create your own structure and helper method for decoupling the css variations as "variants" without this framework, something like this:

```tsx
const variants = {
  kind: {
    primary: css`
      background: ${({ theme }) => theme.palette.primaryBg};
      color: ${({ theme }) => theme.palette.primaryColor};
    `,
    secondary: css`
      background: ${({ theme }) => theme.palette.secondaryBg};
      color: ${({ theme }) => theme.palette.secondaryColor};
    `,
    tertiary: css`
      background: ${({ theme }) => theme.palette.tertiaryBg};
      color: ${({ theme }) => theme.palette.tertiaryColor};
    `,
  },
  size: {
    normal: css`
      --size: 40px;
    `,
    small: css`
      --size: 20px;
    `
  }
};

styled.button`
  ${getVariantCSS(variants, 'kind')}
  ${getVariantCSS(variants, 'size')}

  padding: var(--size, 40px);
`;

export const getVariantCSS = (
  variants,
  variantProp
) => (props) => {
  return variants[variantProp][props[variantProp]];
};



<Button kind="primary" size="small"/>

<Button kind="secondary" size="small"/>

<Button kind="tertiary" size="normal"/>
```

So far it's working nicely, you can express your variations in vanilla CSS and with typescript types, default props, the interface is fairly robust / clean at scale.

Just avoid css property collisions across variant concerns.
