### ISSUE TITLE
styled-system has been deprecated?

### ISSUE THREAD

**Issue by oeduardoal** [styled-system/styled-system#1808]

**Comment by gregolai** [comment]
@jxnblk hasn't been replying to, or merging, PRs, so I'm guessing so?

**Comment by Psvensso** [comment]
Looks pretty shitty when someone dumps a open source project and starts working for a company (gatsbyjs) without assigning additional maintainers or giving any official news on whats going on. This was such a nice touch to react css-in-js. 

Any alternatives? Forks?
Guess we can just use Chakra's system but we don't want the components, just the style system.
