### ISSUE TITLE
Proposal: universal System component

### ISSUE THREAD

**Issue by istarkov** [styled-system/styled-system#183]
Hi, great libraries, thank you!!!

For now for every simple prop I need to create a new component 
```
const INeedJustBGProp = system({bg: 'red'})
```
And seems like I have a lot of one-two-three liners components. 

What are you think about adding Component to _system-components_ which will be universal React component?

And use it like 

```javascript
   <Universal bg={['red', 'green']}>Blabla</Universal>
```

Source of such component using the public API can be just

```javascript

const Universal extends React.Component {
   constructor(props) {
       this.Component = system(props);
   }
  render() {
     const {Component} = this;
     return <Component {...this.props} />
  }
}
```

**Comment by t49tran** [comment]
I think  the idea is interesting but will it leads us to a performance problem when we create a new `system-component` every time `Universal` component mounted and inserted to the DOM ?
