### ISSUE TITLE
Feature request: Border and box shadow support for React Native

### ISSUE THREAD

**Issue by claudiovallejo** [styled-system/styled-system#302]
I'd love to use `styled-system`'s functions to set `border` and `box-shadow` attributes for React Native styled components.

How can I contribute to this feature? Styled system and styled components have made designing with React for the web a great experience, and I'd love to have that same experience building native apps with React Native.

### Example
Below is an example of how I declare box shadow and border attributes in a styled component.

```
const StyledView = styled.View`
    shadow-opacity: ${themeGet('shadows.top.opacity')};
    shadow-radius: ${themeGet('shadows.top.radius')};
    shadow-color: ${themeGet('shadows.top.color')};
    shadow-offset: ${themeGet('shadows.top.offset')};
    borderBottomWidth: 1;
    borderBottomColor: ${themeGet('colors.silver.dark')};
`;
```

### React Native border and shadow attributes
I also found [this React Native doc](https://facebook.github.io/react-native/docs/view-style-props) that lists all the React Native border props, and [this doc](https://facebook.github.io/react-native/docs/shadow-props) that lists all the shadow props.

Thanks, and looking forward to help with this!

**Comment by jxnblk** [comment]
Thanks and sorry for the delay! Generally I think it could make sense to have a dedicated react native version of styled-system that doesn't include the extra logic needed for media query syntax, and these properties would definitely be good to support

**Comment by claudiovallejo** [comment]
Sounds good, thanks @jxnblk! I'll submit a PR when I find some time to remove the media query syntax and include the react native properties :)

**Comment by ademilter** [comment]
i'm having the same problem 😢

**Comment by jxnblk** [comment]
Going to close this out since no work has been done for React Native support. If anyone would like to pick this up, feel free to open a PR

**Comment by nandorojo** [comment]
I'd like to help with React Native support. I figure we'd have to use the match media API for breakpoints, since CSS doesn't apply. @jxnblk is there anywhere I should look to add this kind of support? Perhaps a separate `native` package?
