### ISSUE TITLE
Where's the community at?

### ISSUE THREAD

**Issue by lucastobrazil** [styled-system/styled-system#322]
Not really an issue, but thought i'd ask here... Where are all we `styled-system` users talking?  I'm loving using this, but wish there was somewhere to discuss ideas / uses etc.

This is where i've been looking: https://spectrum.chat/styled-system

Keen to get the conversation going! ✨

**Comment by lucastobrazil** [comment]
@innerdaze oh interesting, I've never heard of discord before! Tried to check it out but it looks confusing... is it https://discord.me? 

Spectrum has a lot of buzz going around, lots of discussion too.

**Comment by flybayer** [comment]
For a reference point, I'm on Spectrum but not Discord 😏

**Comment by LekoArts** [comment]
@lucastobrazil He means [Discord](https://discordapp.com/) and probably [Reactiflux](https://www.reactiflux.com/)

**Comment by johno** [comment]
I think Spectrum is a better platform for community discussions since conversations and ideas won't be lost in private chat history.

**Comment by peduarte** [comment]
I'm on Spectrum too 👋 

Would love to see the community grow in the coming months.

**Comment by jxnblk** [comment]
I've added a badge for spectrum.chat in the readme – feel free to continue the conversation over there!
