### ISSUE TITLE
grid-template-areas css property expects a string

### ISSUE THREAD

**Issue by will-shaw** [styled-system/styled-system#363]
This may be intended behaviour.

The `grid-template-areas` property expects a String (or non-string; none, initial, etc.) [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-areas).
The following snippet adds an invalid css value
```jsx
<Box gridTemplateAreas="a b" />
```
 and would need to be wrapped in single quotes to be valid
```jsx
<Box gridTemplateAreas="'a b'" />
```
The docs suggest no wrapping is required with:
```jsx
// gridTemplateAreas
<Box gridTemplateAreas='a b' />
```

Should the gridTemplateAreas function return a pre-wrapped string if the value is not; none, inherit, etc?
Or this could just be an update to the docs.

Cheers,
Will

**Comment by jxnblk** [comment]
I haven't looked into how styled-components et al. handle this, but might be helpful to have a codesandbox for comparison, but my guess is that an update to the docs might be in order

**Comment by jxnblk** [comment]
Closing this for now. Feel free to open a PR with a docs update if you have any suggestions for making them better
