### ISSUE TITLE
Add props parameter to transformValue

### ISSUE THREAD

**Issue by namjul** [styled-system/styled-system#367]
I would like to propose a change form
https://github.com/jxnblk/styled-system/blob/b7e35cd526952f50f2f36e029217c6b64fd51aa5/src/index.js#L116
to
```javascript
[css]: transform(get(scale, n) || n, props), 
```
That way i get access to the current props in `transformValue` and make the transformation depended on other values.
I like the simplicity of `transformValue` by only giving me the value but i already stumbled several times on this where the additional props parameter would make things easier.
What do you think?

**Comment by jxnblk** [comment]
Sorry for the delay. For v4 I'm considering passing the "scale" (relevant object from the `theme`) as the second argument. Would that cover the use-case you're looking for or is there something else you're trying to achieve?

**Comment by namjul** [comment]
I had no time checking if this would solve my issue. But i found that by using emotion you would not have access to props since its only providing the theme and and not the props.
https://github.com/emotion-js/emotion/blob/master/packages/core/src/jsx.js#L20

So this would not work for emotion anymore.

**Comment by namjul** [comment]
I had no time checking if this would solve my problem. I will come back to this later.

**Comment by joernroeder** [comment]
Hey, i'm running into this as well. i'm currently trying to calculate some ratio based on a static (no scale) `myConst` value from the theme inside a custom prop transform function. Of course i could pass `myConst` in into every component `<Foo ratio={4/myConst} />` but i'd like to have that handled inside the transform – which feels to be more precise to me but seems not possible right now. 
Providing access to the theme would also enable the use of something like`themeGet('my.path.to.const', 42)({ theme })`  inside the transformer. Those are just some ideas. is there any downside in passing the theme as third argument into the function? Thanks!
