### ISSUE TITLE
Add website icon 

### ISSUE THREAD

**Issue by mukeshmandiwal** [styled-system/styled-system#375]
Currently, the website doesn't have any favicon in the header section.

We need to add an icon for the website. We can use existing `logo.png` from docs folder for this.

**Comment by jxnblk** [comment]
I'm in the process of completely redoing the docs, so if you want to hold off until that's ready that'd be helpful

**Comment by mukeshmandiwal** [comment]
yea sure

**Comment by mukeshmandiwal** [comment]
I am not able to add the website icon because public folder added in  .gitignore

**Comment by jxnblk** [comment]
For Gatsby sites, there's a `static/` folder, see https://www.gatsbyjs.org/docs/static-folder/

**Comment by mfix22** [comment]
This can be closed @jxnblk 👍
