### ISSUE TITLE
Print styles with shorthand array syntax

### ISSUE THREAD

**Issue by mjbyrnes4664** [styled-system/styled-system#379]
As mentioned in [this issue](/jxnblk/styled-system/issues/228) the breakpoints only use the screen media type so any styles generated using the shorthand array syntax only apply to screen and are lost when printing.  Is it possible make the media query reference both screen and print so that styling is not lost when printing and doesn't have to be duplicated?

**Comment by jxnblk** [comment]
Currently all the media queries in styled-system are scoped to `screen` and I'm not currently considering changing that. I *think* a separate utility with a separate prop for showing and hiding in `@media print` is the best way to go currently

**Comment by mjbyrnes4664** [comment]
Would you suggest a separate utility outside of `styled-system`? Or maybe another shorthand prop specific for generating print styles?

**Comment by jxnblk** [comment]
Generally I think print styles should be handled outside of this library, yes (as stated in #228). But it might help shed light on your issue to know *which* CSS properties you'd want to control both for media width and for print

**Comment by mjbyrnes4664** [comment]
The issue I'm having is printing a page that is styled mobile first.  I use a lot of the array syntax for properties such as margin, padding, width, flexDirection, etc. When I print the page I end up with a printed version of the mobile view rather than the larger screen view. I'd like to be able to print the view of a larger breakpoint without duplicating all of the styles of that breakpoint with `@media print` in my codebase

**Comment by mjbyrnes4664** [comment]
Update:
I found a work-around using the `mixed` functionality to generate printer friendly components from existing ones using a `print-` prefix on any existing props.  But it looks like v4.0 will remove the `mixed` utility. Any advice? Here's the PrinterFriendly wrapper component


```javascript
const printStyles = props =>
  mixed(
    Object.keys(props)
      .filter(key => /^print-/.test(key))
      .reduce(
        (styles, key) =>
          Object.assign({}, styles, {
            [key.replace(/^print-/, '')]: props[key]
          }),
        {}
      )
  )

const PrinterFriendly = Component =>
  styled(Component)``
    @media print {
      ${printStyles};
    }
  `
```

**Comment by jxnblk** [comment]
Going to close this out since it seems like you've found a workaround

**Comment by cedricdelpoux** [comment]
@mjbyrnes4664 could you share how without duplicating normal and media print styles in the codebase?
