### ISSUE TITLE
Semi-accidental rewrite

### ISSUE THREAD

**Issue by tol-is** [styled-system/styled-system#385]
I was recently dissecting the styled-system code, trying to understand how it works. I was working on a similar library, basically maintaining a dictionary of method props and configure styles by breakpoint, but at the core its styled-components, so quite similar. 

Anyway I thought I should try and apply my recipe on styled-system and see if i've come up with any improvements or if you find it interesting. I basically rewrote styled-system. 

The main difference is that i merged the `style` and `space` functions and that i'm populating the styles using template literals instead of objects. And i'm using rollup to bundle the code. 

Other than that, it's the same logic. I haven't replicated every feature of styled-system yet, but for example, this is what the api looks like.

```
export const margin = style({
  prop: 'margin',
  shortProp: 'm',
  cssProperty: [ 'margin-top', 'margin-right', 'margin-bottom', 'margin-left' ],
  transformValue: em
});

export const fontSize = style({
  prop: 'fontSize',
  shortProp: 'fs',
  transformValue: rem
});
```

The benchmark also shows its a bit faster, but not by much and also a bit early to read much into it, so i'm just mentioning it.

```
fontSizeNew x 802,807 ops/sec ±0.46% (87 runs sampled)
fontSize x 379,590 ops/sec ±0.37% (86 runs sampled)
spaceNew x 1,016,655 ops/sec ±0.85% (83 runs sampled)
space x 502,807 ops/sec ±0.53% (83 runs sampled)
```

If you have a chance to have a look and let me know what you think, maybe with a bit more work i could come back with a pull request. Or maybe you have other plans, and it's not worth pursuing.

Source
https://github.com/tol-is/styled-system/tree/master/src-new
Example:
https://github.com/tol-is/styled-system/blob/master/examples/new/App.js

Cheers

**Comment by jxnblk** [comment]
Thanks for sharing! Will try to dig into this a little deeper later. It might be worth comparing your implementation with the one in #383 to see if there's any performance gains that could be wrapped up there. As for rollup, this repo doesn't gain anything from using it because the source code is in a single file. For such a small library, it's nice to avoid additional build tools. 

Also, at first glance, it doesn't look like you're supporting object literal values, but let me know if I missed that.

**Comment by tol-is** [comment]
Could you give me an example of object literal value usage?  Is it like?

```
const Heading = styled.h1({
   fontSize: 20
})
```

Also regarding rollup, to be honest, I just really struggle with long files, and there are some benefits, like tree shaking, but indeed less important for a library this size. But that's a separate thread.

**Comment by jxnblk** [comment]
Object literal values can be used like e.g. `<Box width={{ xs: 1, sm: 1/2, lg: 1/4 }} />` see https://github.com/jxnblk/styled-system/blob/master/docs/responsive-styles.md#using-objects
