### ISSUE TITLE
"Composed" attributes

### ISSUE THREAD

**Issue by StevenLangbroek** [styled-system/styled-system#388]
I'm not sure how others are solving this, but I have a use-case that is a little un-ergonomic to solve, that I'd like to discuss. I'm open to hearing whether this falls outside of scope for `styled-system`. I see opportunity for making this a feature of `styled-system`, as it's a relatively straightforward composition (so doesn't violate its functional nature), but opens up a lot of power.

## A little bit about our "buttons".

We have 3 button styles:

- Contained
- Outlined
- Text

These incur (relatively) complex changes, as well as having shared behavior. We expose for example a `stretch` boolean, and a theme-based `size` prop to the external interface, which should change:

- `minWidth`
- `px` & `py`
- `fontSize`
- `borderRadius`
- `lineHeight`

We've encapsulated these in `buttonSizes` tokens (we use YAML):

```yaml
- name: buttonSizes
  value:
    sm:
      minWidth: '80px'
      px: '8px'
      py: '8px'
      fontSize: '14px'
      radius: '8px'
      lineHeight: '20px'
```

In order to make these two responsive though, I've resorted to the following:

```ts
const buttonPadding = style({
  prop: 'size',
  key: 'buttons.buttonSizes',
  cssProperty: 'padding',
  transformValue: (x: unknown) => {
    const { py, px } = x as ButtonSizes;
    return `${py} ${px}`;
  }
});

const buttonFontSize = style({
  prop: 'size',
  key: 'buttons.buttonSizes',
  cssProperty: 'font-size',
  transformValue: (x: unknown) => (x as ButtonSizes).fontSize
});

// etc for the other css properties that should be 
// changed when size changes

// then mix them into a styled component:

const Button = styled(tag.button)`
  ${buttonPadding};
  ${buttonFontSize};
`
```

This way you can control the button's size and stretch responsively:

```jsx
<Button
  size={['md', 'md', 'xl']}
  stretch={[true, true, false]}
>Click me</Button>
```

There's a couple awkward things here:

- I have to override the `transformValue`'s type signature, and the approach the compiler forced me into is, let's say less than elegant. 
- I don't have access to the theme here, because I just get the resolved value. This means for now we've hardcoded theme values in these "tokens" (which we settled on as an acceptable trade-off for now, but one we'd like to reevaluate as we add more and more components). The proposal in #367 would solve this.
- This is a lot of repetition, when I think we could get away with a map of sorts:

```ts
const size = style<ButtonSizes>({
  prop: 'size',
  key: 'buttons.buttonSizes',
  cssProperties: {
    // size's type could be taken from a generic maybe, like above?
    'font-size': size => size.fontSize,
    'padding': ({ px, py }) => `${px} ${py}`
  }
});
```

My code is unoptimized right now and I understand that I could write some helpers to make it less verbose, but I feel like this isn't a completely uncommon use-case, and would like to get some input before I submit a PR :).

Would love to hear your thoughts ✌️

**Comment by StevenLangbroek** [comment]
An alternative suggestion, which wouldn't entirely solve the verbosity, but is worth considering I think for the possibilities it would open up, is thunking `key`, having it take `props: ComponentProps` as argument:

```
const size = style({
  prop: 'size',
  key: (currentValue, props) => themeGet(`buttons.buttonSizes.${currentValue}.minWidth`)(props)
});
```

This would eliminiate the need for `transformValue`, making it simpler (and closer to its intention, I feel like I'm abusing it a little bit).

**Comment by StevenLangbroek** [comment]
I guess a next possible question would be, could we build on that and for example output stuff for `:hover`?

```yaml
buttonColors:
  primary:
    bg:
      default: papayawhip
      hover: red
```

**Comment by albermav** [comment]
I have a similar issue with boolean values. In my case I need some kind of `verticalRythm `prop for a **Paragraph** component. When enabled, the `marginTop`, `lineHeight` and `paddingTop` props of the component should be modified. But these values are dynamically calculated based on other props of the component. I managed to do it without using the style helper. But this is not ideal and if I want to make it responsive, this solution is invalid:

```
const vRythm = props => {
  if (props.verticalRythm === true) {
    const fontName = props.fontFamily || props.theme.baseFontFamily;
    const fontSize = themeGet(`fontSizes.${props.fontSize}`, 16)(props);
    const desiredLineHeight = themeGet(`lineHeights.${props.lineHeight}`, props.lineHeight || 1.25)(props);
    const lineHeight = calculateLineHeight(fontName, fontSize, desiredLineHeight)(props);
    const shift = calculateShift(fontName, lineHeight, fontSize)(props);

    return `
      padding-top: ${shift}rem;
      margin-bottom: -${shift}rem;
      line-height: ${lineHeight }rem;
    `;
  }
};
...
export const Paragraph= styled(Text)`
  ${vRythm}
`;
```

My goal is to be able to do something like this:
`<Paragraph fontSize={['s', 'm', 'l']} lineHeight="copy" verticalRythm>Paragraph text...</Paragraph>
`
so when the fontSize changes based on breakpoints, the `marginTop`, `lineHeight` and `paddingTop` props are updated as well.

**Comment by StevenLangbroek** [comment]
@jxnblk any input on this perhaps?

**Comment by jxnblk** [comment]
As for the original issue, to achieve something like `<Button size={['md', 'md', 'xl']} stretch={[true, true, false]} />`, does the `variant` utility not fit the bill? If it does get more complex than what I'm imagining, I generally suggest wrapping a styled-system primitive with another React component to handle the logic in the props. There's a similar discussion here https://spectrum.chat/styled-system/general/dealing-with-multiple-variants~b808556e-80e9-4c8e-be3f-dde9ae186c44 – and sorry if I'm misunderstanding the original issue here

**Comment by joernroeder** [comment]
@albermav could you find a solution which implements a responsive vertical rhythm? looking into the same thing right now.

**Comment by jxnblk** [comment]
Thanks for the ideas here! I'm unsure of what you'd like to proceed with, but if you're interested in opening a PR or RFC for a new package to help with some of the issues you're trying to tackle, I'm open to it. Closing this issue for now since there isn't a ton of discussion around this
