### ISSUE TITLE
Using new CSS logical properties

### ISSUE THREAD

**Issue by mihai-ro** [styled-system/styled-system#390]
Hi! 👋 
I've recently started using styled-system and I've noticed that it references the old css logical properties for spacing and dimensions.
I think it would be quite nifty to convert these tags to the new ones, so styled-system would still be relevant when developing multiple language websites.
E.g.:
height ->block-size
width -> inline-size
margin-top -> margin-block-start
margin-right -> margin-inline-end
margin-bottom -> margin-block-end
margin-left -> margin-inline-start, etc.
Same thing for padding and top/right/bottom/left.

Here is an article that offers some more information on this topic:
https://medium.com/@elad/new-css-logical-properties-bc6945311ce7

Cheers!

**Comment by jxnblk** [comment]
You can create custom props for any CSS property using the `style` function, see https://github.com/jxnblk/styled-system/blob/master/docs/api.md#style

**Comment by mihai-ro** [comment]
Hey, @jxnblk, I apologise for the late response. Yes, that would be one way of doing it, but it would also imply creating custom { space, width, height, etc. }. 
Yes, I was suggesting this as an update to the library. It is true that we all build apps thinking it in top/right/bottom/left terms; what I suggest is we should keep mx/my/mt/mr/mb/ml and other padding/size relevant shortcuts, but update the new css attributes accordingly.

**Comment by jxnblk** [comment]
I think for now the best option is to use the custom style function utilities to achieve this, even if they are replacements for the built-in ones, so I’m closing this out for now

**Comment by madmanwithabike** [comment]
Hi @jxnblk, I've used a custom style function for this in the past and it works well, but have come to need this in @styled-system/css which I don't think is possible, would you accept a PR adding logical property scale support to the css package? Thanks!
