### ISSUE TITLE
Discussion: blacklist / whitelist terminology vs inclusiveness

### ISSUE THREAD

**Issue by StevenLangbroek** [styled-system/styled-system#391]
I'd like to bring up that there are issues with the term blacklist. A recent incident:

https://twitter.com/BenLesh/status/1095487146251546624

Since you're close to releasing a breaking version, maybe this is a good time to consider changing this terminology to something more inclusive? I'd be more than willing to make the changes to code & documentation if you agree this is the right thing to do. If you think it is, but not now, I'd love to hear when you think is :).

Thanks ❤️

**Comment by jxnblk** [comment]
Yeah, if this has even the *potential* to offend, I'm happy to change – and I apologize if this has been exclusive/offensive to anyone

**Comment by wtgtybhertgeghgtwtg** [comment]
It'd be one thing if it was changing documentation or something, but this is a breaking change.  It seems like an undue burden to users to force them to refactor.

**Comment by StevenLangbroek** [comment]
@jxnblk 🙇‍♀️

@wtgtybhertgeghgtwtg there's a breaking change coming up, and we could provide a codemod. I've written them before (see styled-components v4 codemods), and would happily provide one. With regards to user burden, I'd point you to some other projects that have gone through these changes, some of them you might have heard of:

- https://github.com/graphite-project/graphite-web/pull/1700
- https://www.theregister.co.uk/2018/09/11/python_purges_master_and_slave_in_political_pogrom/
- https://github.com/django/django/pull/2692

**Comment by StevenLangbroek** [comment]
@jxnblk some alternatives:

- `pick` / `omit`
- `allow` / `deny`
- `safelist` / `blocklist`

I'm ambivalent about which one, so would like to defer to either someone who can provide a more valuable perspective, or if none speak up, to you and/or other maintainers.

**Comment by wtgtybhertgeghgtwtg** [comment]
In those examples, it was either a deprecation, documentation, or internal change.  Upgrading did not break user code.  Personally, I think `pick` and `omit` are more concise, but I don't think users should have to refactor for that reason without being given a deprecation warning or something.

**Comment by jxnblk** [comment]
AFAIK the only places these terms are used are in subpackages, which I'd generally recommend not using at this point since styled-components has incorporated some of their functionality into the core styled-components API. For anyone still using something like clean-tag, it wouldn't be hard to provide backwards compatibility, even if it's not documented. Arguably, system-components could be removed altogether from this repo since it has been superseded by `@rebass/components`

**Comment by jxnblk** [comment]
@StevenLangbroek I think for `clean-tag`, the prop could maybe be renamed to `omitProps`? What do you think?

**Comment by StevenLangbroek** [comment]
@jxnblk yep sounds reasonable, I'll get on it this week.
