### ISSUE TITLE
property textStyle does not work anymore for the textStyles variant 

### ISSUE THREAD

**Issue by trival** [styled-system/styled-system#403]
Hi, thanks for this great library. 

After upgrading to version 4.0.0 the `textStyle` property on my components stopped working. I needed to change the property name to `variant` to get the behavior back.

I am not sure if this change was intended, but it is out of sync with the docs right now.

Cheers.

**Comment by jxnblk** [comment]
Thanks! Sounds like an unintentional regression. I'll take a look
