### ISSUE TITLE
width/height html attributes

### ISSUE THREAD

**Issue by halvves** [styled-system/styled-system#405]
When using the `width`/`height` helpers in styled-system, is there a way to handle wanting to set the `width`/`height` attributes on something like an `<img />` tag to something different than the styled-system/css width?

For instance... I make some kind of Atom/Box/Buildingblock component that consumes helpers like `display`, `width`, `height`, and `space`. If I then want to use it in some kind of layout with an `<img />`:

```
<Atom is="img" display="block" width="100%" height="auto" src="..." />
```

...I have no way (that I know of) to directly set the img's `width` attribute to something other than the `100%`, like `256px`.

The only workaround I can conceive of at the moment is to filter/remap some props in an intermediary component like:

```
const Img = ({ imgWidth, imgHeight, width, height, ...rest }) => (
  <img width={imgWidth} height={imgHeight} {...rest} />
);
<Atom is={Img} display="block" width="100%" height="auto" imgWidth="256px" src="..." />
```

A possible fix (but breaking) would be to adjust the api some, making the width/height helpers use props of `w` and `h` instead of the full name. This would also fall in line with the shorthand codestyle used in a lot of the other helpers in styled-system.

I may very well just be missing something, or just be totally off base here. I'd be happy to discover that there is already a much better way to handle this case.

**Comment by Dandandans** [comment]
+1

**Comment by nicholaai** [comment]
you can just pass a number value to those props, like `height={200}`, and styled-system will convert that to `200px`;

if your prop has a array associated with it, like spacing, any number passed that is higher than the largest n index ([0, 1,...,n]) in your array should be converted to a pixel value

**Comment by jxnblk** [comment]
Thanks! Im aware of this issue – with the current api, I’d suggest avoiding using those style props with `img` tags that need the width and height attributes or create a custom style function that uses a different prop name, e.g. `cssWidth`
