### ISSUE TITLE
React is a direct dependency of clean-tag

### ISSUE THREAD

**Issue by MatthewLarner** [styled-system/styled-system#406]
https://github.com/styled-system/styled-system/blob/master/packages/clean-tag/package.json#L16

Hello!

clean-tag has React as a direct dependency any chance this could be moved to a peer dep?

It's really only an issue for us when we're linking modules to be honest, albeit annoying.

Cheers

**Comment by jxnblk** [comment]
I've moved all legacy packages to https://github.com/styled-system/extras – feel free to copypasta or fork as needed
