### ISSUE TITLE
Migrate to v4

### ISSUE THREAD

**Issue by ng-hai** [styled-system/styled-system#408]
When upgrade to v4, the `textStyle` seems not to apply to the theme. Some screenshots below:

v3.2.1
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/19520278/53692722-54159e80-3dc7-11e9-88d5-e6044736b41b.png">

v4
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/19520278/53692728-6ee81300-3dc7-11e9-8785-c4ee8ff783e7.png">

Do I need to rewrite the theme and restructure all of my components to make it compatible with the old styles?

**Comment by jxnblk** [comment]
Which version are you using? V4.0.1 fixed an issue with `textStyle`

**Comment by ng-hai** [comment]
Yes, I have installed v4.0.1 but the problem is still there.

**Comment by jxnblk** [comment]
Thanks, can you post a codesandbox for reproduction?
