### ISSUE TITLE
Get fontFamily from theme

### ISSUE THREAD

**Issue by crucialfelix** [styled-system/styled-system#411]
According to the table: https://styled-system.com/table#typography

`fontFamily` should be able to lookup from the `fonts` field in the theme.

This is how I assumed/guessed that was supposed to work:

https://codesandbox.io/s/m5rloz5zp

```
<Text fontWeight="bold" fontFamily="code">
  fontFamily="code" should be courier
</Text>
<Text fontWeight="bold" fontFamily="nice">
  fontFamily="nice" should be verdana
</Text>
```

```
  fontFamily: {
    code: "Courier",
    nice: "Verdana"
  }
```

What we actually get is the value just passed through (it's not treated as a key):

```
<div font-weight="bold" font-family="code" class="sc-iAyFgw besUQg">fontFamily="code" should be courier</div>

.besUQg {
    font-weight: bold;
    font-family: code;
}
```

Is my guess wrong or is it incorrectly (or not yet) implemented?

From here:

https://github.com/styled-system/styled-system/blob/master/src/index.js#L38

Maybe we are supposed to pass in a `transformValue` function that does the job.

    "styled-components": "4.1.3",
    "styled-system": "4.0.1",

Thanks,

**Comment by crucialfelix** [comment]
And right after submitting the issue I notice my theme variable is wrong:
```
// theme
  fonts: {
    code: "Courier",
    nice: "Verdana"
  }

sandbox is updated now.

thanks anyway!

**Comment by crucialfelix** [comment]
The real error I was experiencing was due to using `next.js` and putting the `ThemeProvider` in  `_document.js` It seems that context is not available to pages. So there was no theme, so theme variables are not looked up — they return their input value.

If there is no ThemeProvider / theme then `fontFamily="bigtext"` results in css: `font-family: bigtext` (should log an error or something IMO)

Pages are essentially a different react app, so the ThemeProvider needs to be in an App or Layout that is on every page.

**Comment by jxnblk** [comment]
FWIW/IIRC Next.js also has an `_app.js` component - that's generally where context providers like ThemeProvider should go
