### ISSUE TITLE
Missing "bgColor" deprecation in V4 changelog

### ISSUE THREAD

**Issue by Betree** [styled-system/styled-system#413]
Version 3.2.1 [export a `bgColor` props](https://github.com/styled-system/styled-system/blob/17f2ac54432faaff0caf0b90ed0a2d96f467a4d7/src/index.js#L274) that has been renamed to `backgroundColor` in 4.0

This change is not reflected in the [CHANGELOG](https://github.com/styled-system/styled-system/blob/master/CHANGELOG.md) nor in the [V4 release note](https://github.com/styled-system/styled-system/releases/tag/v4.0.0).

**Comment by jxnblk** [comment]
Thanks! This wasn't part of the public API, so that's why it wasn't mentioned in the changelog
