### ISSUE TITLE
Component child props based on screen size

### ISSUE THREAD

**Issue by markgandy** [styled-system/styled-system#415]
This is a question - I'd like to pass different props to a child component  based on the screen size. I have a menu that overflows into a hamburger when the screen size is small. Something like this:

```
      <Flex flexWrap="wrap" alignItems="center" bg="black">
        <TopNavs navs={[navs[0], navs[1], navs[2]]} />
        <Flex
          width={0.15}
          alignItems="center"
          justifyContent="flex-end"
          pr={[2]}
        >
          <Hide medium large xlarge>
            <Hamburger navs={[navs[3], navs[4]]} />
          </Hide>
        </Flex>
      </Flex>
```

I can hide the hamburger for large screen size, but how to pass different navs props to `TopNavs` and `Hamburger` based on the screen size (I want all 5 navs in `TopNavs` for large screen size)?
This needs to work for SSR as well, as it is a NextJS app.

Is there any way to do something like this?

**Comment by jxnblk** [comment]
This sounds beyond the scope of `styled-system` since it isn't tied to React, but generally you can map over React children with the `React.Children` API and using `React.cloneElement` to add props to children – maybe that can help give you some direction

**Comment by markgandy** [comment]
Yeah that's what I figured, but thought I'd ask. Maybe there is a nice way to do it with rebass / rebass-grid as that is a React thing? Thanks for the pointer around cloning children, will look into it.
