### ISSUE TITLE
Question about change in v4

### ISSUE THREAD

**Issue by namjul** [styled-system/styled-system#421]
In version 4 the following was changes:
> No longer merges returned style object, but returns arrays instead, which should work with common CSS-in-JS libraries

I would like to know why.
My situation is that i use fela and they don't support it. I likely have to move to emotion/styled-components.
I appreciated the atomic css style. I am not sure why it does not get any attention in these two big ones.
Any thoughts on this?

**Comment by jxnblk** [comment]
The fact that Fela doesn't support this is news to me – not intentionally trying to exclude that library. To work around this, a combination of lodash flatten/merge *should* work, but YMMV

**Comment by namjul** [comment]
Do you mind expanding on the reason. Just curious.

**Comment by jxnblk** [comment]
In a nutshell, because the big two css-in-js libraries already handle this, so it offloads the amount of work/code required in this library – I'm certainly not opposed to ensuring support for fela works with a minor version bump

**Comment by namjul** [comment]
I see.
Another situation i came across was when trying to compose your own "buckets" and using already composes styles like space or borders.

So doing something like this:
```javascript
const COMMON = compose(
    color,
    space,
)
```
i would get an array of arrays.
Just FYI.

**Comment by jxnblk** [comment]
So far those libraries handle it like a champ – IIRC they have recursive/deep merging in there

**Comment by vipulrawat** [comment]
Is this related to `styles` object from older versions or `style` utility to create custom style?
As from previous version, I found `styles` object very useful in composing my styles easily, but it got removed in v4, I think.

**Comment by jxnblk** [comment]
@vipulrawat this is unrelated to that change, but as an alternative to the previous `styles` object, there is an optional `props` module for listing out the props https://github.com/styled-system/styled-system/blob/master/props.js

**Comment by vipulrawat** [comment]
@jxnblk Woah, that a quick awesome reply :+1: However, regarding props.js, it is just a static string array right, compared to the `styles` object where I don't have to import anything like `space`, `color` etc. I can directly map them. Am I missing something?

**Comment by jxnblk** [comment]
@vipulrawat yes, `props` is just an array of prop names for reference. You *can* use `import * as system from 'styled-system'` (which will import everything and disable any treeshaking) for something similar to the old behavior, but it will also include the other exported utilities as well

**Comment by vipulrawat** [comment]
Got it, Thanks.

**Comment by jxnblk** [comment]
Closing this since all functions should now return merged object
