### ISSUE TITLE
Export for use directly within styled component

### ISSUE THREAD

**Issue by kristojorg** [styled-system/styled-system#424]
I would like to be able to do the following
```js
import {m} from 'styled-system'

const Avatar = styled.div`
   ${m([2,3])}
`
```
which would then output the required media queries and margin. This is useful to me because in my current projects codebase we are using styled components heavily and it is awkward to define some styles as props and others within the styled component css. I want to be able to write these in the css while hooking in to the theme and writing easy media queries

**Comment by jxnblk** [comment]
You can set `defaultProps` on the component (recommended) or do something like this:
```
const Foo = styled.div`
  ${props => space({ m: [2, 3], ...props })} 
`
```

**Comment by kristojorg** [comment]
Ah yes I was thinking that. The problem with defaultProps is that styled-components doesn't fold default props (yet). Thanks for the suggestion, I'll do that.

**Comment by kristojorg** [comment]
For reference the defaultProps folding issue will be solved here: https://github.com/styled-components/styled-components/pull/2260
