### ISSUE TITLE
Question re Responsive Styles and not rendering a component

### ISSUE THREAD

**Issue by leantide** [styled-system/styled-system#430]
Great library. My only regret is that I found styled-system / rebass after I proliferated styled-components in my project in an inconsistent custom manner. Oh well. At least I can now use your library to get consistent.

Question: Is there a way using styled-system to render a component above a certain screen width breakpoint, and to not render it (or render as null) below that breakpoint?

I am able to do this with [react-responsive](https://github.com/contra/react-responsive), or by using a CSS3 media query, but would be wonderful if I could do this with styled-system.

I observe that using 0 in a responsive style, for example, width = {[0, 1 / 2, 1]} , renders the component as would be expected with a 0 width, which depending on other formatting and its children, can have results very different than not rendering the component.

Thanks.

**Comment by leantide** [comment]
I now see that display = {['none', 'block']} or display = {['none', 'none', 'block']}, etc., meets the need. Thanks.

**Comment by jxnblk** [comment]
If you want to control whether React renders the component at all, you'll need to use something like `react-responsive`, but if the CSS `display` property works for your use-case it sounds like you've figured it out
