### ISSUE TITLE
"Extending" a style

### ISSUE THREAD

**Issue by gausie** [styled-system/styled-system#437]
I sometimes create something like 

```javascript
import { style } from 'styled-system';

const bgHover = style({ prop: 'backgroundColorHover', alias: 'bgHover', cssProperty: 'background-color', key: 'colors' });
```

and then use it like

```javascript
const example = styled.div`
  &:hover {
    ${bgHover}
  }
`;
```

It would be nice to have an "extend" function that would allow me to do that as follows:

```javascript
import { extend, backgroundColor } from 'styled-system';
// extend(styledSystemStyle, prop, alias)
const bgHover = extend(backgroundColor, 'backgroundColorHover', 'bgHover');
```

Maybe having a transformer function might be good too? Like

```javascript
import { extend, backgroundColor } from 'styled-system';
const bgHover = extend(backgroundColor, attr => attr + 'Hover');
```

Thanks for all your great work!

**Comment by gausie** [comment]
Just tried writing roughly how it would work and I realise that only the latter approach would work. But here is the rough idea (seems to work but haven't tested it extensively)

```javascript
const extend = (s, transform) => props => s(
  Object.keys(s.propTypes)
    .reduce((acc, k) => {
      const v = props[transform(k)];
      if (v === undefined) return acc;
      return { ...acc, [k]: v };
    }, {})
);
```

**Comment by jxnblk** [comment]
The refactor in #513 should make this more easily possible. Leaving this comment as a reminder for myself to follow up here
