### ISSUE TITLE
[Question]: Shorthand props being overridden by verbose props

### ISSUE THREAD

**Issue by dkilic** [styled-system/styled-system#441]
Currently verbose props (backgroundColor, margin, padding) always override shorthand props (bg, m, p) for the same property. Normally the prop with the largest component-distance to the html tag overrides the same prop that is closer (and direction-specific props override general props regardless of verbosity).

```
const Box = styled('div')`
	${space}
`;

const Foo = props => <Box margin={1} {...props} />
const Bar = props => <Box m={1} {...props} />

<Foo m={2} /> 		// Will render with space[1]
<Foo margin={2} /> 	// Will render with space[2]

<Bar m={2} /> 		// Will render with space[2]
<Bar margin={2} />	// Will render with space[2]
```

Is this intentional or might it be a bug?

Also thank you for a great library, very well done!

**Comment by jxnblk** [comment]
This is currently how it works yes. I’d advise not mixing shorthand and verbose props together in the same project

**Comment by jxnblk** [comment]
The changes in #513 will mean that prop order takes precedence in v5, so closing this out for now
