### ISSUE TITLE
PropTypes are not enough generic

### ISSUE THREAD

**Issue by neoziro** [styled-system/styled-system#445]
## Problem

[PropTypes are exposed directly in styled-system](https://github.com/styled-system/styled-system/blob/master/src/index.js#L89), I think it is not a good thing. Styled-system is a generic tool and it could be used with another tool than React. In fact it is just a CSS with super power for me.

## Solution

I think we could expose a meta property on styles. This way we could access the necessary informations be able to build `PropTypes` or another thing for another library than React.

This is the approach I used in @smooth-ui/system, [I expose a meta property](https://github.com/smooth-code/smooth-ui/blob/master/packages/system/src/style.js#L76), then [I transform it into prop types](https://github.com/smooth-code/smooth-ui/blob/master/packages/shared/core/utils/propTypes.js#L3).

**Comment by jxnblk** [comment]
I love this idea, and it's something I've been pondering recently as well! It's currently the *only* dependency, so it'd be great to ditch it. With the latest version, all prop types are the same, so I think it's possibly a matter of exposing one prop type function with a reference for styled-system props, possibly in the `meta` object.

Somewhat related, I also recently published this package for use with `@emotion/styled` https://github.com/styled-system/extras/tree/master/packages/should-forward-prop

**Comment by jxnblk** [comment]
Closing in favor of #475
