### ISSUE TITLE
Setting Theme API Defaults

### ISSUE THREAD

**Issue by joe-bell** [styled-system/styled-system#447]
First and foremost thanks for all the effort you've put into `styled-system` and `rebass`, over the last 2 weeks it's really helped change my thinking around Design System architecture.

With larger design systems (ones that incorporate multiple brands that have their own theming schemas for sub-brands) I've found it can be quite difficult to get a common default base. Sticking to a single schema can be difficult as we're assuming too much about what a brand should/shouldn't have 

e.g. let's say one brand has a much larger `space[2]` than the other, so wouldn't be ideal if a defaultProp was set to `mx: 2`. Or one brand background expects a gradient rather than a color.

I hope that makes sense?

One of the solutions I'm thinking for this is being able to **set the styled-system ['smart defaults' set out in the API](https://styled-system.com/api#defaults)**, perhaps via some sort of context. Is this a concept you would support adding? If so I'd be more than happy to contribute.

**Comment by jxnblk** [comment]
Thanks! The idea with something like that would be to create two separate themes. How you create abstractions in places like the `colors` object is up to you, but all of the defaults can be overridden with custom themes/context. Somewhat related, there’s a separate project to create a standard for this sorta thing if you haven’t seen it yet: https://system-ui.com/theme

**Comment by joe-bell** [comment]
I'm not sure I follow sorry! For context what we're doing is something like this:

```
├── base
├── organisation a/
│   └── themes/
├── organisation b/
│   └── themes/
└── organisation c/
    └── themes/
```

Essentially we have a `base` set of components (which align to a default theme) and we'd like each organisation to be in charge of its own theming schema (aligning to system-ui of course!)

The problem stems down to the fact that these defaults create a schema that the organisations will need to follow, when we'd rather leave that down to the organisations to maintain. So being able to set default values would be more ideal. Perhaps I'm looking at this in a completely over-engineered way though!

**Comment by jxnblk** [comment]
Your `base` library can define a base `theme` object, which you'd pass to a `ThemeProvider` component. The organization-specific packages can have their own themes that extend or replace that base theme, allowing you to reuse the same styled components in all the packages. That's how this is designed to work, so I'm not sure I'm following either 🤔

**Comment by joe-bell** [comment]
For sure! But let's say for example we have a button:
```js
// base/components/button.js
import { space } from 'styled-system'

const Button = styled.button({
  space
})

Button.defaultProps = {
  px: 2,
  py: 1
}
```

This would mean that each theme would _have_ to make sure they use their index of `1` or `2` for the button spacing, whereas one organisation may prefer a named approach or have a larger number of spacing variants which means they'd prefer to use `3` or `4` for their buttons. Does that sort of make sense? I know this a super specific example

**Comment by jxnblk** [comment]
For something like that, I'd wrap a base button up into another abstraction, if that makes sense. Maybe your theme includes `space.button.x` and `space.button.y` values that *could* be derived from the core scale, or could be completely one-off. There's a million different ways to do this sorta thing, so don't wanna make too many assumptions about your architecture

**Comment by joe-bell** [comment]
That's not too far off what I was initially thinking! Which was more of some separate config object approach, but I think I prefer your idea of being more explicit and sticking to the system-ui theming schema. Thanks for your time on this Brent, I'll give this idea a go and keep you posted

**Comment by joe-bell** [comment]
Tested this approach out this morning and works like a treat, so I'm happy to close this. Thanks again
