### ISSUE TITLE
Getting `fontSize` key from Theme in String Styles require unit

### ISSUE THREAD

**Issue by peduarte** [styled-system/styled-system#453]
Hey 👋

I came across this unexpected issue earlier, and wanted to verify if this is intended or not.

I'd like to set a default `font-size` to a Component. The value comes from `theme.fontSizes`.

With String Styles:
```js
// When styling with String Styles the unit (px) is required
export const Heading = styled.h1`
  font-size: ${themeGet("fontSizes.2")}px;
`;
```

With Object Styles:
```js
// When styling with Object Styles the unit is not required
export const Text = styled("p")({
  fontSize: themeGet("fontSizes.1")({ theme })
});
```

I've created a [CodeSandbox Demo](https://codesandbox.io/s/2zjjx2lxr0) 👀 

Cheers
👊

**Comment by jxnblk** [comment]
Yup, this is generally how the styled-components and emotion APIs work. Styled System isn't doing anything special here. It's similar to using number types in the React `style` prop

**Comment by peduarte** [comment]
Ahhhh, yes, totally. Should’ve remembered this! Thanks!
