### ISSUE TITLE
Typescript types from library conflict with types of HTML elements

### ISSUE THREAD

**Issue by Lehakos** [styled-system/styled-system#454]
I have next code:
```javascript
import React from 'react';
import styled from 'styled-components';
import { color, ColorProps } from 'styled-system';

const Wrapper = styled.div<ColorProps>`
  ${color}
`;

const Text: React.FunctionComponent<ColorProps> = function ({ children, ...rest }) {
  return <Wrapper {...rest}>{children}</Wrapper>;
};
```
And I have received next error:

```javascript
Type 'string | (string | null)[] | { [key: string]: string; } | undefined' is not assignable to type 'string | (string & (string | null)[]) | (string & { [key: string]: string; }) | undefined'.
  Type '(string | null)[]' is not assignable to type 'string | (string & (string | null)[]) | (string & { [key: string]: string; }) | undefined'.
    Type '(string | null)[]' is not assignable to type 'string & { [key: string]: string; }'.
      Type '(string | null)[]' is not assignable to type 'string'.ts(2322)
```

**Comment by jxnblk** [comment]
This project does not contain any typescript types, could you please clarify the issue?

**Comment by andreoav** [comment]
Got the same error when working with typescript and the `@types/styled-system` package.

I don't have the error if I use `styled-components`, but after changing to `emotion` this error appeared.

**Comment by leebenson** [comment]
Instead of `ColorProps`, import/use `ColorStyleProps`.

**Comment by peduarte** [comment]
@leebenson @Lehakos Hi there 👋 

I'm having the same issue, but on my component I also want to support the `bg` prop and `ColorStyleProps` seem to only solve the `color` prop issue.

Do you have any advice on how to type check this properly?

**Comment by peduarte** [comment]
More info on here: https://spectrum.chat/styled-components/general/typescript-styled-system-styled-components~5593dbf2-7588-4c6d-9e76-b4eadd77ec90
