### ISSUE TITLE
Links to reference table and responsive styles in the README 404

### ISSUE THREAD

**Issue by kbondanza** [styled-system/styled-system#456]
Hi, 

I noticed that the links to the reference table and responsive styles section in https://github.com/styled-system/styled-system/blob/master/docs/getting-started.md, 404.

I'm happy to make a pull request, if that's ok. 

Thanks!

**Comment by jxnblk** [comment]
Thanks! Currently those docs are used to generate the docs site where they *should* work (https://styled-system.com/getting-started). If you want to take a stab at this, I’m not sure if gatsby-plugin-catch-links automatically does anything like stripping the file extension, but the link component in the docs would probably be the place to convert the link href (https://github.com/styled-system/styled-system/blob/master/docs/src/link.js)
