### ISSUE TITLE
Using Styled System with Typescript + Styled Components

### ISSUE THREAD

**Issue by peduarte** [styled-system/styled-system#464]
Hi 👋

I've spent a few days trying to get Styled System + Styled Components to play nicely with Typescript.

I've written about it [here](https://spectrum.chat/styled-components/general/typescript-styled-system-styled-components~5593dbf2-7588-4c6d-9e76-b4eadd77ec90) but didn't get much help.
I've [tweeted](https://twitter.com/peduarte/status/1118842116925526016) about it too, a few folks have tried to help, but we still haven't found a decent solution. 

I've [created a demo](https://codesandbox.io/s/04w296kk6p) to highlight the issue, I tried to keep the demo simple and only using a few props for brevity. The main issue is caused by the use of the `color` prop, since it's a Styled System prop and a HTML Attribute.

The demo covers:
- Allow to pass System Props
- Allow to pass SC's `as` prop
- Allow to interpolate SC props
- Allow to forward props to a child Styled Component (`YellowHeading`)
- Disallow unsupported props

The issues seems to be:
> When you write color={['black', 'white']} as a SS/SC prop, your DOM element actually ends up with an attribute <div color="black,white" />. SC's typings are trying to prevent this.

### Override SC's type checkings by:
- Creating a custom` StyledSystemProps`
[CodeSandbox Demo](https://codesandbox.io/s/zn8m0x5nqm)
☝️ But `color:{["red", "black"]}` doesn't work.

### Introduce custom SS System prop
- Not use `color` SS prop and instead re-create it using the `style` API with a `textColor` prop
- New `textColor` System Prop, using Ss's `style` API
- Create a `TextColorProps` Interface
- Re-create the `ColorProps` type
[CodeSandbox Demo](https://codesandbox.io/s/wyqpkkxo97)
☝️ Everything is working, and I didn't need to mess around with TS, *BUT* the API has changed from `color` to `textColor` - I don't like this.

---

## What's the solution?
I'm not sure and I'm running out of brain capacity to solve this issue, hence why I'm creating this issue. It's not necessarily an issue with Styled System, but SS is playing a part in it, due to the naming convention of its system props.

### Should system props be namespaced?
More and more projects are being built on TS, and this is only gonna rise. This is why I'm also proposing that SS is [built on TS](#463). If SS prop names clash with HTML Attributes, there will always be a problem.

How could it look?
```
<Box ss-mt={1} ss-bg="red"}  ss-color={['black',  'grey']}  />
<Box *mt={1} *bg="red"}  *color={['black',  'grey']}  />
<Box mt={1} *bg="red"}  *color={['black',  'grey']}  />
```

### Is there a way to merge SS's typings with Styled Components?
Maybe? I'm hoping someone knows the answer to this 😂 

Cheers
👊

**Comment by jxnblk** [comment]
If anyone has any suggestions here, this could make a great addition to the *guides* section in the docs, and I'd accept a PR.

WRT to this question:
> Should system props be namespaced?

I think if it is namespaced, it should be the `css` prop – a la [`@styled-system/css`](https://styled-system.com/css/)

**Comment by willtrking** [comment]
Spent some effort attempting to mitigate this issue in our codebase, seems like it comes down to the way the types specified by styled-components work, possible to solve this problem by overriding how the `styled.*` functions work to specifically omit certain HTML properties that are also used by styled-system. It really isn't components defined by SC that are preventing this, but those provided by React (`React.HTMLAttributes` specifically)

I'll spend some time digging more and see if I can come up with a solution. We're moving our codebase to TS right now and would love to use styled-system without `ts-ignore` everywhere.

**Comment by peduarte** [comment]
@willtrking hey dude, yeah you're right. I've spent so much time on this already. 

If you have a decent solution please share.

I've tried:
- creating custom `textColor` prop (works well)
- ignoring the error with `any` - sucks.

**Comment by jxnblk** [comment]
Closing this out since there's not a ton of ongoing discussion. If you'd like to PR some docs on using Styled System, that'd be super helpful, or if you have some ideas for additional packages, that would also be helpful, and feel free to open a new issue

**Comment by kylemh** [comment]
In styled-components v5, I'm able to leverage a strictly typed themes alongside styled-system when I do declaration merging as described here: https://github.com/styled-components/styled-components/issues/1589#issuecomment-578294784

`styled-components` documentation also highlights this, albeit with a worse implementation: https://styled-components.com/docs/api#create-a-declarations-file

**Comment by kamalbennani** [comment]
@kylemh The issue in your example is related to the fact that @types/react adds a basic typing for the color property which is set to: `color: string | undefined` and because `styled-system` has its own typing for the color (string | number | symbol | null)[]), the end result is a union of both types which in this case will generate this issue.

I'm trying to see how to ignore the react typing but without success for now. (because the color property is actually not forwarded to the dom)

**Comment by ashr81** [comment]
@kamalbennani Did you find any resolution for the issue?
