### ISSUE TITLE
Incorrect sort in IE Edge for responsive objects

### ISSUE THREAD

**Issue by jamesmosier** [styled-system/styled-system#465]
When using the responsive object for a style property, the order is incorrect in IE Edge.

For example, this: `<Flex flexWrap={{ mobile: 'wrap', md: 'initial' }}>` would output the `md` media query first in the CSS and the `mobile` media query second, therefore making it so the `mobile` media query rule **always** applies. 

I created a [jsbin](https://jsbin.com/cimavez/edit?js,console) to quickly reproduce the issue in IE Edge (I just rewrote some of the code to simplify things). The output from running this in Edge looks like: 

<img width="536" alt="Screen Shot 2019-04-23 at 11 13 49 AM" src="https://user-images.githubusercontent.com/2854919/56592571-f2003b00-65b8-11e9-894c-612bc91b67d2.png">

While running this in Chrome outputs:

![Screen Shot 2019-04-23 at 11 15 09 AM](https://user-images.githubusercontent.com/2854919/56592638-13f9bd80-65b9-11e9-994c-4d3018356935.png)

If i reverse the order of the properties in the object (`md` first then `mobile`) it works as expected. 

Commenting out the [`styles.sort()`](https://github.com/styled-system/styled-system/blob/master/src/index.js#L83) fixes it for both Chrome and Edge, but I wanted to get any thoughts before proceeding.

**Comment by stinodes** [comment]
Hmm. changing the order of the responsive styles seems to break it on other browsers (at least it seems to in my case).  
Have you figured anything else out to get this to work as expected somewhat painlessly?

**Comment by jamesmosier** [comment]
Unfortunately not @stinodes ... I ended up just writing regular styled-components for anything responsive.

**Comment by jxnblk** [comment]
I believe a fix for this has been published, and the changes in #513 should make this a non-issue. Feel free to reopen this or another issue if similar problems are still happening
