### ISSUE TITLE
Any way to achieve different scales for breakpoints?

### ISSUE THREAD

**Issue by cronin4392** [styled-system/styled-system#468]
Hello,

I am using `styled-components` in a project and loving it. I am running into a use case and cannot figure out the best way to model it in the system.

The case I am trying to implement is I have different font size scales per breakpoint. For example:

| name | mobile size | desktop size |
|---|---|---|
| h1  | 32px  | 50px  |
| h2  | 26px | 34px  |
| p  | 14px | 14px  |

How I tried implementing this was to do this in my theme and component:

`theme.js`
```
{
    fontSizes: [
        [14px, 26px, 32px], // mobile scale
        [14px, 34px, 50px], // desktop scale
    ]
}
```

*note: fontSizes is an array containing 2 arrays. First array pertains to first breakpoint, second array pertains to second breakpoint*

`component.jsx`
```.jsx
<h1 fontSize={2}>...</h1>
<h2 fontSize={1}>...</h2>
<p fontSize={0}>...</p>
```

---

My understanding is that the scale defined in the theme does not have breakpoint logic. Breakpoint logic is handle on your component itself. The only model I could think of was I flatten my mobile and desktop fontSize scales into 1 array and do the breakpoints on the theme and component, like so:

`theme.js`
```
{
    fontSizes: [
        14px, 26px, 32px, // mobile scale
        14px, 34px, 50px, // desktop scale
    ]
}
```

`component.jsx`
```.jsx
<h1 fontSize={[2, 5]}>...</h1>
<h2 fontSize={[1, 4]}>...</h2>
<p fontSize={[0, 3]}>...</p>
```

This solution would work, but obviously feels a bit hacky. My system has 3 fontSizes and 2 breakpoints therefore my fontSizes array is 6 items long.

I wonder if this goes against the values of `styled-system`? It says [here](https://styled-system.com/guides/array-scales#space-font-sizes-and-other-scales):

> Using a [...] limited set of spacing values are widely regarded as good practices in visual design. [...] Don't spend too much time debating what values to use in your fontSizes scale or trying to boil the ocean. Audit your current styles, normalize them.

Which I totally agree with, however, in my experience it can be useful to have different scales pertaining to different breakpoints. Any thoughts or solutions?

**Comment by flybayer** [comment]
Great question! I've wondered how to do this myself for some time now. Haven't tried to tackle it yet.

**Comment by jxnblk** [comment]
Although there are a ton of different ways to handle this sort of thing, the "Styled System approach" would take an idea like your table above:

| name | mobile size | desktop size |
|---|---|---|
| h1  | 32px  | 50px  |
| h2  | 26px | 34px  |
| p  | 14px | 14px  |

And create components that handle responsive styles (similar to what you have above), e.g. (assuming a low-level Text component):

```jsx
const Heading = props => <Text {...props} fontSize={[ 4, 5 ]} />
const SubHeading = props => <Text {...props} fontSize={[ 3, 4 ]} />
const Paragraph = props => <Text {...props} fontSize={2} />
```

That said, there are many other ways to handle this, including aliasing the `fontSizes` scale or creating nested objects, e.g.

```js
fontSizes: {
  small: [ 12, 14, 16, 24, 32 ],
  large: [ 14, 16, 18, 32, 48 ]
}
```

**Comment by cronin4392** [comment]
@jxnblk I think your nested example would be most appropriate however it's not so clear how to implement this in my components? My understanding is that I can create a scale using the plural version of the word(`fontSizes`). Then on my component I set a value on the singular version, `fontSize={1}` and that will pick that item from the scale. 

Can you provide an example of how that works when my scale is nested? Would it be like so?

```.jsx
fontSizes: {
  small: [ 12, 14, 16, 24, 32 ],
  large: [ 14, 16, 18, 32, 48 ]
}
```

```.jsx
const Heading = props => <Text {...props} fontSize={{small: [3, 4], large: [3, 4]}} />
const Text = props => <Text {...props} fontSize={{small: [0, 1], large: [0, 1]}} />
```

**Comment by jxnblk** [comment]
I think the component-based approach from above is the most straightforward and flexible, letting you turn off default responsive changes where needed, but to use the nested values in a theme scale, use dot notation, e.g. `<Text fontSize={[ 'small.2', 'large.2' ]} />`

Using plain objects for values references the `theme.breakpoints` object and is used a bit differently than in your example. For example the same Text component above can be written like `<Text fontSize={{ small: 'small.2', large: 'large.2' }} />` – it's a little less readable than the array syntax in this example IMO

**Comment by jxnblk** [comment]
Closing this as I *think* the original question was answered, but feel free to open another issue if not
