### ISSUE TITLE
First class support of styled-system by JSS 

### ISSUE THREAD

**Issue by kof** [styled-system/styled-system#471]
Hey, as discussed documenting issues I stumbled over while trying to integrate with JSS:

1. Styled-system functions return value data structure.

    Currently, v4 returns a nested array, which could be a flat object as it has been before in v3.  Seems like @jxnblk and I both want it flattened again 😂

2. Dependency on React prop-types isn't ideal, because it could be done in a universal way. Also it was a bit confusing to find `propTypes` property on those functions, because it made them look like a React component. I am looking to have a first-class support for styled-system and keen to integrate the validation automatically.

Related issue on JSS repo https://github.com/cssinjs/jss/issues/974

**Comment by jxnblk** [comment]
Just following up here, removal of the `prop-types` package from core is coming in #513

**Comment by kof** [comment]
@jxnblk thanks for the follow up!

**Comment by jxnblk** [comment]
I *think* this has been resolved, but feel free to follow up with a new issue
