### ISSUE TITLE
some style props are passed as dom elements attributes

### ISSUE THREAD

**Issue by jordiviva** [styled-system/styled-system#474]
Some props like margins or paddings are being passed, but others like width, font weight, color... are not being passed as dom attributes.

Example:

`const css = props => props.css;

const BoxStyled = styled.div`
  ${space}
  ${width}
  ${fontSize}
  ${color}
  ${position}
  ${borders}
  ${colorStyle}
  ${css}
`;

const Box = (props: IBox) => {
  return <BoxStyled {...props} />;
};`

`<Box width={4 / 5} color={Colors.primaryDark} fontSize={3} m={3} p={2}>
            Testing
          </Box>`

Renders:

`<div width="0.8" color="#6200ea" font-size="3" class="Box__BoxStyled-sw00a7-0 kDmNLE">Testing</div>`

**Comment by jxnblk** [comment]
Please see https://styled-system.com/guides/removing-props-from-html

**Comment by DaanDD** [comment]
This is a very annoying issue with Styled Components. Luckily I found an easy solution. Change this:

```
const BoxStyled = styled.div`
  ${fontSize}
  ${width}
`;
```

To this:

```
const BoxStyled = styled(({ fontSize, width, ...other }) => <div {...other} />)`
  ${fontSize}
  ${width}
`;
```

This solution still passes all props to the styled component, but doesn't pass props like `fontSize` and `width` to the DOM.

**Comment by jordiviva** [comment]
Yes, it works, but if I want to give like 30 props to the components, for basic things like margins, paddings, width, color, fontsize and borders.... the code seems not much clear at all.

Anyway, thanks for the answers, now I know how to solve this problem.
