### ISSUE TITLE
Responsive - by key instead of Array

### ISSUE THREAD

**Issue by russpitre** [styled-system/styled-system#476]
I've been experimenting with **styled-system** for a couple days now and it's really slick. There are a couple of things I needed to do in order to make it work with the way I like to setup my theme object - one of which pertains to responsive values. Today we have a something like:

```
<Box bg={["red","green","blue"]}>
  My background changes at different screen widths.
</Box>
```

That's pretty slick. I do like it, but for some reason it doesn't sit 100% well with me. I've been thinking of an alternative to satisfy my need for a more expressive approach. Here's what I came up with.  

The first change would be to change the `breakpoints` on the theme to:

```
const breakpoints = {
  xs: "544px", // (for phones - screens less than 768px wide)
  sm: "768px", // (for tablets - screens equal to or greater than 768px wide)
  md: "992px", // (for small laptops - screens equal to or greater than 992px wide)
  lg: "1200px", // (for laptops and desktops - screens equal to or greater than 1200px wide)
};
```
And then you would do something like this:

```
<Box bg={{xs: "red", sm: "green", md: "blue"}}>
  My background changes at different screen widths.
</Box>
```

I like that it's more clear what you're asking for with the use of the keys indicating the screen size (sm, md, lg, etc.). Also, I can now add breakpoints anywhere in that scale without breaking existing components.

**Comment by jxnblk** [comment]
This is already part of the API, feel free to use whichever approach you prefer

**Comment by russpitre** [comment]
Dang!  I'm not sure why I didn't that in the docs.

**Comment by jxnblk** [comment]
The docs could probably use some clarity around that part of the API for sure

**Comment by andyford** [comment]
did v5 kill this?
