### ISSUE TITLE
Extend `css` functionality for multiple styles and pseudo classes

### ISSUE THREAD

**Issue by mosesoak** [styled-system/styled-system#477]
Hi, I'm also writing to say thanks for `styled-system`, show one way it's being used, and ask how we could improve on it.

In our project we chose to leverage the `css` prop way of generating styles, but that led us to write an additional layer of code to support the functionality we need. I wanted to get your feedback on it.

## Themed Styles Support

We externalize our styles into function calls, like `css={heroStyle()}` and can return an array of styles that include special styled-system wrapper functions like this:

`Hero/styles.js`
```js
import * as s from '../style/util';

export const heroStyle = () => [
  s.space({ p: Space.XL }),
  s.fontSize(FontSize.M),
  s.color(Color.PrimaryBg),
  s.flexWrap({
    mobile: 'wrap',
    desktop: 'nowrap',
  }),
  {
     textAlign: 'center',
   },
];
```

We do this with an extension generator that we use to export a bunch of style functions:

`style/util.js`
```js
import * as styledSystem from "styled-system";
import { has, isArray, isObject, keys, mapValues, first, flatten } from 'lodash';

// These wrapped functions allow us to use a shorthand: color('ourColor')
// instead of color({ color: 'ourColor' }), and return these directly in a style.
// You can also use breakpoints with these functions.
export const color = styledSystemWrapper('color');
export const display = styledSystemWrapper('display');
export const fontSize = styledSystemWrapper('fontSize');
// ...etc.. many more trimmed for brevity

const Breakpoints = {
  mobile: 'mobile',
  desktop: 'desktop',
}

// Our attempt at wrapping themed styles that support breakpoints
const styledSystemWrapper = styleName => arg => ({ theme }) => {
  const argIsArray = isArray(arg);
  const argIsMediaQueryObj =
    !argIsArray &&
    isObject(arg) &&
    keys(Breakpoints).find(key => has(arg, key));
  const obj =
    argIsArray || argIsMediaQueryObj || !isObject(arg)
      ? { [styleName]: arg }
      : arg;
  return styledSystem[styleName]({ theme, ...obj });
};
```

## Themed Pseudo Styles Support

We also need support for pseudo styles, which was pretty hard to recreate - not sure this is done totally correctly but it seems to work.

This 2nd extension allows us to make a style using `hover`, like this:

`Button/styles.js`
```js
export const buttonWrapper = (hoverColor) => [
  s.hover({
    color: Color.ContentBg,
    backgroundColor: hoverColor,
    cursor: 'pointer',
  }),
  s.color(Color.OffContentFg),
  {
    cursor: 'pointer',
  },
];
```

`style/util.js`
```js
export const hover = pseudoStyleWrapper('hover');

// styled-system removed their internal support for pseudo styles, this tries to recreate it
export const pseudoStyleWrapper = styleName => arg => ({ theme }) => {
  const mapped = mapValues(arg, (value, key) => {
    const func = styledSystem[key];
    if (!!func) {
      return (
        get(first(flatten(func({ theme, [key]: { [key]: value } }))), key) ||
        value
      );
    }
    return value;
  });
  return { [`&:${styleName}`]: mapped };
};
```

## Special Themed Props Extensions

We've also been able to leverage the `style` function to extend for special props like SVG fill:

```js
const svgFillStyle = styledSystem.style({
  prop: "fill",
  cssProperty: "fill",
  key: "colors"
});
export const fill = fillColor => ({ theme }) =>
  svgFillStyle({ theme, fill: fillColor });
```

## Conclusion

I know this is a lot but wanted you to see how one team is using `styled-system` in a production project, and some of the difficulties we've run across in trying to leverage use of the `css` prop.

The above works, but it's hard to reason about, was hard to put together, and feels kludgy. (Note the hacky dynamic function lookups from styled-system exports.)

Please let me know if there are simpler, more built-in ways to do these things in the current version? If not, how could extensions similar to `style` make these things easier in the future?

Thanks again for your hard work on `styled-system`, and look forward to your thoughts.

**Comment by jxnblk** [comment]
Hi, I can take a closer look at your examples later, but if you're using the `css` prop, you might be interested in the separate `@styled-system/css` package, which is its own implementation intended for the `css` prop. Looks like you might be doing a little more here, but figured I'd point that out FWIW https://styled-system.com/css/

**Comment by cereallarceny** [comment]
@jxnblk I've been trying to figure out the right way to write components in styled-system.  It's not horribly clear to me from the website.

Should I use `themeGet` inside of `styled`?
Should I use props for everything?
Should I set properties in `styled` and then use `defaultProps` for everything else?
Should I use `css()` as a prop on the component?
Should I use `css()` as a HOC in `styled`?

Of course, I'm the answer here is "yes" to all of the above.  However, I'd love to know if there's a suggested way... or perhaps the way **you** write a component library in styled-system.  I read through the Rebass code many, many times, but ultimately realized that those components are more of building block components and less "real-world" components.  They're great, but they aren't horribly complex.  How do you suggest component library authors write more complex components.

I love everything this library does, but I don't feel like I'm following the rules in the way I'm using it.  😉

**Comment by jxnblk** [comment]
@cereallarceny sorry for the delay! I probably don't have a definitive answer for you since this library is really intended to be somewhat low-level and be used in many different ways. It might be helpful to see how some other people are using the library, here are a few examples https://styled-system.com/showcase/

**Comment by cereallarceny** [comment]
No worries!  I quite like what you're doing in the HOC variation of the CSS
package.  I was hoping for a little dogmatism here, but I'll wait until v5
to decide on my preferred syntax.  Let me know if there's any remaining
tickets I could take.  Been watching your progress, looks like you're
handling it.

**Comment by jxnblk** [comment]
Thanks for sharing how you're using Styled System! I don't see any clear actionable next steps here, so I'm going to close this issue out. If you have further thoughts on how to make Styled System better or any ideas for additional packages, please feel free to open a new issue
