### ISSUE TITLE
Ability to use custom breakpoints in a property array

### ISSUE THREAD

**Issue by Polypants** [styled-system/styled-system#481]
Maybe you want an element to break at an odd point, one that's not already in your theme. But you don't want to add it to the theme because this property is the one and only property that will be using this breakpoint. Sure, you could have it break at the closest existing breakpoint, but hey maybe it just doesn't look quite right breaking there. What if you could describe a new breakpoint and a value for it right inside the property declaration?

Something like...

```jsx
<Flex justifyContent={["center", null, null, "flex-start", [640, "flex-end"]]}>
  <p>...</p>
</Flex>
```

with an inner array entered as a parameter into the parent array, it's two items are a breakpoint value (defaulting to px here but maybe that's too cryptic, I'll let you decide). 
Even more custom breakpoints? More arrays can be added. 

```jsx
<Flex justifyContent={["center", ["40em", "flex-end"], "flex-start", [700, "centrer"]]}>
  <p>...</p>
</Flex>
```

If an array comes before the number of breakpoints assigned to array positions is reached, it won't break it or replace it. You can think of it like the array values are removed from the parent array when compiled (even if that's not the actual implementation). This way you can keep your breakpoints in order, as long as you remember what you set them to in the theme.

Want to completely overhaul the breakpoints for this one thing for some reason maybe? If all your parent array items are arrays, the original breakpoints would be ignored. 

```jsx
<Flex justifyContent={[[400, "flex-end"], [600, "centrer"], [800, "centrer"]]}>
  <p>...</p>
</Flex>
```

This next part is where I might loose you. But maybe you don't like having to write `null` for a filler when you don't want to use a breakpoint. It is a liiiiiiittle weird isn't it?

What if we did something like...

```jsx
// before
<Flex justifyContent={["center", null, null, "flex-end"]]}>
  <p>...</p>
</Flex>

// after
<Flex justifyContent={[[0, "center"], [3, "flex-end"]]}>
  <p>...</p>
</Flex>
```

Is it way way _way_ neater? Sort of. So essentially if the number provided is <= the number of breakpoints provided, the number would coincide with that breakpoint and not a pixel value. Also pretty cryptic, I'll let you decide. This would also introduce some interesting logic problems. Like if I use this syntax, that breakpoint's position would become assigned to the next one which would introduce complexity.

```jsx
<Flex justifyContent={[[3, "flex-end"], [0, "center"], "flex-start", "center"]}>
  <p>Wait whats going on again?</p>
</Flex>
```

But hey maybe just don't try crazy crazy stuff like that and if you do that's your problem because I find writing stuff like `null, null, null` a little weird.

**Comment by jxnblk** [comment]
Interesting idea. I generally recommend using the `css` prop for one off styles – it helps avoid introducing a new syntax and should be easier to understand what's happening later when revisiting the code. That said, you could certainly build your own utility that does something like what you're describing above

**Comment by jxnblk** [comment]
I'm going to close this for now since there hasn't been much activity. Feel free to reopen if you'd like to discuss adding something like this as an optional package, or feel free to build out something of your own
