### ISSUE TITLE
Breakpoints as a parameter as an alternative to theme providers

### ISSUE THREAD

**Issue by Polypants** [styled-system/styled-system#482]
Let's say you have this element that the breakpoints you have going everywhere else just aren't working for. You'd love to overhaul the breakpoints for just this one thing. But a nested `ThemeProvider` seems a bit too much for you. What if you could pass in some new breakpoints somehow, just for this element?

Maybe like this...

```jsx
<Flex
  breakpoints={[400, 550, 700, 1000]}
  justifyContent={["...", "...", "...", "..."]}
>
  <p>...</p>
</Flex>
```

These breakpoints would override theme breakpoints, sort of like in-line styles overriding style sheets. And maybe they cascade to inner elements? Not sure how much of a nightmare that would be. This might be just an option for projects to choose instead of `ThemeProvider` all-together (to avoid specificity issues).

**Comment by Polypants** [comment]
NVM, you can pass in a theme directly into the components. Cool.

**Comment by penx** [comment]
See https://github.com/styled-system/styled-system/issues/389#issuecomment-1059392843
