### ISSUE TITLE
Serializing arrays with aliases

### ISSUE THREAD

**Issue by oliverjam** [styled-system/styled-system#485]
This is vaguely related to #305 

[The docs](https://styled-system.com/guides/array-scales#aliases) appear to recommend adding named aliases to array scales to allow e.g. `mt="space.medium"` instead of `mt="space.2"`.

We've just hit an annoying-to-debug issue with server-rendering: JSON doesn't treat arrays as normal objects and strips out all the non-integer keys.

```js
let space = [0, 8, 16, 24];

space.small = space[1];
space.medium = space[2];
space.large = space[3];

console.log(space); // [ 0, 8, 16, 24, small: 8, medium: 16, large: 24 ]
console.log(JSON.stringify(space)); // [0,8,16,24]
```

We have to serialize our theme object and stick it on `window` to rehydrate on the client. This means a load of our spacing disappears on client-side render (leaving us with lots of className mismatch errors from React).

Is it worth at least a warning in the docs about server-rendering when using array aliases? Maybe we could recommend using an object with integer keys instead?

(I assume this would work as an alternative)
```js
let space = { 0: 0, 1: 8, 2: 16, 3: 24, small: 8, medium: 16, large: 24 }
```

**Comment by jxnblk** [comment]
It sounds like you've mostly figured this out, but if you *do* need to serialize the theme object, then I think your suggestion at the end should work. I don't imagine many people would need to stick a server theme object on the window with modern setups, but this could be added as an alternative approach in the docs

**Comment by oliverjam** [comment]
Yeah I guess our use-case is a bit unusual—supporting dynamic themes on the server. There's probably a solution that avoids serializing too; maybe just passing down a theme name and dynamically importing the right JS file in the client.

Is there any downside to using an object instead of an array, other than it looking kinda weird? It seems to work exactly the same from Styled System's perspective.

I'm happy to close this as it's kind of an edge case, but also happy to PR a tweak to the docs just to mention the serialization pitfall.

**Comment by jxnblk** [comment]
I can’t think of any downside off the top of my head and yeah feel free to open a docs PR if you have the time

**Comment by jxnblk** [comment]
Going to close this for now, but feel free to open a PR for an update to the docs if you see fit
