### ISSUE TITLE
Invariant Violation: Invalid prop `fontSize` of type `string` supplied to `StyleSheet generated`, expected `number`.

### ISSUE THREAD

**Issue by anshupitlia** [styled-system/styled-system#492]
Hi,

I'm getting the following error: 

```
Invariant Violation: Invalid prop `fontSize` of type `string` supplied to `StyleSheet generated`, expected `number`.

StyleSheet generated: {
  "fontSize": "1.5em",
  "lineHeight": 24,
}
This error is located at:
    in StyledNativeComponent (created by Styled(Text))
    in Styled(Text) (at myfile.js:23)
```

This is what I have at line 23:

```
<Text
          fontSize='1.5em'
          lineHeight={24}
          height={32}
    >
```

is putting `em` not supported? But I see the README having description of it being available.

**Comment by jxnblk** [comment]
Not sure what’s happening, but if you’re using React Native, I believe you have to use numbers without units

**Comment by anshupitlia** [comment]
Yes I'm using React Native.

**Comment by jxnblk** [comment]
https://facebook.github.io/react-native/docs/height-and-width

> All dimensions in React Native are unitless, and represent density-independent pixels.

**Comment by anshupitlia** [comment]
Thanks, this helps!
