### ISSUE TITLE
lineHeight doesn't work as documented on React Native

### ISSUE THREAD

**Issue by chrisbull** [styled-system/styled-system#496]
So lineHeight on react native  doesn't work the same as html. Using `em` styling isn't computed like it is with html. So using lineHeight: 1.25 literally makes the line height 1.25px instead of 1.25 times the fontSize.  

The issue with this is that since fontSize is a dynamic and calculated responsive size, setting the lineHeight to an actual px wouldn't work.  Normally with styled-components you have to set lineHeight as the actual px size, eg `{ fontSize: 15, lineHeight: 18 }`.  

A purposed fix (but needs to be done inside of the `styled-system` library) could be that  lineHeight is a calculated value from the final fontSize. 

```
const theme = { 
  fontSizes: [ 12,13,14,15,18,20 ],
  lineHeights: {
    body: 1.75,
    height: 1.25
   }
}

const P = styled.Text({
  fontSize,
  lineHeight,
})

P.defaultProps = {
  fontSize: [3,4],
  lineHeight: 'body'
}
```

should out a product of [1.75 * props.fontSize[3], 1.75 *  props.fontSize[4]] = [26.25, 31.5] thus
```
{
 font-size: 15,
line-height: 26.25
}
{
  font-size: 18,
  line-height: 31.5
}
```

**Comment by chrisbull** [comment]
A fix I've generated is to create a custom lineHeight styleFn. The problem though is is that lineHeights aren't responsive, or returning a responsive value back doesn't work. Here the styleFn for reference

```
 (props: { theme: DefaultTheme; lineHeight: LineHeight; fontSize: FontSize }) => {
    const { theme } = props
    const _lineHeight = theme.lineHeights[props.lineHeight]
    const _fontSize = Array.isArray(props.fontSize) ? props.fontSize[0] : props.fontSize

    const fontSize = theme.fontSizes[_fontSize]
    const lineHeight = _lineHeight * fontSize

    return {
      fontSize,
      lineHeight,
    }
  },
```

**Comment by chrisbull** [comment]
Also to note, responsive doesn't work on react-native at all.  A warning appears for `fontSize: [6,7]` stating that `atrule` is not allowed inline styles.

**Comment by jxnblk** [comment]
Sorry, if I'm misunderstanding this issue, but if you're using RN, why wouldn't you use pixel values for line height?

**Comment by chrisbull** [comment]
I think this may be a null issue now with v5. But i'll report back if necessary. Thanks
