### ISSUE TITLE
Put several Styled System props under media-query

### ISSUE THREAD

**Issue by lishine** [styled-system/styled-system#497]
This is the case when I want to put several SS props under media-query, unlike doing px={[0,1]}.
I wrote something. It looks like css object with media queries but instead of css - SS props.

Did somebody do something like this ?
Is there some better idea or something more general ?

* The mediaDown and mediaUp is just media query, taking media values from the global theme object
* The mediaBoxCss passes props given through all the SS properties returning array of objects, object for each property, but it put this object inside object with the media query
```
const styles = [
    ...mediaBoxCss(mediaUp('md'), {
        justifyContent: 'space-between',
        alignItems: 'center',
        px: 2,
        flex: '1',
        maxWidth: '570px',
        mx: 'auto',
    }),
    {
        [mediaDown('md')()]: {
            justifyContent: 'space-evenly',
            alignItems: 'center',
            position: 'fixed',
            left: 0,
            bottom: 0,
            right: 0,
            zIndex: '100',
            height: '56px',
        },
    },
]

export const Menu = () => (
    <Flex css={styles}>
        <MenuLink route="home">ABOUT</MenuLink>
        <MenuLink route="home">SALSA COURSE</MenuLink>
        <MenuLink route="home" display={['none', 'block']}>
            BLOG
        </MenuLink>
        <MenuLink route="home" display={['none', 'block']}>
            FAQ
        </MenuLink>
        <MenuLink route="home">CONTACT US</MenuLink>
        <MenuLink route="home" display={['block', 'none']}>
            LOG IN
        </MenuLink>
    </Flex>
)

export const mediaBoxCss = (media, props) =>
    [...boxParams].map(func => ({
        [media({ theme })]: func({ theme, ...props }),
    }))

export const mediaDown = to => (props = {}) => {
    const _theme = props.theme || theme
    return `@media screen and (max-width: ${_theme.breakpointsObject[to]})`
}
```

**Comment by jxnblk** [comment]
The `css` package might be of interest for what you're trying to do: https://styled-system.com/css/

**Comment by lishine** [comment]
Indeed, this is what I need !
VERY COOL!!!
I love what you are doing!!!

css can receive object or function(theme)
It just works!
Great!

What do you think, maybe better to pass whole props to the function:
css(props => ({ ...

```
const styles = css(theme => ({
    [mediaUp('md')({ theme })]: {
        justifyContent: 'space-between',
        alignItems: 'center',
        px: 2,
        flex: '1',
        maxWidth: '570px',
        mx: 'auto',
    },
    [mediaDown('md')({ theme })]: {
        justifyContent: 'space-evenly',
        alignItems: 'center',
        position: 'fixed',
        left: 0,
        bottom: 0,
        right: 0,
        zIndex: '100',
        height: '56px',
    },
}))
```

**Comment by jxnblk** [comment]
Awesome! And, it *should* check for `props.theme` already, see https://github.com/styled-system/extras/blob/master/packages/css/index.js#L103 – but let me know if you're seeing any bugs

**Comment by lishine** [comment]
Oh I see!

**Comment by lishine** [comment]
Here is a shortcoming of emotion/babel component css prop - 
```
<Component css=[stylesArray] > 
```
it does not pass props to an array
as oppose to props of
```
styled(component)(stylesArray)
```

See what I mean:

Suppose I have  styles like this, it is even array in an array! :
```
import css from '@styled-system/css'

export const mainLinkStyles = [
    textMenu,
    css({
        p: 1,
        color: 'light-normal',
        borderBottom: '2px solid transparent',
        ':hover': {
            textDecoration: 'none',
            borderBottom: '2px solid currentColor',
            color: 'primary',
        },
    }),
]

const styles = [
    mainLinkStyles,
    css({
        pb: '4px',
        [mediaDown('md')()]: {
            pl: '3px',
            pr: '3px',
            pb: '1px',
            color: 'dark-normal',
        },
    }),
]
```

This will work:
```
import styled from '@emotion/styled'

const Link = styled(BaseLink)(styles)
```

This will not work:
```
<Link  css={styles} >
```

So that if I want to compose styles, I am forced to 'styled' notation.

Am I missing something?
Can something be done about it?
Like if styled-system/css would accept nested arrays, then I would wrap css={css(stylesArray)}

I know that I can do something like this css={(props) => stylesArray(props)}, flatten arrays and pass props, but I want it simple likes with styled(component)(stylesArray)

**Comment by jxnblk** [comment]
IIRC you *can* pass an array of style objects to Emotion's `css` prop, so I'm not sure what's happening in your example

**Comment by lishine** [comment]
Yes, you can pass an array of style objects which do not depend on the props.
In example above styled system css function return a function, it needsto be given props. When it is inside array, it will not be provided props.
But with this form, it will be provided props: styled(component)(stylesArray)

**Comment by lishine** [comment]
> This is the case when I want to put several SS props under media-query, unlike doing px={[0,1]}.
> I wrote something. It looks like css object with media queries but instead of css - SS props.
> 
> Did somebody do something like this ?
> Is there some better idea or something more general ?
> 
> * The mediaDown and mediaUp is just media query, taking media values from the global theme object
> * The mediaBoxCss passes props given through all the SS properties returning array of objects, object for each property, but it put this object inside object with the media query
> 
> ```
> const styles = [
>     ...mediaBoxCss(mediaUp('md'), {
>         justifyContent: 'space-between',
>         alignItems: 'center',
>         px: 2,
>         flex: '1',
>         maxWidth: '570px',
>         mx: 'auto',
>     }),
>     {
>         [mediaDown('md')()]: {
>             justifyContent: 'space-evenly',
>             alignItems: 'center',
>             position: 'fixed',
>             left: 0,
>             bottom: 0,
>             right: 0,
>             zIndex: '100',
>             height: '56px',
>         },
>     },
> ]
> 
> export const Menu = () => (
>     <Flex css={styles}>
>         <MenuLink route="home">ABOUT</MenuLink>
>         <MenuLink route="home">SALSA COURSE</MenuLink>
>         <MenuLink route="home" display={['none', 'block']}>
>             BLOG
>         </MenuLink>
>         <MenuLink route="home" display={['none', 'block']}>
>             FAQ
>         </MenuLink>
>         <MenuLink route="home">CONTACT US</MenuLink>
>         <MenuLink route="home" display={['block', 'none']}>
>             LOG IN
>         </MenuLink>
>     </Flex>
> )
> 
> export const mediaBoxCss = (media, props) =>
>     [...boxParams].map(func => ({
>         [media({ theme })]: func({ theme, ...props }),
>     }))
> 
> export const mediaDown = to => (props = {}) => {
>     const _theme = props.theme || theme
>     return `@media screen and (max-width: ${_theme.breakpointsObject[to]})`
> }
> ```

Back to the first question.
Using now styled-system/css
But it does not accept my custom properties, like:
```
const light = style({
    prop: 'light',
    cssProperty: 'color',
    transformValue: n => 'var(--light-normal)',
})

const text = ({ text }) =>
    text &&
    {
        menu: css`
            font-family: 'Oswald', sans-serif;
            font-size: 14px;
            line-height: 24px;
            transform: translateY(6px);
            font-weight: 400;
        `,
    }[text]
```

I see that in order it to accepts them, the code should rewritten.

**Comment by jxnblk** [comment]
I might be misunderstanding parts of this, but if you're looking to use `props` with the `css` prop, you can access that inside the component's scope where the `css` prop is applied in JSX

```jsx
const Component = props => {
  return (
    <div
      {...props}
      css={theme => ({
        // use props or theme here
      })}
  )
}
```

I.e. you might want to wrap some of the styled-system library (or roll your own utilities) to do exactly what you're trying to do

**Comment by lishine** [comment]
Yes, you are right, I thought css={props=> provide props of the component it is placed on, but no, this props is =theme

**Comment by lishine** [comment]
BTW about the last thing that I wrote - support for my custom SS properties in SS/css. I wrote function that wraps SS/css, it traverses the object before passing it to SS/css. It transforms each custom property that it finds

**Comment by jxnblk** [comment]
It looks like you've probably figured out the original issue, so closing this one out. Feel free to open a new issue, if anything else comes up
