### ISSUE TITLE
Aliases for mx, my, px, py

### ISSUE THREAD

**Issue by r-inaldi** [styled-system/styled-system#498]
Could `paddingHorizontal` (`px`), `marginVertical` (`my`) be useful for someone? It seems to me that these aliases are missing.

**Comment by jxnblk** [comment]
If you're suggesting renaming the built-in props, you can create a custom style function to name them whatever you want

**Comment by r-inaldi** [comment]
Not renaming, but aliasing similar to `m` -> `margin` or `mb` -> `marginBottom`. 
Anyway, creating a custom style is a good alternative, thanks, feel free to close it :)
