### ISSUE TITLE
Check if Prop Is Set

### ISSUE THREAD

**Issue by moshemo** [styled-system/styled-system#500]
The following code is not working for me:

`background-color: ${props => (props.bg? 'red' : 'blue')}`

Whether or not I have set the bg prop, the background-color is always red.

Any idea how I can conditionally check if a prop is set?

**Comment by jxnblk** [comment]
Sorry, I can't really tell where this code is in context, and it doesn't look like you're using styled-system at all here. Is this an issue with either `styled-components` or `emotion`?
