### ISSUE TITLE
Size prop returning incorrect width value

### ISSUE THREAD

**Issue by chrisbull** [styled-system/styled-system#501]
So there is an issue with the size and width props.

When using:

```
const theme = {
  size: [16,32, 48, 64]
}
```

and then using 
```
import  { size } from 'styled-system'
const Box = styled.View(size)
```

and then rendering using
```
<Box size={2} />
```

is returning an incorrect style of:
```
{
  height: 32,
  width: 2
}
```

I've narrowed it down, and it's due to the `getWidth` and `getPx` methods.

For width, using getWidth doesn't return the responsive array value, like height does in the getPx. 

I've copied the code from version 4.2.2 and you can see the issue:
```
var getPx = function getPx(n, scale) {
  return px(get(scale, n));
};

var getWidth = function getWidth(n, scale) {
  return !num(n) || n > 1 ? px(n) : n * 100 + '%';
};

var width = style({
  prop: 'width',
  key: 'widths',
  transformValue: getPx
}); 

var height = style({
  prop: 'height',
  key: 'heights',
  transformValue: getPx
});
```

Unless i'm doing things wrong. I'm under the impression that size is supposed to be an easy way to set height and width, as an equal value, instead of manually setting height and width all the time. Is that correct? If can you please fix the getWidth method? Thanks

**Comment by jxnblk** [comment]
This is how the API currently works (even if not the most obvious in this example), so while this is likely to change in the next major version, it *would* be a breaking change and can't be added in v4. I'll try to walk through what's happening as far as I can tell:

- `size={2}` is setting a non-responsive style for size of `2`
- the `width` function does not use values from the theme, so `2` is interpreted as `'2px'`
- the `size` function looks like it's pick up the value from `theme.size[2]` (though tbh I'm unsure why)

You might have better luck creating your own custom style function for width that hooks into the theme in this case and mapping the `size` prop to `width` and `height`

**Comment by jxnblk** [comment]
Since the API is changing in v5 (see #513), the `size` prop will pick up values from `theme.sizes` in the next version. Going to close this out for now since this is how the v4 API currently works
