### ISSUE TITLE
Is it possible to use styled-system with zero-runtime CSS in JS libraries?

### ISSUE THREAD

**Issue by VladSez** [styled-system/styled-system#510]
Hello everyone! I want to use styled-system with zero-runtime CSS in JS libraries like Linaria, Astroturf, Reshadow? So far, no luck. Is it possible?

https://github.com/callstack/linaria
https://github.com/lttb/reshadow
https://github.com/4Catalyzer/astroturf

**Comment by lishine** [comment]
I  am too interested

**Comment by jxnblk** [comment]
I briefly looked into this, but I don't use any of the libraries mentioned above. If anyone wants to open a PR with an example added for one of these, that'd be great

**Comment by VladSez** [comment]
I have found this:
https://codesandbox.io/s/styledsystemreshadowstyled-3yeho
https://github.com/lttb/reshadow/issues/20

**Comment by jxnblk** [comment]
That looks like a good example. Feel free to open a PR adding something like this to the `examples/` directory

**Comment by jxnblk** [comment]
Closing in favor of #640 and #641

**Comment by uptonking** [comment]
- the example above doesn't make using styled-system with zero-runtime lib possible.  
- because @reshadow/styled lib uses runtime styles, which is used in the example.
- but reshadow lib is different, it just failed to run the example.
