### ISSUE TITLE
shouldForwardProp forwards custom (aliased) props

### ISSUE THREAD

**Issue by woro83c** [styled-system/styled-system#517]
Heya,

Supplying the `shouldForwardProp` doesn't seem to prevent custom props from being displayed in the HTML when an alias is used, e.g.

```jsx
const display = style({ prop: 'display', alias: 'd' });
const Box = styled('div', { shouldForwardProp })();

Box.defaultProps = { d: 'block' };

// <div d="block" />
render(<Box />);
```

Thanks!

**Comment by jxnblk** [comment]
The `should-forward-prop` helper only filters out built-in prop names and anything props Emotion excluded by default. If you’re creating custom props, you might want to wrap this helper with your own that includes custom props like `d`, which is a valid attribute for SVG path elements

**Comment by woro83c** [comment]
Ah I see! Cheers 👍

**Comment by jxnblk** [comment]
Heads up, in v5 the `@styled-system/should-forward-prop` utility will include a `createShouldForwardProp` function to make adding custom props easier. Closing this issue for now

**Comment by kevinSuttle** [comment]
Could this be why I'm _not_ seeing certain custom props make it to the output CSS? e.g. `whiteSpace`, `cursor`?

**Comment by jxnblk** [comment]
@kevinSuttle As far as I understand how Emotion uses this, it should still pass props to functions in your style argument, only remove them from the rendered HTML

**Comment by kevinSuttle** [comment]
Gotcha. I’ll open up a new issue later. Thanks!
