### ISSUE TITLE
Setting a default theme (without the need for a provider)

### ISSUE THREAD

**Issue by sebald** [styled-system/styled-system#519]
Hey,

we are am using `emotion` and `styled-sytem/css` together and are wondering if there is proposed way to set a "custom default theme". Meaning, using a custom theme, without the need to use a `<ThemeProvider>`.

Currently we have two hooks to achieve this, but it doesn't feel right, because we're programmatically injecting the theme:

```js
// useTheme.js
export const useTheme = () => {
  const theme = useContext(ThemeContext);
  return {
    ...defaultTheme,
    ...theme,
  };
};

```

```js
// useBox.js
import css from '@styled-system/css';
import { useTheme } from './useTheme';

export const useBox = props => {
  const theme = useTheme();
  return css(props)(theme);
};
```

### [Full Codesandbox Example](https://codesandbox.io/embed/defaulttheme-6dyb2)

This allows us to not require a provider:

```js
// Default theme, not default theme set by styled-system
<Box margin={2} width={[100, 500]} color="primary">
  I am orange.
</Box>

// Custom theme, will be merge with default theme
<ThemeProvider theme={customTheme}>
  <Box color="primary">I am pink!</Box>
</ThemeProvider>
```

---

Executing `css(props)(theme)` feels counter intuitive to emotion's and styled-system's API. Is there already a way to set our own default theme?

If not, what about exposing a factory function for `css`. E.g.

```js
import { createCSS } from '@styled-system/css';
export default createCSS(defaultTheme);
```

This additional API should be possible to implement, without any breaking changes, because the default `css` export still could be the default styled-system theme.

If this is an option, I am happy to submit a PR 🙂

**Comment by jxnblk** [comment]
With the `styled` components approach, you can achieve this by setting `theme` as a default prop on the component. I’m not sure if there’s a standard way to do something like this with the `css` prop, but I also don’t think calling `css(styles)(theme)` is bad – if what you have works for your use-case it looks fine to me

**Comment by jxnblk** [comment]
Oh, and an earlier version did have a `createCSS` method, which I’m not opposed to, but would require a little more thought before rolling out IMO because there are several things that could be configured

**Comment by sebald** [comment]
That's interesting that there already was a `createCSS`. Do you mind sharing why it was removed?

Regarding the configuration of `styled-system`. True, there might be other things that are worth configuring. But I for example, like that `styled-system` is opinionated about the core design tokens (spaces, fonts, etc).

What do you have also make configurable?

**Comment by jxnblk** [comment]
There’s aliases, theme keys, transforms, could be other things as well, see https://github.com/styled-system/styled-system/blob/master/packages/css/src/index.js

**Comment by sebald** [comment]
Yes, but I think it is a good thing that this is NOT customizable 🙂 Otherwise you can just could just create your own spec with `system` from '@styled-system/core'.

---

This is a little off topic, but what are the reasons for not using any other `@styled-system` packages in the `@styled-system/css` package?

**Comment by jxnblk** [comment]
> Yes, but I think it is a good thing that this is NOT customizable

I tend to agree with you, but flexibility in an API like this can be good IMO

> what are the reasons for not using any other @styled-system packages in the @styled-system/css package?

The implementation is a bit different and the `css` package doesn't need to filter out properties that aren't styles, so this was an opportunity to start with a fresh code based and work on optimizing the performance without the baggage of the rest of the API

**Comment by sebald** [comment]
This is a little bit off topic, but I didn't want to bother you with a new issue (if you prefer I can put this in a new issue though):

Since start working with `@styled-system/css` (and trying to make typings for it), I stumbled upon some things that I would like to improve. I absolute love what you created with `styled-system` and before I fork the project and make "yet another styled system that is actually not better but just different", I wanted you to ask, what you think about the following features for the `css` package:

**1. Custom transforms.**

You already talked about customization things, not just the theme. I thinks adding the option for custom transformers is a relevant feature, even though basic transforms are already supported.

For example something like this already works:

```js
css({
  transform: 'fast',
})({
  transform: {
    slow: 'all 5s linear',
    fast: 'all 1s linear',
  },
})
// => { transform: 'all 1s linear' }
```

**2. Dedicated `variants` key for the theme.**

Instead of allowing variant objects to be put anywhere in the theme, having a dedicated key (e.g. `variants`) would make it easier to understand the feature (and also would make creating types easier).

*Optional: Since it already was talked about Typescript in #463. What about moving the `css` package to TypeScript as an experiment. With the current babel/jest setup this should be relatively easy and little extra work.*

**Comment by jxnblk** [comment]
Going to close this issue out since it's gotten a little off topic, but feel free to open new/more specific issues.

> 1. Custom transforms

Based on your code example, did you mean `transition`? The transforms in the `css` package won't likely be customizable for some of the same reasons you mentioned above.

> 2. Dedicated variants key for the theme

This is an interesting idea, and might be worth proposing in the [Theme Spec](https://github.com/system-ui/theme-specification)
