### ISSUE TITLE
Transitions in theme specification

### ISSUE THREAD

**Issue by neoziro** [styled-system/styled-system#524]
I added transitions to xstyled, I think it would be nice to have it in theme specifications.

https://system-ui.com/theme/

```js
transitions: {
  color: 'color 300ms ease' 
}
```

What do you think?

**Comment by jxnblk** [comment]
Sounds like a good idea to me! Feel free to open a PR here: https://github.com/system-ui/theme-specification/

**Comment by neoziro** [comment]
@jxnblk PR submitted
