### ISSUE TITLE
First option in sizes array not returning properly

### ISSUE THREAD

**Issue by ebello** [styled-system/styled-system#529]
After upgrading to v5 and converting the `maxWidths` array in my theme.js to `sizes`, I have: 

`sizes: ['80em', '52em', '40em', '30em']`

The expected result from `<Box maxWidth={0}>` would be `max-width: 80em`, however `max-width: 0` is returned.

Conversely, `<Box maxWidth={1}>` returns `max-width: 52em` as expected.

**Comment by kevinSuttle** [comment]
I'm seeing the same thing other properties. I think this is a bug in core. 

<img width="600" alt="Image 2019-06-03 at 3 40 37 PM" src="https://user-images.githubusercontent.com/95672/58829492-f25b0f80-8615-11e9-88a7-79278ac831f3.png">
