### ISSUE TITLE
v5 backwards compatibility: boxShadow 

### ISSUE THREAD

**Issue by leantide** [styled-system/styled-system#532]
v5 backwards compatibility issue with v4.

`import { boxShadow } from 'styled-system';`

Under v4, this worked. Now under v5, this results in:
Attempted import error: 'boxShadow' is not exported from 'styled-system'.

**Comment by mfix22** [comment]
You can use `import { shadow } from 'styled-system'` or `import shadow from '@styled-system/shadow'` now 👍

**Comment by leantide** [comment]
Thanks.

**Comment by jxnblk** [comment]
The new API is `shadow`, but I think I missed aliasing the v4 `boxShadow` export, if anyone wants to PR that
