### ISSUE TITLE
Opacity

### ISSUE THREAD

**Issue by leantide** [styled-system/styled-system#533]
From Rebass v3: `import { opacity } from 'styled-system';`

 Maybe I'm just missing it, but I don't see opacity in any @styled-system package.

**Comment by jxnblk** [comment]
In v5, it's part of the `@styled-system/color` package and should be exported by the main `styled-system` package

**Comment by leantide** [comment]
Thanks. I should have figured that out.
FWIW, table @ https://styled-system.com/guides/migrating could be updated to show opacity under color.
