### ISSUE TITLE
defaultProps + system

### ISSUE THREAD

**Issue by kevinSuttle** [styled-system/styled-system#537]
Given the following, theme values and component:
```js
// theme.js
const fontSizes = [10, 11, 12, 14, 16, 18, 22];
const lineHeights = [
  `${space[3]}px`,
  `${space[4]}px`,
  `${space[5]}px`,
  `${space[6]}px`,
  `${space[7]}px`,
];
const fontWeights = [400, 500, 600];
```

```js
// @flow

import styled from '@emotion/styled';
import shouldForwardProp from '@styled-system/should-forward-prop';
import {Box} from './Box';

import {compose, system, textStyle} from 'styled-system';
import typography from '@styled-system/typography';

const whiteSpace = system({property: 'whiteSpace', cssProperty: 'white-space'});

const styleProps = compose(
  textStyle,
  typography,
  whiteSpace
);

export const Text = styled(Box, {
  shouldForwardProp,
})(
  {
    label: 'text-primitive',
  },
  styleProps
);

Text.defaultProps = {
  as: 'span',
  color: 'textOnNeutral',
  fontFamily: 'sans',
  fontWeight: 0,
  whiteSpace: 'nowrap',
  fontSize: 1,
  lineHeight: 1,
};
```
This is the output I'm seeing as of v5.0.5.

<img width="600" alt="Image 2019-06-03 at 4 47 45 PM" src="https://user-images.githubusercontent.com/95672/58845925-213fa880-864b-11e9-964e-682033820637.png">

Notice that `white-space` isn't set. I could also very well be overlooking something that's been documented already or have made a typo 😅

**Comment by jxnblk** [comment]
I *think* it's in call to `system`: the arguments to `system` need to have keys for the props you wish to use:

```
const whiteSpace = system({
  whiteSpace: {
    property: 'whiteSpace',
  }
})
```

*Or* since the CSS property is the same as the key, you can use the shorthand: `system({ whiteSpace: true })`

**Comment by kevinSuttle** [comment]
That was it! Thanks @jxnblk!
