### ISSUE TITLE
Prop `fontSize={0}` returns css `font-size: 0` instead of taking the first item in the theme.fontSizes array

### ISSUE THREAD

**Issue by laij84** [styled-system/styled-system#540]
Styled-System 5.0.4

When using the { typography } on a styled component, passing a fontSize prop of 0 renders the element with css `font-size: 0` instead of taking the size defined in the array at position index 0 (fontSizes[0]). Passing `fontSizes={1}` however returns the size defined in fontSizes[1].

Is this the expected behaviour? Should the first item in the array be made 0 like the space scale?

**Comment by jxnblk** [comment]
This should’ve been fixed in 5.0.5 if you can try that version

**Comment by peduarte** [comment]
Working fine for me in `5.0.5`

**Comment by laij84** [comment]
Same can close issue
