### ISSUE TITLE
Compose not combining props system as expected

### ISSUE THREAD

**Issue by chrisbull** [styled-system/styled-system#541]
Recommendation... compose should really work like recompose, react-apollo, or any typical compose function. But it doesn't (currently).

What I mean by this is that compose currently doesn't allow for combination styled threads. For example:

```typescript
import styled from 'styled-components/native'
import is from 'typescript-styled-is'
import * as RN from 'react-native'

export const cssProps = compose(
  borders,
  colors,
  flexbox,
  grid,
  layout,
  position,
  shadow,
  space,
  typography,
)

const TextInput = styled(RN.TextInput)(cssProps)

export const boxProps = compose(
  cssProps,
  is('row')({ flexDirection: 'row' }),
  is('col')({ flexDirection: 'column' }),
  is('center')({ justifyContent: 'center', textAlign: 'center' }),
  is('middle')({ alignItems: 'center' }),
  is('alignRight')({ justifyContent: 'end', textAlign: 'right' }),
  is('alignLeft')({ justifyContent: 'start', textAlign: 'left' }),
  is('space')((props: AlignProps) => ({
    alignItems: `space-${props.space}`,
  })),
)

const Box = styled.View(boxProps)
const Text = styled.Text(boxProps)
const LinearGradient styled(LinearGradient)(boxProps)
```

** ⬆️  Doesn't work as expected.  😠 **

As you can see, what I want to do is apply the same set of styled responders to a variable called boxProps. And then reuse boxProps on several different types of components. Otherwise I would have to repeat the code on each component for Box, Text, and LinearGradient. (which is definitely not ideal). 

However, with the method of compose changed to a typical 'compose' structure (like recompose). Then the code works flawlessly. Here is the code I've switched out for compose in my own library.

** Recommended compose functionality** 
```typescript
const compose = <P extends object>(...args: any[]) => (props: P) =>
  args.map((arg) => arg(props))
```

Also, for the love of puppies... please write this library in Typescript!! If you don't want to do it, but are open to a pull request. I've already rewritten your v5.0 library in it already.

**Comment by jxnblk** [comment]
The Styled system `compose` is *only* for use with styled system and handles internal perf improvements. You can add other functions as separate arguments to the `styled.div` to use other style props. If you’re trying to share these as a set, you can keep them in an array and spread them as arguments *or* use a separate function compose utility

**Comment by chrisbull** [comment]
@jxnblk Great answer. But i'm sharing more as a fan of styled-system, and believe consumers like myself, who are trying to use it for react-native ... find the current setup confusing, unconventional, and difficult to use with react-native and react-native-web. I think with a few minor adjustments, it would be the ultimate library for more users.

**Comment by jxnblk** [comment]
Thanks for the ideas/discussion! Going to close this for now. The Styled System `compose` is a utility meant only for the parser functions in this library. A more general purpose utility like you're proposing is an interesting idea – if you'd like to open a PR or RFC for a separate package to do some of this, I'd be happy to take a look.

For use with React Native, I'd love some help in adapting this library into a separate package that would work well for RN. I do not use RN myself, so haven't spent any time looking into it at all. Also see #302
