### ISSUE TITLE
Named Alias Not Working for Space

### ISSUE THREAD

**Issue by moshemo** [styled-system/styled-system#544]
I have created the following space array with aliases:

```
const space = [0, 1, 4, 8, 16, 32, 64, 128, 256]

space.none = space[0]
space.one = space[1]
space.xxs = space[2]
space.xs = space[3]
space.sm = space[4]
space.md = space[5]
space.lg = space[6]
space.xl = space[7]
space.xxl = space[8]
```

And I have a header component that I added the space function to.  This component works fine if I reference the space array index -- like this:  `<Header px={5}>`

But if I try to use the alias, it will not work.  I.e., this does NOT work:  `<Header px='md'>`

Any idea why this doesn't work?  

Thanks.

**Comment by mfix22** [comment]
Hey @moshemo, I can imagine it being any number of issues.

I have created an example on Code sandbox here: https://codesandbox.io/embed/cranky-chatelet-wf3o5 that shows an example for your use case above.
