### ISSUE TITLE
Duplicated className style props

### ISSUE THREAD

**Issue by tresko** [styled-system/styled-system#546]
ClassName style props are duplicated in version 5.0.5. Check Heading component in [the example](https://codesandbox.io/s/styledsystembasicdemo-fqy1r).

![example](http://shrani.si/f/M/K4/2OWKGYTL/screenshot-2019-06-07-at.png)

[Example: https://codesandbox.io/s/styledsystembasicdemo-fqy1r](https://codesandbox.io/s/styledsystembasicdemo-fqy1r)

**Comment by peduarte** [comment]
Can confirm 👍

**Comment by jxnblk** [comment]
Ah, I see what’s happening. The `fontSize`and `lineHeight` functions are shimmed so that things don’t break when upgrading, but they should be replaced with the new `typography` one. I’ll see if there’s a way to avoid the duplication in the shims as well though

**Comment by colepeters** [comment]
I'm seeing the same thing with properties from style functions other than `typography`, FWIW: https://zpt80.codesandbox.io/

![image](https://user-images.githubusercontent.com/1713932/59209557-3350a800-8b71-11e9-96ed-80f221ff068b.png)

**Comment by jxnblk** [comment]
@colepeters this will probably happen for any of the new category functions

**Comment by colepeters** [comment]
@jxnblk Just to clarify: even if only the category functions are used, and not any shims from the same category?

**Comment by jxnblk** [comment]
@colepeters if only the new category functions are used, it should *not* happen. I can't seem to see the source code for the codesandbox above, so I'm unsure how you've used it...

**Comment by colepeters** [comment]
@jxnblk Crap, sorry, I'm horribly late to codesandbox — does this work? https://codesandbox.io/embed/bold-night-zpt80

**Comment by jxnblk** [comment]
@colepeters it looks like you have a few "duplicate" functions in there. 

Instead of this:
```js
const Box = styled("div")(
  border,
  boxShadow,
  color,
  display,
  flexbox,
  layout,
  opacity,
  overflow,
  position,
  space,
  typography,
  transition
)
```

Try this:
```js
const Box = styled("div")(
  compose(
    border,
    shadow,
    color,
    flexbox,
    layout,
    position,
    space,
    typography,
    transition
  )
)
```

Things to note:
- The `compose` utility *should* dedupe these if they exist
- `display` and `overflow` are included in `layout`
- `opacity` is included in `color`

**Comment by colepeters** [comment]
@jxnblk Thanks! I had an instance similar to the codesandbox example in my codebase without the 'duplicates' where this was also happening, but as soon as I wrapped them with the `compose` function, things were tidy as heck. Yay!

**Comment by jxnblk** [comment]
Generally you should use `compose` to combine multiple style props to avoid this issue. The shims have been updated to help mitigate some cases where this would happen. Closing this issue, but feel free to open new issues if needed
