### ISSUE TITLE
compose does not maintain stable order of media queries

### ISSUE THREAD

**Issue by ericberens** [styled-system/styled-system#549]
Using `styled-system@4.2.4` If you `compose` a set of styles together and use responsive arrays then depending on the order or the interpolation functions in the composed statement it will generate css media queries in the incorrect order. This appears due to the way the style objects are merged together.

Given: 
```
const Box = styled("div")(
  compose(
    backgroundColor,
    width
  )
);
```

and usage with the default breakpoints from styled-system:
```
<BrokenBox
  backgroundColor={["purple", null, "yellow"]}
  width={[1, 3 / 4, 1 / 2]}
>
```

then the background color is displayed correctly across breakpoints but the width is not.

Demonstration of the issue (`BrokenBox`) and a potential solve (`Box`):

https://codesandbox.io/s/styled-system-v4-oq04k

It does appear that the same issue is in v5.x too but I have not looked into a fix yet.

https://codesandbox.io/s/styled-system-v5-89ktj

**Comment by ericberens** [comment]
Happy to open a PR to fix the v4.x issue if there isn't a more performant solve (not overly excited about looping over each breakpoint again to re-order the media queries back into the correct order). Also would like to find a way to test that the order of the returned styles is as expected. `to(Strict)Equal` won't do the trick.

**Comment by jxnblk** [comment]
This *should* be resolved in `v5.0.18`, but please reopen the issue if not

**Comment by jxnblk** [comment]
Sorry, just remembered this was for v4, not v5. If you're able to PR a fix for v4, we can try to get that fix published still

**Comment by jxnblk** [comment]
Closing this since no work has been done to v4 for a while. Feel free to open a PR for v4 if needed
