### ISSUE TITLE
Plans to remove individual style functions

### ISSUE THREAD

**Issue by peduarte** [styled-system/styled-system#550]
Hey 👋 

With the new addition of Style Categories, are there any future plans to remove access to individual Style functions?

I'm asking because:
1. Those functions are commented with `v4 shim` in [main export](https://github.com/styled-system/styled-system/blob/master/packages/styled-system/src/index.js#L30)
2. I'm not planning on using Style Categories exclusively

Regarding point 2, I'm not a fan of over-exposing Style Props to the public API of my components, and quite often I only want to allow `margin` to be exposed and not `padding` for example. Or perhaps just `backgroundColor` and not `color`.

Personally I think Style Categories are useful for looser API's but it shouldn't be the only way to access the Style props.

PS: please keep them 🙏

**Comment by jxnblk** [comment]
The real push is to use the `system` function directly, which would let you define exactly which props you do and don't want to use on your components. Part of the thinking is that this could (potentially/maybe/no-promises) be a better way of handling types with styled-system – i.e. you'd define your own types for props & theme values however you want. Using `system` directly is also meant to help with some of the performance issues of having multiple v4 style functions on the same component

That said, there could be another package separate from the core that includes some of these as individual functions

**Comment by peduarte** [comment]
Interesting. If the push is to use `system` mainly, then it'd also make sense that the Style Categories are installed separately - that way, the main Styled System library is `packages/core`.

Quite like that idea, it's lightweight and composable.

This also means I can build my own Styled System API :)

Should help fix some of the Typescript annoyances.
