### ISSUE TITLE
Consider switching away from css() namespace

### ISSUE THREAD

**Issue by kof** [styled-system/styled-system#553]
To follow up on our twitterland discussions, here are a few challenges which come up once you start using css function from styled-system and css prop babel plugin proxy:

### Problems
1. You might end up importing 2 css() functions from both emotion and styled-system within one product. This will result in mental overhead because you always need to look up which one is used right now.
1. Same thing with css prop from emotion and styled-system
1. If you try to stick with css() function from styled-system, but you actually want to use a regular CSS value, you can use a string value, so that styled-system doesn't match it with the scales, but this is an implicit, magical behavior.
1. You might want to have a style object which uses scales and regular values in one.

### Potential solutions:

Rename styled-system css() function and the prop to something else, for example: `scss` - system css.

**Comment by jxnblk** [comment]
Thanks! If the named export changes, I want to make sure it's a solid choice before rolling it out since it's used in a few places already.

Here's just a few quick thoughts:

1. With Styled System CSS, you can rename the import whatever, which might make sense to go ahead and show in the docs for clarity, e.g. `import sx from '@styled-system/css'`
2. With the above, it'd become `css={sx({ color: 'primary' })}`
3. See https://github.com/styled-system/extras/pull/24 – I'd still like a solution for opting-out built into the API, but `fontSize: 1` vs. `fontSize: '1px'` will probably remain as far as how values work by default
4. I think the solution above should cover this

There's also the issue of using a custom pragma for this. It currently uses the same `css` prop as Emotion, but perhaps a different prop name for this would also be important to include as part of this

**Comment by kof** [comment]
1.Yes, renaming imports is possible in any case, it's just that there will be struggles to unify that convention in the teams.
3.Let's keep exploring a possible interface, downsides of `raw(value)` :
- yet another import
- needs to be repeated around every value, more verbose
Benefits: it is explicit.

**Comment by jxnblk** [comment]
Yeah, totally get that

> needs to be repeated around every value, more verbose

I think the idea of adopting something like Styled System is that the theme-based values *are* the default and raw values are the exception, so ideally you wouldn't need it for **every** value, right?

In thinking about this issue across the board of applications we're looking at, I'm leaning more towards using a custom pragma (that uses Emotion's create element function under the hood). This pragma would need to be set at the top of a module using it with a comment, and it could leverage a separate prop for styled-system-css values. This would help with using this in a library that other apps consumer. Curious what you think of this approach:

E.g.

```jsx
/** @jsx jsx */
import jsx from '@styled-system/jsx'

export default props =>
  <div
    scss={{
      // styled-system styles
      mx: 2,
    }}
    css={{
      // raw values if you want them
    }}
/>
```

**Comment by kof** [comment]
yes this is exactly what I ment by

> Rename styled-system css() function and the prop to something else, for example: scss - system css.

**Comment by jxnblk** [comment]
After bouncing this idea around a little, some people (understandably) don't react well to the `scss` name :)

I'd like to have a clear and memorable prop name like `css`, but `scss` is certainly cryptic and has its own baggage. The only other name I've come up with so far that feels right (which is also a little cryptic) is `sx` – some loose variant of the `style` & `styled-system` but terse enough to read well in code.

```jsx
// example
<div
  sx={{
    fontSize: [ 4, 5 ],
    fontWeight: 'bold',
    color: 'primary',
  }}
/>
```

**Comment by kof** [comment]
More ideas:
 
"ss" - styled system (probably won't go well bc. of ww2)
"cs" - constrained styles
"stsy" - first chars of styled system
"sts" - first two chars off styled and first char of system

**Comment by jxnblk** [comment]
> probably won't go well bc. of ww2

Yes, this is *completely* off the table, and I try to make sure this library is never abbreviated that way

**Comment by VinSpee** [comment]
> I try to make sure this library is never abbreviated that way

choosing something for _the purpose outlined in this thread_ also helps to prevent that from happening by heading it off at the pass.


I know this isn't a democracy, but I think `sx` is nice - terse, uncommon kinda sleek. On the other hand, saying `ess ex` out loud can be muddy. Where do you want the emphasis? s__x__? __s__x?__sx__?

**Comment by matthova** [comment]
Some more ideas, since the argument being passed in is an object
jss
jcss
jsoncss
jscss
cssjs
cssjson

**Comment by jxnblk** [comment]
As of `theme-ui@0.2.0` the custom JSX pragma now uses the `sx` (system) prop. The `@styled-system/jsx` package will be deprecated (#575) in favor of the `theme-ui` package, so I'm closing this out. A new issue has been created to disambiguate the usage in the docs: #578
