### ISSUE TITLE
Where can I find v4 docs?

### ISSUE THREAD

**Issue by lucasconstantino** [styled-system/styled-system#555]
Hello there.

I'm still stuck with v4 due to proper TypeScript support. Can I find that version's docs published anywhere?

**Comment by jxnblk** [comment]
https://github.com/styled-system/styled-system/tree/v4.2.3/docs

**Comment by lucasconstantino** [comment]
@jxnblk I took the permission to publish that on surge here:

http://styled-system--v4-2-3.surge.sh

If you disagree with that, please advise and I'll remove it.

**Comment by jxnblk** [comment]
That’s fine. It’s all available under the MIT license anyhow
