### ISSUE TITLE
@styled-system/css with breakpoint objects

### ISSUE THREAD

**Issue by ruaridhnewman** [styled-system/styled-system#558]
I am having an issue when using `@styled-system/css` where using breakpoint objects in our theme causes `css` to error with `breakpoints.map is not a function`. Our theme has something like this in it:

```
const theme = {
    breakpoints: {
        s: '1px',
        m: '2px',
        l: '3px',
        xl: '4px'
    }
}
```

which works for everything else, but just seems to break when we use the `css` functionality as described in the docs.

Removing the breakpoint object array from the theme fixes it (as I assume it will fallback to the default breakpoints), and also changing it to be an array instead of an object fixes the error.

I guess the `css` package just needs to be updated to handle breakpoint objects as well as arrays, or do you think I am doing something incorrect?

**Comment by jxnblk** [comment]
The css package does not currently handle plain objects for `theme.breakpoints`.

In style objects, you can use standard media query syntax as an alternative to the array syntax

**Comment by jxnblk** [comment]
Thanks for bringing this up! After considering this a bit, I think since the `@styled-system/css` package only supports arrays for responsive values, it doesn't really make sense to define breakpoints as a plain object when using this package. I'd like to add some utilities to make working with the `@media` rule syntax a little bit more ergonomic (which will require some exploration), but I'm going to close this issue for now

**Comment by frederickfogerty** [comment]
Hey @jxnblk, I understand that the `css` package is different to the main styled-system library, but this package provides the supposed solution to a real problem we have, and I was wondering how you would suggest we solve it without the use of this package.

Problem: **using styled-system props with a non-styled-system child**

```js
const UnstyledCard = ({ className } : { className?: string }) => <div className={className} />

const StyledCard = styled(UnstyledCard)(
  css({
    px: '12px'
  })
)
// we can't use .defaultProps here or anything, because the UnstyledCard doesn't support styled-system props
// I also think that adding the styled-system helpers to every component doesn't make much sense either.
```
