### ISSUE TITLE
Is it a good idea to rely on object key order in v5?

### ISSUE THREAD

**Issue by nikparo** [styled-system/styled-system#560]
This is not a bug report, but rather some thoughts around implementation.

I've been using styled-system v3 in a commercial project for some time, and It's been good. Trying to upgrade to v5 in the last few days, I have realized that it is now relying on the object key order (prop order) and enumeration to be stable. Is this actually a good idea? From some brief research, [key order is not guaranteed even in ES6](https://stackoverflow.com/a/30919039/5909251). While it may work in practise in modern browsers, what about older browsers such as Internet Explorer 11 etc?

**Comment by jxnblk** [comment]
If you’re not mixing conflicting style props, it generally shouldn’t matter, should it? If you have some examples of where the shortcomings are, I think they could potentially be good additions to the docs (I.e. mixing shorthand and normal border properties)

**Comment by nikparo** [comment]
If the order is not as expected, then there are multiple properties that can easily conflict. E.g. `p` overriding `pr` etc., same for `m`, `mx`, `mr`,... `variant` css overriding other properties that are set explicitly. `border` short-hand overriding `borderColor`.

I should mention that I created this thread as a follow up to finding out that `defaultProps` get appended to `props`, messing with the expected order. See [#499](https://github.com/styled-system/styled-system/issues/499#issuecomment-502356817) for that. However, any environment that has an unstable, or differing, object key order implementation would suffer similar problems.

**Comment by kof** [comment]
It has always worked and is in the latest specs strictly definef.

I get this question from time to time on JSS repo.

**Comment by andycarrell** [comment]
👍 to this being an issue.
For example:
```
<ABox py="100px" pt="50px" />

<ABox pt="50px" py="100px" />
```
Producing different results - even if this is "expected", it's very brittle. Any given refactor could break, code styling rules/guidelines can require props to be applied in alphabetical order, plus the issue with default props (as linked by @nikparo). 

I don't really want to debate the merits of code style-guides, but point out that this functionality is a bit hidden, and likely to trip developers up as they start with the library, as well as resulting in brittle code long term.

**Comment by jxnblk** [comment]
Thanks for bringing attention to this, but since this issue isn't very actionable on its own, I'm going to close in favor of https://github.com/styled-system/styled-system/issues/499#issuecomment-498045390 – I think a PR for failing test cases (potentially with React integration) is the best way to proceed

If you'd like to open an issue or PR to help document some of the pitfalls around using CSS shorthand syntax, that would also be very helpful, IMO

**Comment by kof** [comment]
What can be done is adding tests which ensure specific order, just for the case that the logic changes unexpectedly and order changes accordingly, not because javascript has an issue with object props order.
