### ISSUE TITLE
Style functions exposing extra props

### ISSUE THREAD

**Issue by peduarte** [styled-system/styled-system#562]
Hey 👋 

I've noticed that implementing `maxWidth` Style function, also exposes a [extra props](https://github.com/styled-system/styled-system/blob/master/packages/layout/src/index.js), such as:
- `width`
- `height`
- `minWidth`
- `minHeight`
- `maxHeight`
- `size`

For example:
```jsx
export const Container = styled("div")(
  props => ({
    marginLeft: "auto",
    marginRight: "auto"
  }),
  maxWidth
);

<Container maxWidth={320} size={0} />
// 👆 size should not be exposed
```

[Demo here](https://codesandbox.io/s/styled-system-issue-eml9w)

I suppose this is somewhat related to #546 

Cheers

**Comment by jxnblk** [comment]
Maybe this isn't clear enough in the migration doc, but the old non-category functions are only meant as shims to prevent breaking changes. Each shim is a renamed export of its category, so `width` is using the new `layout` function under the hood. Ideally, when migrating to v5, you'd either adopt the preset categories of props *or* use the `system` function to define a set of custom props. 

Hope that makes sense!

**Comment by peduarte** [comment]
@jxnblk Oh right, hmmm. I don't think that makes sense, sorry. 😕 

I think if we're going to shim the old API it needs to work the same way. In my case (as you know) exposing extra props is a huge breaking change. 

I'm not sold on the idea of Styled System forcing users into using Style Categories. I'm personally not a fan of this approach and don't think it should be promoted as best practice, but that's just my opinion. 

I think when it comes to Design Systems, consistency is key, allowing what can be overriden is crucial to maintain consistency. The moment components accept more props than they should, we're welcoming undesired behaviours and inconsistent results.

Given that Styled System is becoming the go-to library to build Design Systems, I think there's a certain level of responsibility to advocate best practices. 

To illustrate what I mean, here's how easily you can brake Github Primer's `Button`:
![image](https://user-images.githubusercontent.com/372831/59626931-fd915d80-9134-11e9-8cf3-77850363fae4.png)

Please don't get me wrong, Primer has done an awesome job, and it's been a huge source of inspiration for Radix. Style Categories seem like a great way to share concerns _internally_ but to expose those concerns to the component API, I think it's a misleading approach.

Maybe I'm misunderstanding the goal of Styled System altogether?

**Comment by jxnblk** [comment]
Right, so it sounds like you'd want to use the `system` function to specify custom props for your custom components. For your example above, you can make a `maxWidth` prop by doing:

```js
styled('div')(
  system({
    maxWidth: {
      property: 'maxWidth',
      scale: 'sizes',
    },
    // add other style props *if* you want them
  })
)
```

You can also use the `system` and `compose` utilities together to create whatever custom categories you want and reuse them across multiple components.

The shims are only meant to be used as shims (to generally prevent things from breaking if you've missed something), but v5 is a breaking change with the API. As far as the v5 API goes, functions like `width` are no longer part of public API. `width` was replaced by `layout`, which is a shortcut with some smart defaults if you want them. I *do* think is a nicer API than leaving no guidance on the matter, but it is certainly more opinionated than before.

In the case of the primer button image you have, that is exactly what I'd expect to happen if I added `p={100}` to a Button, but that doesn't mean I'd ship a button that looks like that :) That is, the API is meant to give developers the flexibility to do things like that when they're asked to do them. The same thing could be done with the `css` prop, an inline style attribute, a global CSS override, etc., this just keeps the styling API consistent and more learnable across multiple components.

**Comment by peduarte** [comment]
Yeah, that's what I've done for now.

Maybe I misunderstood the general direction of Styled System altogether. Allowing any props to be passed in enables a fast way of prototyping stuff, _which is great_, but not how I think Design Systems should work. 

> The same thing could be done with the css prop, an inline style attribute, a global CSS override, etc.

True, but at least that's explicit IMO.

I guess what I need to do now is re-create each Style Function I want to be able to expose individually. Not a big deal, the v5 API does make it very easy 🙂 

---

I've always had the feeling you wanted to keep Styled System as low level and un-opinionated, so I'm quite surprised you've remove the Style Functions in favour of Category Styles.

To me, it feels that Styled System should now be nothing but the low-level  function creators (`system`, `compose`, `createParser` etc...)

And then have two extra packages: `@styled-system/style-functions` and `@styled-system/category-styles`.

Appreciate this may not be your vision though 👍

**Comment by jxnblk** [comment]
Yeah, the new API is really in `@styled-system/core` and `styled-system` is meant to help transition to that. The optional categories are in packages like `@styled-system/typography` `@styled-system/space`, etc. – the thinking is if you make something like a `Text` component, you'll probably want all the typographic style props together, and if you add a `Heading` and `Subhead` component, they all have the same props API, so it's less API surface area for the end-users of the components

**Comment by jxnblk** [comment]
> I guess what I need to do now is re-create each Style Function I want to be able to expose individually. 

If you're not sharing props across multiple components, you probably don't need to do this, but if you are, then you can also share the `config` objects in modules and pass those to the `system` function where needed – either approach works, just wanted to point that out

```js
import styled from '@emotion/core'
import { system } from '@styled-system/core'
import configs from './styled-system-configs'

const Box = styled(system({ ...configs.space, ...configs.layout }))
```

**Comment by peduarte** [comment]
Good stuff. Sorry for the misunderstanding and thanks for the clarification ✨

**Comment by peduarte** [comment]
#### Update for the ones interested

I've created a custom wrapper on top of `@styled-system/core` which allows me to have more control over how I want the API to work and hand pick which style prop I want to expose.

You can learn more about [Radix System here](https://radix.modulz.app/docs/radix-system)

Here's a list of the main differences
- Typescript support
- style functions are independent
- `color` style function has been renamed to `textColor`
- `space` has been split into `margin` and `padding`
- Theme-aware variant API

Thanks Brent for the idea.
