### ISSUE TITLE
Support for theme lookups on `background` shorthand in `@styled-system/css`

### ISSUE THREAD

**Issue by jxnblk** [styled-system/styled-system#563]
Currently theme-based values can be used in the `background` shorthand property by using a function as a value (e.g. ``` background: t => `${t.colors.primary} url('kitten.png')` ```), but parsing strings could make this syntax a little more ergonomic by splitting the string and checking against an array of keys defined in the theme (e.g. `Object.keys(theme.colors)`). This feature would require a full set of tests to account for edge cases 

Related https://github.com/system-ui/theme-ui/issues/81

**Comment by wagerfield** [comment]
+1 I'd love to have this.

**Comment by jxnblk** [comment]
Closing since `@theme-ui/css` will replace `@styled-system/css`
