### ISSUE TITLE
skipping breakpoints

### ISSUE THREAD

**Issue by VinSpee** [styled-system/styled-system#571]
Hi again!

What's the best way "skip" a breakpoint? for example, I have some components which look like this:

```jsx
  <Flex
    css={{
      justifyContent: [undefined, undefined, undefined, 'space-between'],
      flexDirection: ['column', undefined, undefined, 'row'],
      fontSize: [2, undefined, 1],
    }}
  >
    …
  </Flex>
```

Is there a better way to _skip_ a breakpoint besides passing `undefined`?

**Comment by jxnblk** [comment]
That's the general idea, yes. You *should* also be able to use `width: [ '100%', null, '50%' ]`or `width: [ '100%', , '50%' ]`, but just noticed there's a bug with that behavior

**Comment by VinSpee** [comment]
🤣 I just tried `null` thinking "that's shorter" and saw that bug
