### ISSUE TITLE
Duplicate CSS properties

### ISSUE THREAD

**Issue by snesjhon** [styled-system/styled-system#573]
I was trying to see how `rebass.js` components had been created, so I copied the `Box` and `Button` source from [here](https://github.com/rebassjs/rebass/blob/master/src/index.js).

It all works as expected, however when I looked at the source I found duplicated css properties. I'm not sure if this is intended or I did something wrong. My guess is something with the defaultProps, that might be adding extra styling logic(?)

If I look at the rebass component's source, I don't find the same duplication issue. 

Below is a screenshot of the `Button` component in `index.js`. Here is the source https://codesandbox.io/s/styled-system-bug-0rsuz

![image](https://user-images.githubusercontent.com/5641734/59813055-fa2cdc00-92c4-11e9-910b-7539518c184a.png)

**Comment by snesjhon** [comment]
I thought this was a different task but after applying the suggestion here: https://github.com/styled-system/styled-system/issues/546#issuecomment-501059693

I was able to deduped the properties. Although I'm still getting duped media queries, but it looks like that'll be solved with: https://github.com/styled-system/styled-system/issues/546#issuecomment-500462069

Closing the issue.

**Comment by snesjhon** [comment]
Sorry to open this again, but after continuing with the solution above I discovered something with `compose` and `variant` in relations to how it interacts with `defaultProps` 

If I follow the `compose` route, I am able to remove the duplicated css. That's great!

Using the following: 
```
${compose(
    border,
    borderColor,
    borderRadius,
    fontWeight,
    buttonStyle
  )}
```
I also have the following defaultProps 

```
Button.defaultProps = {
  as: "button",
  px: 2,
  py: 1,
  fontSize: "inherit",
  fontWeight: "inherit",
  color: "white",
  bg: "blue",
  border: "1px solid",
  borderColor: "yellow",
  borderRadius: "4px",
  hoverColor: "var(--hover1)"
};
```

However if I add a variant, for example: 

```
// theme.js
const buttons = {
  cancel: {
    color: "gray",
    backgroundColor: "white",
    border: "1px solid",
    borderColor: "red",
    "&:hover": {
      borderColor: "pink",
      color: "white"
    }
  }
};

export default {
  buttons
};
```

The `defaultProps` border takes precedent over the variant -- but only if I have the `compose` function in the component. But if I take out the `compose`, it works ... but I'm back to the original issue of duplicated css. 

Here's the repro link, including commented lines to toggle between working / non-working examples.

https://codesandbox.io/s/styled-system-bug-0rsuz

**Comment by jxnblk** [comment]
I'd recommend not using style props that collide with CSS properties in a variant. I.e. if you'd like to expose the `color` prop, use `defaultProps` to set a default, but don't include color styles in a variant on the same component. The two APIs are meant for different use cases, and because of how the CSS will be generated, I don't think there's a good way for Styled System to control that sort of thing

**Comment by snesjhon** [comment]
Got it. Thank you for the clarification @jxnblk !
