### ISSUE TITLE
All properties from parent category get included when applying an individual prop

### ISSUE THREAD

**Issue by emplums** [styled-system/styled-system#580]
I _think_ I've discovered a bug! 

I noticed while working on Primer Components that it seems that all props that exist in a category get included when trying to include just one prop from that category.

For example, I've got some custom categories in Primer Components, one of them being `LAYOUT`:

```
export const LAYOUT = compose(
  styledSystem.width,
  styledSystem.height,
  styledSystem.minWidth,
  styledSystem.minHeight,
  styledSystem.maxWidth,
  styledSystem.maxHeight,
  styledSystem.overflow,
  styledSystem.verticalAlign
)
```

Note that `display` is purposefully excluded from `LAYOUT` because I've already included it in `COMMON`, a different custom category that I've made.

I noticed in my snapshots for our `Box` component that the `display` prop is implemented twice. I confirmed that this was happening by removing `COMMON` from my `Box` component (which previously had both `COMMON` and `LAYOUT`) and seeing if `Box` still gets the `display` prop (from `LAYOUT`) and it does.

Further, I tested out this:

```
export const LAYOUT = compose(
  styledSystem.width,
  styledSystem.height
)

``` 

and confirmed that a component importing the `LAYOUT` group of props is still able to use all the other props in the `layout` category in styled system, even though I've only included `width` and `height`. 

I also tested renaming my custom group of props from `LAYOUT` to `ASDFG` to double check that this wasn't happening because of a naming clash, and confirmed that this still happens with a totally random name.

**Comment by emplums** [comment]
I'll link to a PR demonstrating this soon!

**Comment by jxnblk** [comment]
This is a known issue – from my phone but can link to relevant issues later. In a nutshell, `width` isn’t part of the v5 api but it is provided as a shim to prevent accidental breaks. If you want to only use the width prop without the other layout props, you can use the lower-level `system` API to create a custom style prop

**Comment by emplums** [comment]
Awesome, thanks @jxnblk!
