### ISSUE TITLE
Allow theme values in variants

### ISSUE THREAD

**Issue by sapegin** [styled-system/styled-system#582]
Now you have to use literal values for CSS properties in variants:

```js
textStyles: {
  xsmall: {
	color: colors.base,
	fontFamily: fonts.heading,
	fontWeight: fontWeights.base,
	lineHeight: lineHeights.base,
	letterSpacing: letterSpacings.base,
        fontSize: fontSizes.xs,
  },
}
```

Which isn't just awkward but don't allow you to use dynamic theming, for example a dark theme which inverts text and background color. For variants this values are hardcoded at load time, so they would remain not inverted.

It would be great to be able to use theme values, similar to [@styled-system/css](https://github.com/styled-system/styled-system/tree/master/packages/css):

```js
textStyles: {
  xsmall: {
	color: 'base',
	fontFamily: 'heading',
	fontWeight: 'base',
	lineHeight: 'base',
	letterSpacing: 'base',
        fontSize: 'xs',
  },
}
```

And apply them at render time, so we'd have access to the current theme for a component.

**Comment by jxnblk** [comment]
Heads up: this landed in `5.1.0` with a *slightly* updated API: https://styled-system/variants
