### ISSUE TITLE
Custom `size` variant applies `width`and `height` properties

### ISSUE THREAD

**Issue by rafaelderolez** [styled-system/styled-system#588]
Hello 👋.

I'm creating a custom buttonSize variant with help from the ([docs](https://styled-system.com/variants#custom-variants)).

```
const buttonSizesVariant = variant({
  // theme key for variant definitions
  scale: 'buttonSizes',
  // component prop
  prop: 'size',
})
```

```
const buttonSizes = {
  small: {
    padding: `${space[1]} ${space[4]}`,
  },
};
```

The above works fine and applies my padding as expected using my `space`, but it also applies `width: small;` and `height: small;` on my button component. I think this is due to [this line](https://github.com/styled-system/styled-system/blob/6cca63469ea931dde9ade1cc46823e256855967b/packages/layout/src/index.js#L33) in styled-system/packages/layout/src/index.js.

```
size: {
    properties: ['width', 'height'],
    scale: 'sizes',
  },
```

Is this expected behaviour?

**Comment by jxnblk** [comment]
Are you also including the `layout` or a deprecated layout function in the same component? That would cause a conflicting prop name since it also uses a `size` prop

**Comment by rafaelderolez** [comment]
Yes it also has `layout`. I've resorted using a different prop key in the meantime. Just found it weird to provide the `size` prop for the custom variant if the same key is used elsewhere!

**Comment by jxnblk** [comment]
The `layout` function adds a set of props, including `size` (for width and height), so if you use `layout`, you'd probably want to not use the same prop name for something else, if that makes sense. You can also use the `system` utility directly for more control of what props you want to add to a component

**Comment by ConnorTCM** [comment]
Hi @jxnblk. Really enjoying using Styled System, but I was wondering if there is any way to omit just the `size` prop when including the `layout` function? I agree with @rafaelderolez that the `size` prop name is a bit odd as being able to alter the size of a component (in more ways than just the height and width) is something that I do quite frequently. Being able to omit it would help reduce a fair amount of refactoring of existing components.
