### ISSUE TITLE
Nested themes for local breakpoints not working

### ISSUE THREAD

**Issue by gregoralbrecht** [styled-system/styled-system#592]
I've noticed something weird with nested themes and their respective breakpoints. We have a "base" theme with the default `const breakpoints = ['40em', '52em', '64em']`. Sometimes, we want to use "local" overrides of the base theme, e.g. for a component that might have only one breakpoint which is not in the array above. We do this like this (There's one other `ThemeProvider` further up the component tree with the "default" theme):

```jsx
const Example = () => {
  const localTheme = theme => ({
    ...theme,
    breakpoints: ['11em', '22em', '33em'],
  })

  return (
    <ThemeProvider theme={localTheme}>
      {/* Should be shown above 11em */}
      <Text display={['none', 'block']}>Hola.</Text>
    <ThemeProvider>
  )
}
```

While this works completely fine for one component, it behaves really strangely in one other.

Using the above "local theme" with:
```jsx
<Text
  color={['white', 'hotpink', 'white']}
  fontSize={[1, 2, 3]}
>
  Hola.
</Text>
```

... results in:

![image](https://user-images.githubusercontent.com/6179211/60445898-7c4fc580-9c20-11e9-978d-bf41d7160ed4.png)

So, the `color` prop uses the "local theme" values, but `fontSize` uses the default breakpoints. Am I missing something obvious here?

**Comment by jxnblk** [comment]
Just noticed this isn't in the migration guide, but with v5, breakpoints are cached by the function, see https://github.com/styled-system/styled-system/blob/master/CHANGELOG.md#v500-2019-06-02 – v4 should support dynamic & nested breakpoints fwiw

This seems like a fairly unique use-case, but mind if I ask why you don't keep all breakpoints together in the root-level theme?

**Comment by gregoralbrecht** [comment]
I was afraid you'd say this is a v5 thing 😅 Makes sense though, because this popped up after we upgraded. I believe globally defined breakpoints work totally fine for most use-cases but some components do need more granular control. The most common example might be a header which can easily have more than 3 breakpoints to look good on all kinds of window widths.

**Comment by jxnblk** [comment]
Yeah, totally get that. I was anticipating some issues related to how the caching of breakpoints works, and I would like to provide a way to do what you're describing – it's just not in there yet. I'll definitely keep this in mind as I think about how to handle this in a good way – right now I'm thinking the API could involve something like adding a `disableStyledSystemCache` boolean to a theme

**Comment by gregoralbrecht** [comment]
Glad to hear you have a plan for this. Is there anything we could do on our side to make this work with v5 until this is implemented? Also, is there anything we could do to support you with this?

**Comment by jxnblk** [comment]
Sure! The relevant caching stuff starts here: https://github.com/styled-system/styled-system/blob/master/packages/core/src/index.js#L39-L41 – if you start a PR, I'd suggest starting with a failing test and working from there. Without any upstream changes, you might be able to nuke the `cache.breakpoints` and `cache.media` objects, which are added to each parser function as a static property, but that's probably less-than-ideal
