### ISSUE TITLE
Grid utility examples

### ISSUE THREAD

**Issue by grantmoran** [styled-system/styled-system#604]
Hello all,

I'm very new to styled-system and have been digging around for basic examples of the [grid utility](https://styled-system.com/api#grid-layout) in action but haven't found anything substantial. Most of the documentation is Flexbox oriented. Additionally, many other searches result in projects which seem to be using styled-system for some things and Rebass for layout issues but again, Flexbox.

I love the [Rebass grid examples](https://rebassjs.org/grid/) and hoping someone can shed some light on the basics of a grid layout implementation using only styled-system if possible. A basic responsive layout example using the grid utility would be killer.

Excuse my naivety and thanks for the time reviewing my question.

Cheers!

**Comment by jxnblk** [comment]
I don't think there are many official examples of using CSS grid properties in Styled System, but I'd recommend searching for CSS grid generally to get a sense of how it can work. https://gridbyexample.com/ is a good place to start, but I know there are many other resources out there

**Comment by grantmoran** [comment]
Thanks for the reply, I'm fairly familiar with how CSS grid works but was just looking for something high level for styled-system. I've been playing with it for a bit now and think I have a sense of how to accomplish it. I'll try to write something up soon and see if it's worthy for documentation examples possibly as I know I've seen some others ask about this as well.

Thanks!!

**Comment by jxnblk** [comment]
Yeah, IMHO CSS Grid Layout is sorta tricky to abstract with something like styled system, but the utilities are there if you need them. Would love to see what you come up with regardless!
