### ISSUE TITLE
Using the mediaQueries key in theme

### ISSUE THREAD

**Issue by sanjilshah** [styled-system/styled-system#606]
The theme specification document mentions a ["mediaQueries"](https://styled-system.com/theme-specification#media-queries) key, can someone guide me how to use it along with breakpoints? I am looking to add device orientation based media queries.

**Comment by jxnblk** [comment]
There isn't currently anything built in to Styled System that uses `theme.mediaQueries`, but it can be used as a convention for manually using the `theme.breakpoints` array in other places. With an array of `breakpoints`, you can add ```theme.mediaQueries = breakpoints.map(n => `@media screen and (min-width: ${n})`)``` along with any other values you'd like to the `theme` object. How you reference and use it beyond that is up to you

**Comment by nickcobbett** [comment]
@sanjilshah not sure if this is what you're asking but this is one (kinda ugly) way to make use of the `mediaQueries` key.
```js
const Text = styled.div`
  display: none;
  ${({ theme }) => `${theme.mediaQueries.medium} {
    display: block;
  }`}
`;
```
