### ISSUE TITLE
Typescript and themeGet

### ISSUE THREAD

**Issue by benjamingeorge** [styled-system/styled-system#609]
I'm trying to use the new `@styled-system/theme-get` package but typescript complains about no types.  are these available?  I didn't find anything on @types repo.

**Comment by benjamingeorge** [comment]
If anyone needs a quick solution (albeit maybe not absolutely correct) you can create a delcaration file in your /src/@styled-system/theme-get/index.d.ts and add 
```ts
declare module '@styled-system/theme-get' {
    export function themeGet(path: string, fallback?: any): any;
}
```

**Comment by jxnblk** [comment]
It looks like you've found a solution, so closing this out for now. Feel free to open a new issue if needed

**Comment by Jerry-Hong** [comment]
@benjamingeorge @jxnblk 
I have created a PR to DefinitelyTyped, it will fix this issue
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40275
