### ISSUE TITLE
Allow custom propTypes creation

### ISSUE THREAD

**Issue by selrond** [styled-system/styled-system#618]
Despite having style groups (modules) from `v5`, I still use some single functions from `styled-system`. 
Like this `Box.js` component

```js
import { layout, flex, alignSelf, justifySelf, order } from 'styled-system'
```

I don't need whole `flexbox` group, since I have a separate `Flex.js` component for that.

`@styled-system/proptypes` provides `propTypes` only for those groups. Thus I need to manually create propTypes for those single functions. 

I suggest exporting `createPropTypes` function from https://github.com/styled-system/styled-system/blob/master/packages/prop-types/src/index.js#L25 so one doesn't need to reinvent the wheel each time. 

So it could become

```js
Box.propTypes = {
  ...PropTypes.layout,
  ...createPropTypes(flex.propNames),
  ...createPropTypes(alignSelf.propNames),
  ...createPropTypes(justifySelf.propNames),
  ...createPropTypes(order.propNames),
}
```

**Comment by jxnblk** [comment]
You should be able to `import { createPropTypes } from '@styled-system/prop-types` now

**Comment by selrond** [comment]
Great, thanks!
