### ISSUE TITLE
Hook into the breakpoints system for custom props

### ISSUE THREAD

**Issue by anzorb** [styled-system/styled-system#629]
Good afternoon folks, I am curious if it is possible to hook into styled-system's breakpoint mechanism for custom props. For example, I am working on a Container component that controls the margin of its children based on a prop. I'd like to have the prop accept an array same as `space` would:

```
const Container = styled.div`
> * + * {
   margin-left: ${props => props.spacing + 'px'}
}
`

<Container spacing={[1, 2]}></Container>
```
```
const theme = { 
    spacing: [8, 16, ...]
}
```

The above would result in a margin of 8px on mobile and 16px on tablet+

Thanks in advance!

**Comment by jxnblk** [comment]
You can use child selectors with Emotion or Styled Components, e.g.

```js
import styled from 'styled-components'
import { space } from 'styled-system'

const SpaceChildren = styled('div')`
  & > * {
    ${space}
  }
`
```
