### ISSUE TITLE
"as" property removes inherited props from "styled" HOC

### ISSUE THREAD

**Issue by mikemclin** [styled-system/styled-system#630]
When "extending with `styled`" as seen here (https://styled-system.com/guides/build-a-box#extending-with-styled), the `as` attribute removes all of the inherited properties from the HOC.

```js
const Box = styled.div(space);

const Card = styled(Box)({
  borderRadius: '4',
  border: '1px solid #f6f6f6',
  boxShadow: '0 2px 4px rgba(0, 0, 0, .125)',
});

<Box as="p" m="3">I have margin</Box>
<Card as="p" m="3">I do not have margin</Card>
```

* `styled-system@5.0.16`
* `styled-components@4.3.2`

This was working with styled-system 4.

**Comment by jxnblk** [comment]
I suspect this is an issue with `styled-components`, but I *thought* they'd fixed this already

**Comment by mikemclin** [comment]
Yeah, I would expect the issue would be with `styled-components`, since it is their function.  However, it was working with `styled-system` 4, so I thought maybe there was something behind the scenes that `styled-system` 5 was doing which was not "friendly" to the `styled` function.

Also, I just tested using `styled-components@5.0.0-beta.8`, and the issue still exists.

**Comment by jxnblk** [comment]
I tried adding an integration test here: https://github.com/styled-system/styled-system/blob/master/packages/styled-system/test/styled-components.js#L40-L52

If you're able to create a PR with another test like this that fails, that could be helpful. The installed version should be `styled-components@4.3.2`

**Comment by jxnblk** [comment]
This appears to work as demonstrated in this [codesandbox](https://codesandbox.io/s/styled-systembasic-demo-o5xes). Please reopen this issue with a failing reproduction if you have an example of the issue described here, if it is different
