### ISSUE TITLE
Add `system`-like override to css package

### ISSUE THREAD

**Issue by TheSisb** [styled-system/styled-system#639]
Currently we generate tokens using Theo and our colors are split into `textColors`, `backgroundColors`, and `globalColors`.  I want to use the `css()` package like this:

```
styled.div(css({
  color: 'colorTextPrimary'
}));
```

But it currently fetches color values from the `colors` bucket, while I want `textColors`. Is there any plans to allow us to override where the values are looked up?  Somewhat like the [system api](https://styled-system.com/api#system).

**Comment by jxnblk** [comment]
Styled System follows the [Theme Specification][], and you can map any other object to the shape that the core library expects.

The `@styled-system/css` package adheres to this specification, and allowing customizing for how that package works would potentially break how it's intended to be used. For style props with the core Styled System library, you can use the `system` API to customize things however you want

[theme specification]: https://github.com/system-ui/theme-specification
