### ISSUE TITLE
Integration with Material-ui

### ISSUE THREAD

**Issue by DDDDDanica** [styled-system/styled-system#643]
Hey,

Just come across an issue when set up the project with `material-UI`, `styled-components` and `styled-system`: The props I defined in the theme cannot be called as a normal variable inside `styled()` method.

So this is the theme setting i have, which i use to wrap my root app component:
```import React from "react";
import PropTypes from "prop-types";
import { ThemeProvider as StyledThemeProvider } from "styled-components";
import { MuiThemeProvider } from "@material-ui/core/styles";
import { StylesProvider } from "@material-ui/styles";
import { StyledTheme, MuiTheme } from "./theme";

const ThemeProvider = ({ children }) => {
  return (
    <StylesProvider injectFirst>
      <StyledThemeProvider theme={StyledTheme}>
        <MuiThemeProvider theme={MuiTheme}>{children}</MuiThemeProvider>
      </StyledThemeProvider>
    </StylesProvider>
  );
};

ThemeProvider.propTypes = {
  children: PropTypes.oneOfType([PropTypes.node, PropTypes.func]).isRequired
};

export default ThemeProvider;
```
and for my `theme.js`, i have:
```
import colors from "./colors";
import { createMuiTheme } from "@material-ui/core/styles";

export const StyledTheme = {
  colors: {
  primaryColor: "#002a32",
  secondaryColor: "#f9c940"
  }
};

export const MuiTheme = createMuiTheme({
  overrides: {
    MuiButton: {
      root: {
        "&:hover": {
          backgroundColor: colors.secondaryColor
        }
      }
    }
  }
});
```

When i'm trying to access it from a material-ui component: 
```
// Library
import React from "react";
// Style
import { color } from "styled-system";
import styled from "styled-components";
// Material UI Components
import Button from "@material-ui/core/Button";

const StyledButton = styled(Button)`
  height: 80px;
  background: ${props => props.theme.colors.primaryColor};
`;

const Component = () => <StyledButton>Styled Button</StyledButton>;

export default Component;
```
Here: I can only use `  background: ${props => props.theme.colors.primaryColor};` instead of `  background: ${colors.primaryColor};`

Do you guys have any solution for this issue?
Thanks :)

**Comment by jxnblk** [comment]
Hi! Material UI uses its own CSS-in-JS library, which can be tricky to integrate with, but I think there might be some misunderstanding of how Styled System works. When you use the `styled` function, you'll want to pass the `color` function like this:

```js
const Button = styled(MUIButton)`
  ${color}
`
```

With that function added, you can use the `color` and `bg` props on the Button, like so `<Button color='tomato' bg='black' />`. That said, Material UI has its own fork of Styled System that does something similar, so you might want to check their docs

Also worth noting that Material UI uses its own React context, which will be different from the Styled Components' theming context

**Comment by DDDDDanica** [comment]
Thanks !!! @jxnblk
