### ISSUE TITLE
TypeScript definitions for @styled-system/should-forward-prop

### ISSUE THREAD

**Issue by nerdyman** [styled-system/styled-system#645]
Hi,

I'm using TypeScript with [@styled-system/should-forward-prop](<https://www.npmjs.com/package/@styled-system/should-forward-prop>) but can't find any type definitions in [@types](<https://github.com/DefinitelyTyped/DefinitelyTyped>) or within the module itself. TypeScript recommends installing `@types/styled-system__should-forward-prop` but it's not a package.

Are there type definitions available for the module?

If not I'm happy to attempt a PR.

Thanks

**Comment by jxnblk** [comment]
Sorry for the delay on this! If you'd like to add types for this package on Definitely Typed, please feel free to do so. Since that code is in another repo, I'm going to close this issue for the time being

**Comment by nerdyman** [comment]
No problem! thanks for getting back to me. I'll take a look at the types in [@types](https://github.com/DefinitelyTyped/DefinitelyTyped).
