### ISSUE TITLE
Document the behaviour of compose() when using both variant and specific styles

### ISSUE THREAD

**Issue by grrowl** [styled-system/styled-system#646]
We should document how `compose()` interacts with variant styles (like `colorStyle`) which may render specific props (like `color`) ineffective when composed.

It makes sense that this might be the behaviour for performance reasons, but it's a bit of a gotcha when on a user level you might expect it to act in the same order and with the same effect as non-composed function.

https://styled-system.com/api/#compose

### examples of the issue

```js
const Box = styled('div')(
  colorStyle,
  color
)

render(<Box colors="whiteOnRed" color="blue" />) // => color will be blue on red
```

```js
const Box = styled('div')(
  compose(
    colorStyle,
    color
  )
)

render(<Box colors="whiteOnRed" color="blue" />) // => color will be white on red
```

```js
const Box = styled('div')(
  compose(
    color
    colorStyle,
  )
)

render(<Box colors="whiteOnRed" color="blue" />) // => color will be white on red
```

**Comment by jxnblk** [comment]
Thanks! The docs probably aren't clear enough on this subject, but generally you shouldn't mix style props with variants that cover the *same* CSS properties. Due to the cascade (i.e. source order), it can cause unexpected issues
