### ISSUE TITLE
Is the default theme documented somewhere?

### ISSUE THREAD

**Issue by nnals** [styled-system/styled-system#652]
Hello,

Is there currently a more efficient way to see the default theme than to look at each file separately (e.g. https://github.com/styled-system/styled-system/blob/master/packages/typography/src/index.js gives me `fontSizes: [12, 14, 16, 20, 24, 32, 48, 64, 72]`)?

Sorry, if I missed something in the docs.

As a side note: It would be quite nice if the docs were searchable.

Thanks for this wonderful library!

Take care,
Nicolai

**Comment by jxnblk** [comment]
Thanks! They're currently documented here https://styled-system.com/api#defaults – but yeah adding search to the docs is a great idea!
