### ISSUE TITLE
Extended `system` usage

### ISSUE THREAD

**Issue by joe-bell** [styled-system/styled-system#653]
Hey @jxnblk, I'm currently implementing a "stack" component in my library based on the great work from [every-layout.dev](https://every-layout.dev/layouts/stack/)

I've removed `margin: 0; padding: 0;` from my `Box` HoC to make this possible, but the last thing left is getting a nice little prop to set my vertical rythym. The only issue is, this is nested in a "lobotomized owl" selector.

Is there a way you'd recommend implementing `system` function mapped to a `property` that is "nested"? 

## Current Workaround

Creating a CSS custom property to store the value, and access that later down the styles. This works absolutely fine, but doesn't add the `px` suffix when the value is a `number` (as it's a custom property), not a `margin`.

```js
import styled from "@emotion/styled";
import { get, system } from "styled-system";
import { Box } from "./box";

/**
 * Pinched from `styled-system`
 * https://github.com/styled-system/styled-system/blob/2a5d4b5aea2ade0e9b9a33009c342cc2145702e3/packages/space/src/index.js#L7
 */
const isNumber = n => typeof n === "number" && !isNaN(n);

const getSize = (n, scale) => {
  if (!isNumber(n)) {
    return get(scale, n, n);
  }

  const isNegative = n < 0;
  const absolute = Math.abs(n);
  const value = get(scale, absolute, absolute);
  if (!isNumber(value)) {
    return isNegative ? "-" + value : value;
  }
  return `${value * (isNegative ? -1 : 1)}px`;
};

/**
 * Stack
 * https://every-layout.dev/layouts/stack/
 */
export const Stack = styled(Box)(
  system({
    space: {
      property: "--rythym",
      scale: "space",
      transform: getSize
    }
  }),
  {
    "& > * + *": {
      marginTop: "var(--rythym)"
    }
  }
);

Stack.defaultProps = {
  as: "div",
  rythym: 2
};
```

## Ideal Solution

Something as follows, where the `property` is assumed by the adjacent `marginTop`

```js
import styled from "@emotion/styled";
import { system } from "styled-system";
import { Box } from "./box";

export const Stack = styled(Box)({
  "& > * + *": {
    marginTop: system({
      rythym: {
        scale: "space"
      }
    })
  }
});

Stack.defaultProps = {
  as: "div",
  rythym: 2
};
```

**Comment by jxnblk** [comment]
Not sure if I'm 100% following what you're trying to achieve, but you can use nested selectors like this (I *think* that's what you're aiming for, but let me know if I misunderstood).

```js
const Stack = styled('div')`
  & > * + * {
    ${space}
  }
`
```

There's the undocumented `createParser` utility as well, that can take custom transform functions if you're looking for something more custom than that

**Comment by joe-bell** [comment]
For this component the aim is **not** to have as much control as `space`, as we want to keep the margins in a single direction; in this case `marginTop`. Hope that's a little clearer?

Perhaps I'm getting too attached to object styles, seems like the solution was this

```jsx
import styled from "@emotion/styled";
import { system } from "styled-system";
import { Box } from "./box";

const rhythm = system({
  space: {
    property: "marginTop",
    scale: "space"
  }
});

/**
 * Stack
 * https://every-layout.dev/layouts/stack/
 */
export const Stack = styled(Box)`
  & > * + * {
    ${rhythm}
  }

  /**
   * Prevent inline 'style' tags injected by SSR from affecting adjacent sibling
   * selector usage.
   * https://github.com/emotion-js/emotion/issues/1178
   */
  & > style:first-child + * {
    margin-top: 0;
  }
`;

Stack.defaultProps = {
  as: "div",
  space: 2
}
```

---

Unless there is a way to achieve this using object styles? 🤔
