### ISSUE TITLE
missing `css` prop on migration guide

### ISSUE THREAD

**Issue by sibelius** [styled-system/styled-system#668]
on v4 with could do something like this

```jsx
import { css } from 'styled-system';
```

and use like this

```jsx
<Text css={{ opacity: 0.7 }}></Text>
```

on v5 we need to use:

```jsx
import css from '@styled-system/css
```

and use like this:

```
<Text css={css({ opacity: 0.7 })></Text>
````

is this correct?

should we add this to migration guide?

**Comment by jxnblk** [comment]
> on v4 with could do something like this
> 
> ```js-jsx
> import { css } from 'styled-system';
> ```

I don't think that's correct. Where did you see this?

**Comment by sibelius** [comment]
I think this was on Rebass instead of styled-system

```jsx
<Flex flexDirection='column' css={{ margin: '0 auto', maxWidth: '960px' }}>
```

what is the alternative on Rebass apis?

**Comment by jxnblk** [comment]
The `css` prop is provided by Emotion and Styled Components, usually via a Babel plugin. The new version of Rebass adds this back in without needing the Babel plugins, FWIW. Going to close this since it sounds like it's not an issue here
