### ISSUE TITLE
Build not updated with 5.0.20?

### ISSUE THREAD

**Issue by dburles** [styled-system/styled-system#673]
Not sure what's happened but it seems like #671 wasn’t actually included in the latest published version of @styled-system/css, 5.0.20.

**Comment by jxnblk** [comment]
Thanks! Yeah, that's odd, will try publishing a patch now

**Comment by jxnblk** [comment]
Republished as `5.0.21` if you can confirm that it's working now

**Comment by dburles** [comment]
@jxnblk yep all good now, thanks!
