### ISSUE TITLE
Disable mobile-first approach

### ISSUE THREAD

**Issue by einomi** [styled-system/styled-system#687]
Hello, how can I disable mobile-first approach for the array props?

I'm not using the mobile-first approach for my project and in this case I have to duplicate values in the array if, for example, some value is same on mobile and tablet devices:
`mb={[20, 20, 80, 110]}`

instead of this I want to write some like this:
`mb={[110, 80, 20]}`
where 110 would match the biggest breakpoint and this would be compiled to something like 

```
.element {
  margin-bottom: 110px;
}

@media screen (max-width: 73.75em) {
  .element {
    margin-bottom: 80px;
  }
}

@media screen (max-width: 62em) {
  .element {
    margin-bottom: 20px;
  }
}
```

so not to `min-width` media queries

**Comment by wladiston** [comment]
You don't need to duplicate values, just pass null to the breakpoints you don't want to change.
```
<Box maxWidth={[ 768, null, null, 1024 ]} />
```

**Comment by einomi** [comment]
@wladiston thanks! It works perfectly for my needs.
