### ISSUE TITLE
Using other props in a system() definition

### ISSUE THREAD

**Issue by webbrewjake** [styled-system/styled-system#700]
Is there a way to use other component props in a `system()` definition?

I currently have:
```javascript
const sidebarSystemSpacing = system({
  spacing: {
    property: 'margin',
    scale: 'sidebar.spacing',
    transform: (value, scale) => `calc(${scale[value]}px / 2)`,
  },
})
```

If I wanted another prop to influence this calculation (for example, `minSpacing`), how would I achieve that? Is it possible? Here's ultimately what I want to achieve:
```javascript
const sidebarSystemSpacing = system({
  spacing: {
    property: 'margin',
    scale: 'sidebar.spacing',
    transform: (value, scale) => `calc(${props.contentMin} - ${scale[value]}px / 2)`,
  },
})
```

Thanks!

**Comment by jxnblk** [comment]
It's not documented, but just added a third argument in `5.1.0` for `props` - e.g. `transform: (value, scale, props) => 'value'`, which I think will let you do what you're looking for

**Comment by webbrewjake** [comment]
Thanks for the quick reply! However this isn't working for me. `props` is undefined. I _think_ you might of missed the `system()` export when you were adding in `props` in `5.1.0`

**Comment by webbrewjake** [comment]
@jxnblk did I miss something here? Or am I looking in the wrong place?

**Comment by jxnblk** [comment]
That link in the codebase isn't really related to the transform function. The example from my last comment should work. If you can create a codesandbox reproduction, it might be more helpful for understanding what you're trying to do

**Comment by Rothmanberger** [comment]
Hey, here's what I'm trying to do. `props` is `undefined` though.

https://codesandbox.io/embed/suspicious-noether-s5esq

**Comment by webbrewjake** [comment]
[Here's what I'm trying to do.](https://codesandbox.io/embed/suspicious-noether-s5esq). `props` is `undefined` though.

**Comment by jxnblk** [comment]
Ah! Looks like props are only passed through with the lower-lever `createParser` API, but it's missing from `system` so I think you've found a bug in the undocumented API :)

**Comment by webbrewjake** [comment]
OK cool. I thought I was going crazy!
