### ISSUE TITLE
Variant example in docs fails in Typescript. 

### ISSUE THREAD

**Issue by benjamingeorge** [styled-system/styled-system#705]
On page https://styled-system.com/variants

This example:
```jsx
const Button = styled('button')(
  variant({
    scale: 'buttons',
    variants: {
      primary: {
        color: 'white',
        bg: 'primary',
      },
      secondary: {
        color: 'white',
        bg: 'secondary',
      },
    },
  })
)
```
get a typescript error 
```
Argument of type '{ scale: string; variants: { primary: { color: string; bg: string; }; secondary: { color: string; bg: string; }; }; }' is not assignable to parameter of type 'VariantArgs'.
  Object literal may only specify known properties, and 'variants' does not exist in type 'VariantArgs'.
```
I basically can't get themeable variants to work when using typescript. 

I'm using
 "@types/styled-system": "^5.0.1",
   "styled-system": "^5.1.0",

**Comment by jxnblk** [comment]
I *think* whoever maintains `@types/styled-system` will need to update the types for the new API

**Comment by benjamingeorge** [comment]
Maybe I will try my first contribution to open source and do a pull request

**Comment by nerdyman** [comment]
I think this can be closed, [`@types/styled-system`](https://www.npmjs.com/package/@types/styled-system) 5.1.1 updated the `VariantArgs` interface.

Thanks @benjamingeorge!

**Comment by earksiinni** [comment]
Can someone provide an example of how to use variant correctly with the new interface? @nerdyman? @benjamingeorge?

**Comment by dittmarconsulting** [comment]
Why is that closed? The issuer clearly asked for an `example` in the docs.

I can't find any example for `VariantArgs` in the docs and the `index.d.ts` file doesn't state what `K` and `TStyle` actually `[key in K]: TStyle` is. I tried so many combinations and I still get errors for the `variant` prop in my component.
