### ISSUE TITLE
add utility to filter relevant props for collectives

### ISSUE THREAD

**Issue by jescowuester** [styled-system/styled-system#707]
when using a utility like `color` or `space` it often forces you to spread all your props on a dom element instead of getting every single possibility

```
MyComponent = (props) => (
	<MyStyledComponent {...props}>
		...
	</MyStyledComponent>
)
```

```
MyComponent = ({m,mt,mb,mr,ml,my,mx,p,...etc}) => (
	<MyStyledComponent
	m={m}
	mt={mt}
	mb={mb}
	mr={mr}
	...
	>
		...
	</MyStyledComponent>
)
```

Something like this could solve the issue

```
MyComponent = (props) => (
	<MyStyledComponent
	{...getSpaceProps(props)}
	>
		...
	</MyStyledComponent>
)
```

**Comment by jxnblk** [comment]
Sorry for the delay! I think this could be a helpful utility to add to the library (both a *pick* and *omit* version), and I think the `@styled-system/should-forward-prop` package could be used for this
