### ISSUE TITLE
Setting an alias as a responsive subarray of the scale

### ISSUE THREAD

**Issue by webbrewjake** [styled-system/styled-system#709]
I'm trying to do create subarrays of my `space` array to use as `defaultProps` in my library components.

Is it possible to do something _like_ the following (this doesn't work, instead the css value for `padding` is set to be literally `4,8,16,32`):

In my `theme.js`:
```js
const space = [0, 2, 4, 8, 16, 32, 64, 128, 256, 512]
space.box = [space[2], space[3], space[4], space[5]]
```

Then in my simplified `Box` component:
```js
const boxSystem = system({
  padding: {
    property: 'padding',
    scale: 'space',
  },
})

export const Box = styled.div`
  ${boxSystem}
  display: block;
`

Box.defaultProps = {
  padding: 'box',
}
```

That way, the default `padding` for all `Box` components can be defined once in the theme, but can also be overridden using the regular `space` scale.

I originally defined my own scale for `Box` by creating a subarray of the `space` array, and set `padding.scale` in the `system()` definition to use that scale, and the `defaultProps` to be `[0, 1, 2, 3]`, but that means when I want to override it, I can no longer use the `space` scale and instead have to provide the explicit values I want.

I hope that makes sense! Thanks.

**Comment by jxnblk** [comment]
The responsive array values only work as props, not as theme definitions, because e.g. `space.box.2` could be a valid value from the theme. Variants let you define responsive styles in the theme, but single style props like this won't work

**Comment by webbrewjake** [comment]
Thanks! I played around with Variants but it wasn't working how I'd like it. You actually gave me an idea regarding your mention of `space.box.2`.

Here's my solution for anyone else wanting to do the same things

In my `theme.js`:
```javascript
const space = [0, 2, 4, 8, 16, 32, 64, 128, 256, 512]
space.box = [space[2], space[3], space[4], space[5]]
```

Then in my simplified `Box` component:
```javascript
const boxSystem = system({
  padding: {
    property: 'padding',
    scale: 'space',
  },
})

export const Box = styled.div`
  ${boxSystem}
  display: block;
`

Box.defaultProps = {
  padding: ['box.0', 'box.1', 'box.2', 'box.3'],
}
```

Now I can set the default padding for all `Box` components in the `theme`, but I can also override the padding using the universal `space` scale.
