### ISSUE TITLE
5.0.18 Variants API changes feel like a step backwards: Just me?

### ISSUE THREAD

**Issue by kevinSuttle** [styled-system/styled-system#724]
I'm struggling to see the value in moving theme values out of a centralized file and inline into components. I give benefit of the doubt where it's due, but maybe some visual examples would help explain the advantages? 

In practice, this feels like it facilitates competing props and "[boolean traps](https://spicefactory.co/blog/2019/03/26/how-to-avoid-the-boolean-trap-when-designing-react-components/)", but to be honest, I'm just shooting from the hip here. 

Can you shed some light on the decisions made here, @jxnblk? 🙏

**Comment by jxnblk** [comment]
I think this blog post goes into more detail about the rationale FWIW https://jxnblk.com/blog/a-conceptual-look-at-theming/

**Comment by kevinSuttle** [comment]
Thanks for the context. I can definitely see the vision and reasoning now.

**Comment by kevinSuttle** [comment]
I'm wondering about primitives/extension, default values from theme, and React within and _without_ the context of the new variants API. 

Example: 
```jsx
// primitives/Text.jsx

import styled from '@emotion/styled';
import {
  colorStyle,
  compose,
  system,
  textStyle,
  typography,
} from 'styled-system';
import shouldForwardProp from '@styled-system/should-forward-prop';
import {Box} from './Box';

const whiteSpace = system({whiteSpace: true});
const textDecoration = system({textDecoration: true});

const styleProps = compose(
  colorStyle,
  textDecoration,
  textStyle,
  typography,
  whiteSpace
);

export const Text = styled(Box, {
  shouldForwardProp,
})(
  {
    label: 'text-primitive',
  },
  styleProps
);

Text.defaultProps = {
  as: 'span',
  fontFamily: 'sans',
};

```

### Old way
```jsx
// Heading.jsx

import * as React from 'react';
import {Text} from '../primitives/Text';

export const Heading = (props: Props) => {
  const {as = 'h2', size = 'medium', children, color = 'text.default'} = props;

  return (
    <Text
      color={color}
      as={as}
      fontFamily="system"
      margin={0}
      textStyle={headingStyles[size]}
      {...props}
    >
      {children}
    </Text>
  );
};
```

### New way
```jsx

export const VariantHeading = styled(Text)(
 {fontFamily: 'headings'}, // doesn't work without @styled-system/css to pick up theme values
  variant({
    scale: 'fonts',
    prop: 'size',
    variants: {
      small: {
        fontSize: 2,
        lineHeight: 1,
        fontWeight: 2,
      },
      medium: {
        fontSize: 3,
        lineHeight: 1,
        fontWeight: 2,
      },
      large: {
        fontSize: 5,
        lineHeight: 3,
        fontWeight: 1,
      },
      xlarge: {
        fontSize: 6,
        lineHeight: 3,
        fontWeight: 0,
      },
    },
  })
);
```

- What about React props handling/rendering logic, etc? 
- How does this new API allow for setting of default styles (not even default props), that are based on theme values? Does it require `@styled-system/css`?
