### ISSUE TITLE
Order of applied css

### ISSUE THREAD

**Issue by sktt** [styled-system/styled-system#743]
**Describe the bug**
`defaultProps` appear as to be applied after other props.

**To Reproduce**
https://codesandbox.io/s/solitary-platform-y9cmv

**Expected behavior**
Thing should use provided `mt`

**Additional context**
may be related to #549

**Comment by JerryGreen** [comment]
Wait, "defaultProps are merged after the element's props" makes no sense. If default values can't be overridden, then they are not "default" values.

I'm facing the same problem with Flex, wanted to set `justifyContent="flex-end"`, but default values (space-between) has higher precedence in output styles (I'm using [Primer Components](https://github.com/primer/components))
