### ISSUE TITLE
Breakpoints bug when using numbers of different length

### ISSUE THREAD

**Issue by ThePuzzlers** [styled-system/styled-system#761]
Hello hello,
I've encountered a weird behavior when dealing with breakpoints as objects. Regarding your documentation I came up with the following breakpoints within a breakpoints.js file:

```
const breakpoints = [
  '21em', // 336px
  '35em', // 560px
  '45em', // 720px
  '64em', // 1024px
  '75em', // 1200px
  '90em', // 1400px
  '100em', // 1600px
];

breakpoints.phone_portrait = breakpoints[0];
breakpoints.phone_landscape = breakpoints[1];
breakpoints.tablet_portrait = breakpoints[2];
breakpoints.tablet_landscape = breakpoints[3];
breakpoints.desktop_s = breakpoints[4];
breakpoints.desktop_m = breakpoints[5];
breakpoints.desktop_l = breakpoints[6];

export default breakpoints;
```

Afterwards I'm pulling them into the theme.js file. So far so good but once I try to reference them as follows: 

```
H1.defaultProps = {
  fontFamily: 'teko_bold',
  fontWeight: 'normal',
  fontSize: {
    _: 1,
    phone_portrait: 2,
    phone_landscape: 3,
    tablet_portrait: 4,
    tablet_landscape: 5,
    desktop_s: 6,
    desktop_m: 7,
    desktop_l: 9,
  },
};
```

**things get stuck at `90em` - never reaching `100em`**. (The numbers for the fontsizes are just referencing the position of the actual value within the theme.js array for fontSizes)

However, if I prefix all of the values within breakpoints.js so the number will have the same length:

```
const breakpoints = [
  '021em', // 336px
  '035em', // 560px
  '045em', // 720px
  '064em', // 1024px
  '075em', // 1200px
  '090em', // 1400px
  '100em', // 1600px
];
```

**Everything works as expected and even the `100em` breakpoint gets picked up correctly**. But it's a weird thing to do...

**Comment by jxnblk** [comment]
Thanks! Could you create a reproduction in CodeSandbox?

**Comment by ThePuzzlers** [comment]
Hi @jxnblk thanks for getting back to me. Here's the codesandbox link. Sry I didn't include it right away...

https://codesandbox.io/embed/potential-styled-system-bug-qxf5g

The working solution is commented out within breakpoints.js

You can see the bug within the inspector tools as without the 'prefix' the H1 stops at 90em but if you have the 0 as a prefix it goes all the way to 100em.

<img width="1920" alt="100em_is_never_reached" src="https://user-images.githubusercontent.com/16598375/64265459-84e8b300-cf65-11e9-94da-6debf3b92acf.png">
<img width="1918" alt="100em_is_reached" src="https://user-images.githubusercontent.com/16598375/64265460-85814980-cf65-11e9-9613-26605e75a8c6.png">

**Comment by jxnblk** [comment]
Thanks! I believe this is due to how it tries to sort object-based responsive styles alphabetically, and `100` is before `90` alphabetically, causing a cascade/source order issue in CSS

**Comment by ThePuzzlers** [comment]
I guess I don't get it just yet. Wouldn't this mean that the 100em always gets called instead of the 90? It's the same with px, though. If you have the values let's say:

600px
720px
1100px

it gets stuck on the 720px

**Comment by jxnblk** [comment]
Yes, so alphabetically, the media rule with 100em is before the 90em in *source order* (i.e. the cascade), which means the 90em rule takes precedence and due to how the cascade part of CSS works. This is a bug with Styled System, because it should be smarter about how it sorts the object-based responsive styles
