### ISSUE TITLE
Variant does not seem to work with custom props

### ISSUE THREAD

**Issue by slightly-askew** [styled-system/styled-system#810]
**Describe the bug**
Referencing a custom prop within a `variant()` does not seem to return a value

**To Reproduce**

[Codesandbox example](https://codesandbox.io/embed/cocky-glade-gsicb)

Given a custom `system` prop function to add a coloured border:
```javascript
const systemBorder = props =>
  system({
    bordercol: {
      property: 'border',
      scale: 'colors',
      transform: value => {
        return `2px solid ${value}`
      },
    },
  })
```
I am referring to the custom prop within a variant like so: 
```javascript
const colorStyles = variant({
  variants: {
    primary: {
      bordercol: 'blue',
    },
    secondary: {
      bordercol: 'green',
    },
  },
})
```
However the border colour value from the variant seems to be ignored by my custom prop. I have checked that the custom prop function works on it's own by adding a prop onto the component directly and observing that the border will change color.

**Expected behavior**
The custom prop should be fulfilled by the value it gets from a variant declaration

**Additional context**
Styled components v4.3.2
Styled system v5.1.1

**Comment by jxnblk** [comment]
Thanks, but I think there might be a misunderstanding of how variants work. Variants allow you to create sets of *styles* (not props) and `bordercol` is not a CSS property. You could either use the native `borderColor` CSS property here or the shorthand `border` property

**Comment by slightly-askew** [comment]
Thanks @jxnblk for the explanation! Makes a lot of sense now 👍 
I'd not even noticed the extensive theming of borders, refactored to get the effects I needed.

**Comment by zackphilipps** [comment]
@jxnblk Maybe the docs should be updated then? [Here](https://styled-system.com/variants) the example seems to have props _and_ styles (looking at `bg`, which is a style prop):

```js
// example Button with variants
import styled from 'styled-components'
import { variant } from 'styled-system'

const Button = styled('button')(
  {
    appearance: 'none',
    fontFamily: 'inherit',
  },
  variant({
    variants: {
      primary: {
        color: 'white',
        bg: 'primary',
      },
      secondary: {
        color: 'white',
        bg: 'secondary',
      },
    }
  })
)
```

and [here](https://styled-system.com/api#variant), looking at the values, they seem to be all props.

This is of current interest to me, because I'm implementing variants on my buttons now, which have gradients and box shadows. During a quick test just now, it appears that setting `bg` within the variant worked (it even pulled the color value from the theme), but not `boxShadow`. This is confusing, since `boxShadow` is not a _custom_ prop -- it's already defined as a style prop by styled-system.

So, it appears that _some_ props are supported, but not all? Or maybe I'm just wrong about everything.

**Comment by jacobbrown0192** [comment]
@jxnblk If you have a minute can you answer @zackphilipps question? 

Right now I am trying to add background as a theme to my varients to add gradients to the background of some of my components. The plan is to have a dark and light mode and have different gradients based on that (similar to color modes).

Right now my background custom prop is not resolving in the variants.

**Comment by kuldeepkeshwar** [comment]
I ran into a similar problem today. the reason, why `bg` works & not any other custom props is `variant` internally, uses `core/css` and `css` has  a mapping of [aliases](https://github.com/styled-system/styled-system/blob/0a6805a96be69efb449ef5fcf3804a082127ba9c/packages/css/src/index.js#L17)/scales.

**Comment by zackphilipps** [comment]
That makes sense. Yeah, I'm not sure what I was talking about re: `boxShadow`. Maybe I had the scale messed up at the time.

**Comment by zackphilipps** [comment]
@jacobbrown0192 Just a word of caution in case you have done this, I wouldn't name a custom prop "background" since that is a reserved prop and you might get unexpected results. Also, based on @kuldeepkeshwar's comment, looks like we just have to live with using built-in style props for variants.

**Comment by zackphilipps** [comment]
Yeah, that makes sense. Not sure what I was talking about re: `boxShadow`. Maybe I had the scale messed up at the time.
