### ISSUE TITLE
Array with `null` generates empty media query

### ISSUE THREAD

**Issue by wfifer** [styled-system/styled-system#813]
Looking at docs [here](https://styled-system.com/guides/array-props/), passing `null` in an array position should not generate a media query for corresponding to that position, but that doesn't appear to be the case. I'm using latest `styled-components` and `styled-system`. It's become crucial to whittle down our generated css due to Google's low-low 50kb AMP limit, so any help would be extremely appreciated.

**Comment by jxnblk** [comment]
`null` values used to not render but this causes issues – see #561 #551 #549 – without a clear way to handle this sort of issue, I'm afraid it will have to return an empty media rule for the time being
