### ISSUE TITLE
Media Queries theme key not working

### ISSUE THREAD

**Issue by freislot** [styled-system/styled-system#826]
Documentation says: 
For convenience and for use with other styling approaches, a mediaQueries scale derived from the breakpoints scale can be added to the theme object.

`breakpoints: [ '40em', '52em', '64em' ]`

```
mediaQueries: {
  small: `@media screen and (min-width: ${breakpoints[0]})`,
  medium: `@media screen and (min-width: ${breakpoints[1]})`,
  large: `@media screen and (min-width: ${breakpoints[2]})`,
}
```

I want change min-width in media queries to max-width and this is my code from theme:
```
const breakpoints = ['320px', '768px', '1024px', '1200px'];
// aliases
breakpoints.xs = breakpoints[0];
breakpoints.sm = breakpoints[1];
breakpoints.md = breakpoints[2];
breakpoints.lg = breakpoints[3];

/** Тема */
export const theme = {
  breakpoints,
  mediaQueries: {
    xs: `@media screen and (max-width: ${breakpoints[0]})`,
    sm: `@media screen and (max-width: ${breakpoints[1]})`,
    md: `@media screen and (max-width: ${breakpoints[2]})`,
    lg: `@media screen and (max-width: ${breakpoints[3]})`,
  }
}
```

In my component i use object with aliasses
```
<Box
  width={{
    xs: '100px',
    sm: '200px',
    md: '300px',
    lg: '400px',
  }}
>
  {'I\'m box!!!'}
</Box>
```
but in chrome inspector a see than mediaQueries not working and apply default min-width

@media screen and (min-width: 1200px)
.eUQXYq {
    width: 400px;
}
@media screen and (min-width: 1024px)
.eUQXYq {
    ~~width: 300px;~~
}
@media screen and (min-width: 768px)
.eUQXYq {
    ~~width: 200px;~~
}
@media screen and (min-width: 320px)
.eUQXYq {
    ~~width: 100px;~~
}

**Comment by jxnblk** [comment]
The values provided for the `width` prop will always come from `theme.breakpoints` and are always `min-width` mobile-first media queries.
