### ISSUE TITLE
Could not find a declaration file for module '@styled-system/theme-get'. 

### ISSUE THREAD

**Issue by mounikakella** [styled-system/styled-system#830]
When I import ```import { themeGet } from '@styled-system/theme-get';``` in my react typescript project, it is throwing the following error.

Could not find a declaration file for module '@styled-system/theme-get'. '**<project path>**/node_modules/@styled-system/theme-get/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/styled-system__theme-get` if it exists or add a new declaration (.d.ts) file containing `declare module '@styled-system/theme-get';`

How to fix this?

**Comment by seivan** [comment]
Take a look at https://github.com/styled-system/styled-system/issues/609

**Comment by Jerry-Hong** [comment]
@mounikakella @seivan 
I have created a PR to DefinitelyTyped, it will fix this issue
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40275
