### ISSUE TITLE
how to opt out of using array index?

### ISSUE THREAD

**Issue by harlanlewis** [styled-system/styled-system#847]
Hello, is there a way to reference a `space` value by its value, rather than array index? I'll steer clear of discussing the merits of index vs value vs alias (that's been hashed out plenty already), just looking to understand the intended mechanics. Apologies if this has been covered, wasn't able to find it.

For example, the [styled system homepage](https://styled-system.com/#space-theming) shows this array for space theming:

```
export default {
  space: [0, 4, 8, 16, 32, 64, 128, 256, 512],
}
```

How would one use the values `4` and `8` _without_ selecting them by index? My understanding is using `<Box mx={4}>…` or `<Box mx={8}>` would return elements with horizontal margins of 32 or 512 pixels respectively.

My preference would be for `<Box mx={4}>…` would be to return an element with horizontal margins of 4px, and using an unspecified value like `<Box mx={5}>…` would throw an error for using a value outside of the defined scale

**Comment by jxnblk** [comment]
You can pass string values with units to use hard-coded, non-theme-based values, e.g. `m='4px'` – the whole point of using scales in Styled System is to *not* think about the actual values, if that makes sense

**Comment by harlanlewis** [comment]
Gotcha, makes sense. 

I'm certainly a fan of using scales for things like z-index, where the values can be abstract (eg `[100, 200, 300]`) and only have meaning relative to each other, but prefer the clarity of actual values for sizes and the like. Index order instability can also be a tough juggle if project standards are in flux.

Thanks for reply!
