### ISSUE TITLE
Inconsistent short props overriding

### ISSUE THREAD

**Issue by ludovicmnji** [styled-system/styled-system#849]
**Describe the bug**
When you define `marginTop` in default props on a Styled component using styled-system `space` helper (for example), the default prop is applied in priority of other short props define on the component itself (`marginY` for example).
In the Codesandbox below, the 2th `Div` component should have a `margin-top` of 10px and a `margin-bottom` of 10px thanks to `marginY="10px"`. Currently, it just has the right margin-bottom. It doesn't seem to be a normal behaviour.

**To Reproduce**
https://codesandbox.io/embed/styled-system-props-overriding-6cwqc

**Expected behavior**
The prop defines on component should take precedence over default props. If `marginY` prop is of less priority than `marginTop`, it should be specified in the documentation.

**Additional context**
Sorry for the title of the issue, I don't know if it's quite explicit.

**Comment by mjaycub** [comment]
We're also experiencing this issue. Is there any fix for this?

**Comment by jxnblk** [comment]
Closing in favor of #1058
