### ISSUE TITLE
How to override default styles?

### ISSUE THREAD

**Issue by isaacalves** [styled-system/styled-system#882]
What is the recommended or possible way to override default styles?

Let's say I have a Section and it has some responsive padding:

```
Section = styled.div`
// ...
  ${space}
`

Section.defaultProps = {
  padding: {
    default: `25px 0`,
    sm: `40px 0`,
  },
}
```

Now, I'd like to override just the top padding on a specific instance of the `Section`, so I'm expecting to be able to use this:

```
<Section pt={0}>
```

But it doesn't work - I'd need to override the whole padding. `py` also wouldn't work. I could set `padding-top` and `padding-bottom` separately as default styles, but that feels a bit awkard, especially if I have a component with all 4 paddings and I want to be able to overwrite them all.

Thins get even more complicated when I want to have conditional styles based on props (let's say, a `Button` with a `small` prop, which would mean smaller paddings and margins.

So, styles depend on media queries, props, and can also be overwritten. 
How should one go about this? Any ideas?

**Comment by mjaycub** [comment]
@jxnblk I just saw your comment on #984 with the same `cascade` label, but this above issue of overriding styles mentioned by @isaacalves is an issue right?

I'm encountering it a lot also in my codebase and am trying to find a fix for it. My issue(s) are similar to that described above where a prop such as `pt` would not override the default `padding` for example.

**Comment by jxnblk** [comment]
The `padding` shorthand and `padding-top` property are **different** properties in CSS -- this is an issue with the CSS cascade, which Styled System does not currently try to account for

**Comment by mjaycub** [comment]
Ah I see, that makes sense. Thanks for the explanation.

**Comment by jxnblk** [comment]
Closing in favor of #1058
