### ISSUE TITLE
Is it possible to nest the theme, or does it have to live at the root?

### ISSUE THREAD

**Issue by stonebk** [styled-system/styled-system#884]
Let's say you have a theme:
```js
const theme = {
    colors: {
        ...
    },
    ...
};
```

You usually pass this to `ThemeProvider` as such:
```jsx
<ThemeProvider theme={theme}>
```

Is it possible to nest the theme such that it is not at the root?

```jsx
<ThemeProvider theme={{ myNestedTheme: theme }}>
```

I want to basically namespace the theme -- is it possible to do this with styled-system?

**Comment by johnsantos-wag** [comment]
I also have a similar concern about this like nested theme with different theme.

What have you done @stonebk ?

**Comment by jxnblk** [comment]
There isn't any support for namespacing within the theme context, but note that React contexts are scoped by default so this is only used in Emotion or Styled Components' contexts

**Comment by stonebk** [comment]
> There isn't any support for namespacing within the theme context, but note that React contexts are scoped by default so this is only used in Emotion or Styled Components' contexts

Yeah, I'm looking specifically for namespacing within the styled-components context. We have a lot of teams that build components, and I would like to keep the core theme namespaced so that there aren't accidental naming collisions.

@johnsantos-wag I'm more in the exploratory phase right now looking to switch to styled-system, so I haven't done anything at this point.
