### ISSUE TITLE
Unknown Prop Warning

### ISSUE THREAD

**Issue by osamajandali** [styled-system/styled-system#898]
**Describe the bug**
When using styled components to custom style react router Link and then use styled system with its props I get unknown props warning

**To Reproduce**
Extend the style of react router Link using styled component and add styled system props to it

Use codesandbox to create a reproduction:
https://codesandbox.io/s/unknown-props-warning-ec8st

**Expected behavior**
Should not give that warning

**Additional context**
Maybe it is not styled system bug but you may guide me through this bug

**Comment by jxnblk** [comment]
Is this the issue? https://styled-system.com/guides/removing-props-from-html

**Comment by osamajandali** [comment]
Yeah I think it's.. 
How about adding example to the docs to make the problem more clear? as I have read it in the docs and when I see the problem I could not relate the issue with that part in the docs

**Comment by jxnblk** [comment]
PRs welcome!
