### ISSUE TITLE
Typography maybe missing textOverflow and whiteSpace props?

### ISSUE THREAD

**Issue by TheSisb** [styled-system/styled-system#922]
Looking at the [Typography bucket in v5](https://styled-system.com/api/#typography), I couldn't help but notice that maybe the `textOverflow` and `whiteSpace` props were overlooked?  They are commonly used to make text overflow into an ellipsis.

[edit] And also possibly `textDecoration`?

**Comment by jxnblk** [comment]
Thanks for the question! Generally, I don't think it's common to change `white-space` or `text-overflow` properties on a per-component-instance basis with props. If you need to dynamically change these values with props, I'd suggest using [custom props](https://styled-system.com/custom-props)

**Comment by michalstypa** [comment]
For all those looking for a TL;DR; in the comments:

```jsx
import { system } from 'styled-system'

const wordBreak = system({
  prop: 'wordBreak',
  cssProperty: 'word-break',
})

const whiteSpace = system({
  prop: 'whiteSpace',
  cssProperty: 'white-space',
})

const customProps = () => {
  return system({ wordBreak: true, whiteSpace: true })
}

export const P = styled.p`
  ${customProps};
`
```
