### ISSUE TITLE
Seeing width=[object,object] everywhere

### ISSUE THREAD

**Issue by zammer** [styled-system/styled-system#931]
Hi I've looked through the docs and issues but can't see and answer to this question. 

When doing `<Column width={{xs: s, l: l}} />` in the outputted html I see `<div width="[object, object]">` I still get the correct breakpoints in the css but is there anyway to get rid of the `width="[object, object]"` in the html.

<img width="336" alt="Screenshot 2019-11-08 at 14 22 48" src="https://user-images.githubusercontent.com/754039/68483838-2923fa00-0234-11ea-81c2-0a1c46e116a2.png">

Apologies if this has been answered before.

**Comment by jxnblk** [comment]
If you're using styled-components, they don't offer an API to remove attributes, but Emotion does, see https://styled-system.com/guides/removing-props-from-html
