### ISSUE TITLE
Setting responsive width to 1 doesn't convert to 100% but uses `space` scale

### ISSUE THREAD

**Issue by ElForastero** [styled-system/styled-system#932]
**Describe the bug**
```jsx
<Box width={[ 1, 1 / 4 ]} />
```

`1` will not be converted to `100%`, but instead it will be the `space[1]` value from config.
`0.99` works well.

**To Reproduce**
Can't reproduce it in sandbox :(

**Screenshots**
![image](https://user-images.githubusercontent.com/5102818/68527760-137e0580-0304-11ea-9aa9-edbaa7da3233.png)

**Additional context**
"styled-system": "^5.1.2"
"styled-components": "^5.0.0-beta.11"

**Comment by jxnblk** [comment]
If you've defined `theme.sizes[1]`, this is the intended behavior. You can use `'100%'` to set width to `100%`
