### ISSUE TITLE
set background gradient doesn't work 

### ISSUE THREAD

**Issue by travis-joe** [styled-system/styled-system#933]
**example**

```
        <Flex
          bg="linear-gradient(270deg,rgba(255,186,56,1) 0%,rgba(255,108,0,1) 100%)"
          width="100%"
          paddingX="30px"
          paddingY="16px"
          color="white"
        >
```

like that, it doesn't work, how to do it?

**Comment by jxnblk** [comment]
The `bg` prop is for `background-color`. If you want a `background-images`, you'll need to use the `background` utility, see https://styled-system.com/table#background
