### ISSUE TITLE
Custom prop with css package

### ISSUE THREAD

**Issue by lishine** [styled-system/styled-system#944]
How can I use custom props in css prop?
Same question for theme-ui, it uses sx compatible to css. But what if I write custom prop using system(). How can I use it in sx?
Thanks

**Comment by jxnblk** [comment]
The `css` utility cannot be customized. Since the goal with that package is interoperability with various themes and tools, it's more of a hard-coded convention. If you want custom props, you can, of course, use styled-system

**Comment by lishine** [comment]
@jxnblk But I want to put styles into css prop instead of spreading into component props. I like the idea of separation styles into it's own prop.
With styled-system I just use css={my_css(...)}. 
But with theme-ui it is built into jsx.
I like to write with native html elements <h1 sx={{}} />
The customization option is provided for styled-system, pity it is not for css prop.
Maybe do some plugin option...
