### ISSUE TITLE
Inherit prop from parent component

### ISSUE THREAD

**Issue by omhoumz** [styled-system/styled-system#945]
If we have Box defined like this:
```jsx
export const Box = styled.div`
  ${space}
`
```

And a parent component that uses `Box`:

```jsx
export const ParentBox = ({ children }) => (
  <Box>{children}</Box>
)
```

I want to be able to pass all the props that `styled-system` supports, without explicitly defining them on `ParentBox` or using the spreading `...otherProps` "hack“:

```jsx
export const ParentBox = ({ children, ...otherProps }) => (
  <Box {...otherProps}>{children}</Box>
)
```

Is there a way to do this?

**Comment by jxnblk** [comment]
Passing props through with rest isn't really a "hack", and it sounds like exactly what you want in this case. If you need to filter the styled-system props specifically, you can use the [`@styled-system/props`](https://github.com/styled-system/styled-system/tree/master/packages/props) package

**Comment by indrasantosa** [comment]
@jxnblk This is an answer that I've been looking for. I think this answer should have been posted in https://styled-system.com/guides/removing-props-from-html as well
