### ISSUE TITLE
Responsive border color

### ISSUE THREAD

**Issue by rich-wvs** [styled-system/styled-system#983]
When you set a responsive border prop, you have to set the "borderColor" twice, even if it's the same colour. For example:

<Column
     borderRight={["0", "1px solid"]}
     borderColor={["grey.0", "grey.0"]}
     width={[1, 1 / 2]}
>

To reproduce try something like:

<Column
     borderRight={["0", "1px solid"]}
     borderColor="white"
     width={[1, 1 / 2]}
>

**Comment by jxnblk** [comment]
Closing in favor of #1058
