### ISSUE TITLE
Is @styled-system/css compatible with @emotion/core css??

### ISSUE THREAD

**Issue by ruifortes** [styled-system/styled-system#985]
Hi.
Does @styled-system/css enhance emotion css function or just replace it?
Thanks

**Comment by jxnblk** [comment]
It's intended for use with Emotion's `css` prop. See https://styled-system.com/css/ - you might also be interested in https://theme-ui.com

**Comment by lukaskoeller** [comment]
@jxnblk Do you accidentally also know how to use `variant()` with the `css` prop?

I tried this, but it says `variant is not a function`

```js
export const Example = ({ 
  disabled, 
  variant, 
  children, 
  ...props 
}) => {
  return (
    <button
      css={
          css({
            backgroundColor: "primary.base"
          }),
          variant({
            variants: {
              primary: {
                backgroundColor: "primary.base"
              },
              secondary: {
                backgroundColor: "light.0",
                boxShadow: "button",
                color: "primary.base"
              },
            }
          })
      }
      disabled={disabled} 
      variant={variant} 
      {...props}
    >
      { children }
    </button>
  )
}
```

**Comment by jxnblk** [comment]
@lukaskoeller looks like you have a scope issue: the `props.variant` declared in function scope is overriding the module scope's `variant`
