### ISSUE TITLE
why is it not allowed to use ${color } in @styled-system/css

### ISSUE THREAD

**Issue by uptonking** [styled-system/styled-system#998]
**Spectrum.chat**

If you have a related post on https://spectrum.chat/styled-system, please post it here  
[post](https://spectrum.chat/styled-system/general/why-is-it-not-allowed-to-use-color-in-styled-system-css~b389337d-0f3b-4d98-876f-4700306273d1)  

```
 <button
  css={css`
    background: deepskyblue;
    color: black;
    border: none;
    border-radius: 3px;
    padding: 10px 30px;
    ${color}
  `}
>
  { props.children} 
</button>
```

if removing the line `${color}`, it works fine.
It would be nice if it's possible to add style props in the `styled-components` way like this

```
const Box = styled.div`
  ${color}
`
```

is it possible?
there is not much documentation about `@styled-system/css`.
Since css method depends on css prop to work, is it similar to the css method from `@emotion/core`?

**Comment by jxnblk** [comment]
The `css` package only accepts objects as an argument. It's *not* a tagged template literal function

**Comment by uptonking** [comment]
if removing the line ${color}, it works fine.  

so css can be used as a tag function. but it’s confusing that ${color} expression cannot be put inside

**Comment by jxnblk** [comment]
The fact that that works is coincidence and not part of the public API, which means it may break in a future release
