### ISSUE TITLE
Arrays or Objects as prop values?

### ISSUE THREAD

**Issue by stonebk** [styled-system/styled-system#999]
I don't think this is a very common use-case, but with styled-system using arrays and objects for responsive media queries, does that mean you can't use arrays or objects as prop values?

**Comment by jxnblk** [comment]
Sorry I’m not sure I understand the question, can you please include a code example?

**Comment by stonebk** [comment]
> Sorry I’m not sure I understand the question, can you please include a code example?

It's really hard to think of an actual use-case which makes me think this is a non-issue. But basically, if I want one of my props to accept an array of values:

```
// Note the array is not different string values for different breakpoints,
// but rather an array of values for all breakpoints
<Component colors={['red', 'white', 'blue']} />
```

Then with styled-system responsive syntax you would do something like:

```
// Uses different array of colors at different breakpoints
<Component colors={[['red', 'white', 'blue'], ['black', 'yellow', 'orange']]} />
```

...or as an object:

```
<Component colors={{ _: ['red', 'white', 'blue'], sm: ['black', 'yellow', 'orange'] }} />
```

I'm not sure if you would ever actually want to do this, just wondering if styled-system always assumed arrays/objects were responsive values.

**Comment by jxnblk** [comment]
Ah! I get what you mean now. Yes, Styled System does assume that array or plain object values are responsive. If you want to use objects as values, but don't need the responsive shorthand, you can probably roll your own style function, depending on your needs. There has been discussion of adding react-native utilities, which wouldn't need responsive values, but no one has worked on that yet, afaik

**Comment by stonebk** [comment]
Great, thanks for the quick responses @jxnblk!
